Horizon: Assembly parsing and AST->Core transformation
Assembly parsing and AST->Core transformation
Classes
class horizon::AstAlloc
class horizon::AstAsm
class horizon::AstBCInsn
class horizon::AstBInsn
class horizon::AstCallInsn
class horizon::AstCastInsn
class horizon::AstClass
class horizon::AstClosure
class horizon::AstConstExpr
class horizon::AstConstantIdentifier
class horizon::AstConstantNull
class horizon::AstConstantInteger
class horizon::AstConstantFloat
class horizon::AstConstantChar
class horizon::AstConstantString
class horizon::AstDefaultValue
class horizon::AstDecl
class horizon::AstEqInsn
class horizon::AstFnPtr
class horizon::AstFunction
class horizon::AstInPackage
class horizon::AstInsn
class horizon::AstInterface
class horizon::AstIsA
class horizon::AstLabel
class horizon::AstLoadInsn
class horizon::AstMetadata
class horizon::AstMovInsn
class horizon::AstNode
class horizon::AstNullInsn
class horizon::AstOperand
class horizon::AstParam
class horizon::AstParInsn
class horizon::AstRegister
class horizon::AstRetInsn
class horizon::AstStoreInsn
class horizon::AstType
class horizon::AstTypedef
class horizon::AstUsingPackage
class horizon::AstVariable
class horizon::AstVariant
class horizon::AsmParser
class SymbolTableBase< T >
Namespaces
namespace horizon
namespace h
Defines
#define VARIABLE 258
#define COLON 259
#define FUNCTION 260
#define LBRACE 261
#define RBRACE 262
#define LPAREN 263
#define RPAREN 264
#define LBRACKET 265
#define RBRACKET 266
#define COMMA 267
#define B_MNEMONIC 268
#define BC_MNEMONIC 269
#define CALL 270
#define CAST_MNEMONIC 271
#define SIMPLE_MNEMONIC 272
#define RET 273
#define FLOAT 276
#define IMPLEMENTS 277
#define EXTENDS 278
#define IN 279
#define QUOTE 280
#define BACKTICK 317
#define DEC_NUMBER 281
#define IDENTIFIER 282
#define NEWLINE 283
#define PERIOD 284
#define CLASS 285
#define INTERFACE 286
#define UNKNOWN 290
#define DOUBLE 291
#define INTEGER 292
#define PERCENT 295
#define ASTERISK 296
#define VARIANT 297
#define USING 298
#define CONST 299
#define FAT_COMMA 300
#define FLOAT_NUMBER 301
#define STRING 302
#define CHARACTER 303
#define EQUALS 304
#define ALLOC 305
#define LANGLE 306
#define RANGLE 307
#define LOAD 308
#define STORE 309
#define PAR 310
#define PAR_ASYNC 311
#define DOT_DOT 313
#define STEP 314
#define SYNC 315
#define RO 316
#define PUBLIC 318
#define PRIVATE 319
#define PROTECTED 320
#define API_ 321
#define TOK_NULL 322
#define CLOSURE 323
#define IS_A 324
#define AT 325
#define STATIC 326
#define VIRTUAL 327
#define ASM 328
#define SIDEEFFECT 329
#define ALIGNSTACK 330
#define TYPEDEF 331
Enumerations
enum horizon::AstAsm::ConstraintState { horizon::AstAsm::Output, horizon::AstAsm::Input, horizon::AstAsm::Clobber }
Functions
horizon::AstAlloc::~AstAlloc ()
virtual void horizon::AstAlloc::Print (std::ostream &stream)
virtual std::string horizon::AstAlloc::GetName ()
AstType * horizon::AstAlloc::GetType ()
void horizon::AstAlloc::SetType (AstType *x)
AstRegister * horizon::AstAlloc::GetTarget ()
void horizon::AstAlloc::SetTarget (AstRegister *x)
virtual void horizon::AstAlloc::Identify (SymbolTable &symtab)
virtual void horizon::AstAlloc::Resolve (SymbolTable &symtab)
virtual void horizon::AstAlloc::ToCore (horizon::Module &module, horizon::FunctionSignature *fn, horizon::Block *block)
horizon::AstAsm::AstAsm (bool side, bool align, std::string a)
horizon::AstAsm::~AstAsm ()
virtual void horizon::AstAsm::Print (std::ostream &stream)
virtual std::string horizon::AstAsm::GetName ()
std::list< Constraint > & horizon::AstAsm::GetConstraints (ConstraintState state)
void horizon::AstAsm::AddConstraint (std::string mode, AstRegister *r, int state)
virtual void horizon::AstAsm::Identify (SymbolTable &symtab)
virtual void horizon::AstAsm::Resolve (SymbolTable &symtab)
virtual void horizon::AstAsm::ToCore (horizon::Module &module, horizon::FunctionSignature *fn, horizon::Block *block)
horizon::AstBCInsn::~AstBCInsn ()
virtual void horizon::AstBCInsn::Print (std::ostream &stream)
virtual std::string horizon::AstBCInsn::GetName ()
AstNode * horizon::AstBCInsn::GetConditionRegister ()
void horizon::AstBCInsn::SetConditionRegister (AstNode *x)
std::string horizon::AstBCInsn::GetTrueIdentifier ()
void horizon::AstBCInsn::SetTrueIdentifier (std::string x)
std::string horizon::AstBCInsn::GetFalseIdentifier ()
void horizon::AstBCInsn::SetFalseIdentifier (std::string x)
virtual void horizon::AstBCInsn::Identify (SymbolTable &symtab)
virtual void horizon::AstBCInsn::Resolve (SymbolTable &symtab)
virtual void horizon::AstBCInsn::ToCore (horizon::Module &module, horizon::FunctionSignature *fn, horizon::Block *block)
horizon::AstBInsn::~AstBInsn ()
virtual void horizon::AstBInsn::Print (std::ostream &stream)
virtual std::string horizon::AstBInsn::GetName ()
std::string horizon::AstBInsn::GetIdentifier ()
void horizon::AstBInsn::SetIdentifier (std::string x)
virtual void horizon::AstBInsn::Identify (SymbolTable &symtab)
virtual void horizon::AstBInsn::Resolve (SymbolTable &symtab)
virtual void horizon::AstBInsn::ToCore (horizon::Module &module, horizon::FunctionSignature *fn, horizon::Block *block)
horizon::AstCallInsn::~AstCallInsn ()
virtual void horizon::AstCallInsn::Print (std::ostream &stream)
virtual std::string horizon::AstCallInsn::GetName ()
std::list< AstOperand * > & horizon::AstCallInsn::GetParameters ()
std::list< AstRegister * > & horizon::AstCallInsn::GetReturnValues ()
std::string horizon::AstCallInsn::GetJumpTargetIdentifier ()
void horizon::AstCallInsn::SetJumpTargetIdentifier (std::string x)
AstRegister * horizon::AstCallInsn::GetJumpTargetRegister ()
void horizon::AstCallInsn::SetJumpTargetRegister (AstRegister *x)
virtual void horizon::AstCallInsn::Identify (SymbolTable &symtab)
virtual void horizon::AstCallInsn::Resolve (SymbolTable &symtab)
virtual void horizon::AstCallInsn::ToCore (horizon::Module &module, horizon::FunctionSignature *fn, horizon::Block *block)
horizon::AstCastInsn::AstCastInsn ()
horizon::AstCastInsn::~AstCastInsn ()
virtual void horizon::AstCastInsn::Print (std::ostream &stream)
virtual std::string horizon::AstCastInsn::GetName ()
Types horizon::AstCastInsn::GetCastType ()
void horizon::AstCastInsn::SetCastType (Types x)
void horizon::AstCastInsn::SetTargetRegister (AstRegister *x)
AstRegister * horizon::AstCastInsn::GetTargetRegister ()
void horizon::AstCastInsn::SetTargetType (AstType *x)
AstType * horizon::AstCastInsn::GetTargetType ()
void horizon::AstCastInsn::SetSourceRegister (AstOperand *x)
AstOperand * horizon::AstCastInsn::GetSourceRegister ()
virtual void horizon::AstCastInsn::Identify (SymbolTable &symtab)
virtual void horizon::AstCastInsn::Resolve (SymbolTable &symtab)
virtual void horizon::AstCastInsn::ToCore (horizon::Module &module, horizon::FunctionSignature *fn, horizon::Block *block)
horizon::AstClass::~AstClass ()
virtual void horizon::AstClass::Print (std::ostream &stream)
virtual std::string horizon::AstClass::GetName ()
void horizon::AstClass::SetName (std::string x)
std::string horizon::AstClass::GetPackage ()
void horizon::AstClass::SetPackage (std::string x)
std::string horizon::AstClass::GetExtends ()
void horizon::AstClass::SetExtends (std::string x)
std::list< std::string > & horizon::AstClass::GetImplements ()
std::list< AstDecl * > & horizon::AstClass::GetMembers ()
virtual bool horizon::AstClass::IsClass ()
void horizon::AstClass::Identify (SymbolTable &symtab)
void horizon::AstClass::Resolve (SymbolTable &symtab)
void horizon::AstClass::ToCore (horizon::Module &module)
horizon::Symbol * horizon::AstClass::GetRef (horizon::Module &module)
horizon::AstClosure::~AstClosure ()
virtual std::string horizon::AstClosure::GetName ()
virtual void horizon::AstClosure::Print (std::ostream &stream)
std::list< AstType * > & horizon::AstClosure::GetReturnValues ()
std::list< AstParam * > & horizon::AstClosure::GetParameters ()
std::list< AstInsn * > & horizon::AstClosure::GetContent ()
virtual void horizon::AstClosure::Identify (SymbolTable &symtab)
virtual void horizon::AstClosure::Resolve (SymbolTable &symtab)
horizon::Value * horizon::AstClosure::ToCore (horizon::Module &module, horizon::FunctionSignature *fn)
horizon::AstConstExpr::~AstConstExpr ()
virtual void horizon::AstConstExpr::Print (std::ostream &stream)
virtual std::string horizon::AstConstExpr::GetName ()
virtual bool horizon::AstConstExpr::IsInteger ()
horizon::AstConstantIdentifier::~AstConstantIdentifier ()
virtual void horizon::AstConstantIdentifier::Print (std::ostream &stream)
virtual void horizon::AstConstantIdentifier::Resolve (SymbolTable &symtab)
virtual bool horizon::AstConstantIdentifier::IsInteger ()
horizon::Value * horizon::AstConstantIdentifier::ToCore (horizon::Module &module, horizon::FunctionSignature *fn)
horizon::AstConstantNull::~AstConstantNull ()
virtual void horizon::AstConstantNull::Print (std::ostream &stream)
virtual bool horizon::AstConstantNull::IsInteger ()
horizon::Value * horizon::AstConstantNull::ToCore (horizon::Module &module, horizon::FunctionSignature *fn)
horizon::AstConstantInteger::~AstConstantInteger ()
virtual void horizon::AstConstantInteger::Print (std::ostream &stream)
unsigned long horizon::AstConstantInteger::GetValue ()
virtual bool horizon::AstConstantInteger::IsInteger ()
void horizon::AstConstantInteger::SetWidth (int x)
int horizon::AstConstantInteger::GetWidth ()
horizon::Value * horizon::AstConstantInteger::ToCore (horizon::Module &module, horizon::FunctionSignature *fn)
horizon::AstConstantFloat::~AstConstantFloat ()
virtual void horizon::AstConstantFloat::Print (std::ostream &stream)
double horizon::AstConstantFloat::GetValue ()
void horizon::AstConstantFloat::SetWidth (int x)
int horizon::AstConstantFloat::GetWidth ()
horizon::Value * horizon::AstConstantFloat::ToCore (horizon::Module &module, horizon::FunctionSignature *fn)
horizon::AstConstantChar::~AstConstantChar ()
virtual void horizon::AstConstantChar::Print (std::ostream &stream)
unsigned int horizon::AstConstantChar::GetValue ()
horizon::Value * horizon::AstConstantChar::ToCore (horizon::Module &module, horizon::FunctionSignature *fn)
horizon::AstConstantString::AstConstantString (const std::string &value, Encoding enc)
horizon::AstConstantString::~AstConstantString ()
virtual void horizon::AstConstantString::Print (std::ostream &stream)
const std::string & horizon::AstConstantString::GetValue () const
horizon::Value * horizon::AstConstantString::ToCore (horizon::Module &module, horizon::FunctionSignature *fn)
horizon::AstDefaultValue::~AstDefaultValue ()
virtual void horizon::AstDefaultValue::Print (std::ostream &stream)
horizon::Value * horizon::AstDefaultValue::ToCore (horizon::Module &module, horizon::FunctionSignature *fn)
horizon::AstDecl::AstDecl ()
virtual horizon::AstDecl::~AstDecl ()
virtual void horizon::AstDecl::Identify (SymbolTable &symtab)
virtual void horizon::AstDecl::Resolve (SymbolTable &symtab)
virtual void horizon::AstDecl::ToCore (horizon::Module &module)
virtual horizon::Symbol * horizon::AstDecl::GetRef (horizon::Module &module)
virtual
horizon::ClassTypeCtor::Member horizon::AstDecl::GetClassMember (horizon::Module &module)
virtual bool horizon::AstDecl::IsDecl ()
virtual bool horizon::AstDecl::IsClass ()
virtual bool horizon::AstDecl::IsInterface ()
virtual bool horizon::AstDecl::IsVariable ()
virtual bool horizon::AstDecl::IsFunction ()
virtual bool horizon::AstDecl::IsTypedef ()
void horizon::AstDecl::SetAccess (Access a)
Access horizon::AstDecl::GetAccess () const
horizon::AstEqInsn::~AstEqInsn ()
virtual void horizon::AstEqInsn::Print (std::ostream &stream)
virtual std::string horizon::AstEqInsn::GetName ()
std::list< AstOperand * > & horizon::AstEqInsn::GetOperands ()
virtual void horizon::AstEqInsn::Identify (SymbolTable &symtab)
virtual void horizon::AstEqInsn::Resolve (SymbolTable &symtab)
virtual void horizon::AstEqInsn::ToCore (horizon::Module &module, horizon::FunctionSignature *fn, horizon::Block *block)
horizon::AstFnPtr::~AstFnPtr ()
virtual void horizon::AstFnPtr::Print (std::ostream &stream)
virtual std::string horizon::AstFnPtr::GetName ()
void horizon::AstFnPtr::SetName (std::string x)
AstRegister * horizon::AstFnPtr::GetThis () const
virtual void horizon::AstFnPtr::Identify (SymbolTable &symtab)
virtual void horizon::AstFnPtr::Resolve (SymbolTable &symtab)
horizon::Register * horizon::AstFnPtr::ToCoreReg (horizon::Module &module, horizon::FunctionSignature *fn)
horizon::Value * horizon::AstFnPtr::ToCore (horizon::Module &module, horizon::FunctionSignature *fn)
horizon::AstFunction::~AstFunction ()
virtual void horizon::AstFunction::Print (std::ostream &stream)
virtual std::string horizon::AstFunction::GetName ()
void horizon::AstFunction::SetName (std::string x)
std::list< AstType * > & horizon::AstFunction::GetReturnValues ()
std::list< AstParam * > & horizon::AstFunction::GetParameters ()
std::list< AstInsn * > & horizon::AstFunction::GetContent ()
virtual bool horizon::AstFunction::IsFunction ()
void horizon::AstFunction::Identify (SymbolTable &symtab)
void horizon::AstFunction::Resolve (SymbolTable &symtab)
void horizon::AstFunction::ToCore (horizon::Module &module)
horizon::Symbol * horizon::AstFunction::GetRef (horizon::Module &module)
virtual
horizon::ClassTypeCtor::Member horizon::AstFunction::GetClassMember (horizon::Module &module)
virtual
horizon::InterfaceTypeCtor::Member horizon::AstFunction::GetInterfaceMember (horizon::Module &module)
horizon::AstInPackage::~AstInPackage ()
virtual void horizon::AstInPackage::Print (std::ostream &stream)
virtual std::string horizon::AstInPackage::GetName ()
void horizon::AstInPackage::SetName (std::string x)
virtual horizon::AstInsn::~AstInsn ()
virtual void horizon::AstInsn::ToCore (horizon::Module &module, horizon::FunctionSignature *fn, horizon::Block *block)
virtual bool horizon::AstInsn::IsDecl ()
horizon::AstInterface::~AstInterface ()
virtual void horizon::AstInterface::Print (std::ostream &stream)
virtual std::string horizon::AstInterface::GetName ()
void horizon::AstInterface::SetName (std::string x)
std::string horizon::AstInterface::GetPackage ()
void horizon::AstInterface::SetPackage (std::string x)
std::list< AstFunction * > & horizon::AstInterface::GetMembers ()
virtual bool horizon::AstInterface::IsInterface ()
void horizon::AstInterface::Identify (SymbolTable &symtab)
void horizon::AstInterface::Resolve (SymbolTable &symtab)
void horizon::AstInterface::ToCore (horizon::Module &module)
horizon::Symbol * horizon::AstInterface::GetRef (horizon::Module &module)
horizon::AstIsA::~AstIsA ()
virtual void horizon::AstIsA::Print (std::ostream &stream)
virtual std::string horizon::AstIsA::GetName ()
AstType * horizon::AstIsA::GetType ()
void horizon::AstIsA::SetType (AstType *x)
AstRegister * horizon::AstIsA::GetTarget ()
void horizon::AstIsA::SetTarget (AstRegister *x)
AstRegister * horizon::AstIsA::GetCondition ()
void horizon::AstIsA::SetCondition (AstRegister *x)
virtual void horizon::AstIsA::Identify (SymbolTable &symtab)
virtual void horizon::AstIsA::Resolve (SymbolTable &symtab)
virtual void horizon::AstIsA::ToCore (horizon::Module &module, horizon::FunctionSignature *fn, horizon::Block *block)
horizon::AstLabel::~AstLabel ()
virtual void horizon::AstLabel::Print (std::ostream &stream)
virtual std::string horizon::AstLabel::GetName ()
void horizon::AstLabel::SetName (std::string x)
horizon::LabelInsn * horizon::AstLabel::GetRef (horizon::Block *block)
virtual void horizon::AstLabel::Identify (SymbolTable &symtab)
virtual void horizon::AstLabel::Resolve (SymbolTable &symtab)
virtual void horizon::AstLabel::ToCore (horizon::Module &module, horizon::FunctionSignature *fn, horizon::Block *block)
horizon::AstLoadInsn::~AstLoadInsn ()
virtual void horizon::AstLoadInsn::Print (std::ostream &stream)
virtual std::string horizon::AstLoadInsn::GetName ()
AstRegister * horizon::AstLoadInsn::GetTarget ()
void horizon::AstLoadInsn::SetTarget (AstRegister *x)
std::string horizon::AstLoadInsn::GetSourceIdentifier ()
void horizon::AstLoadInsn::SetSourceIdentifier (std::string x)
AstRegister * horizon::AstLoadInsn::GetSourceRegister ()
void horizon::AstLoadInsn::SetSourceRegister (AstRegister *x)
int horizon::AstLoadInsn::GetIndex ()
void horizon::AstLoadInsn::SetIndex (int x)
AstRegister * horizon::AstLoadInsn::GetIndexReg ()
void horizon::AstLoadInsn::SetIndex (AstRegister *x)
virtual void horizon::AstLoadInsn::Identify (SymbolTable &symtab)
virtual void horizon::AstLoadInsn::Resolve (SymbolTable &symtab)
virtual void horizon::AstLoadInsn::ToCore (horizon::Module &module, horizon::FunctionSignature *fn, horizon::Block *block)
horizon::AstMetadata::~AstMetadata ()
virtual void horizon::AstMetadata::Print (std::ostream &stream)
virtual std::string horizon::AstMetadata::GetName ()
std::list< std::string > & horizon::AstMetadata::GetContent ()
horizon::AstMovInsn::~AstMovInsn ()
virtual void horizon::AstMovInsn::Print (std::ostream &stream)
virtual std::string horizon::AstMovInsn::GetName ()
std::list< AstOperand * > & horizon::AstMovInsn::GetOperands ()
virtual void horizon::AstMovInsn::Identify (SymbolTable &symtab)
virtual void horizon::AstMovInsn::Resolve (SymbolTable &symtab)
virtual void horizon::AstMovInsn::ToCore (horizon::Module &module, horizon::FunctionSignature *fn, horizon::Block *block)
virtual horizon::AstNode::~AstNode ()
virtual std::string horizon::AstNode::GetName ()=0
virtual void horizon::AstNode::Print (std::ostream &stream)=0
virtual void horizon::AstNode::Identify (SymbolTable &symtab)
virtual void horizon::AstNode::Resolve (SymbolTable &symtab)
void horizon::AstNode::SetLine (int line)
int horizon::AstNode::GetLine ()
virtual bool horizon::AstNode::IsDecl ()
horizon::AstNullInsn::~AstNullInsn ()
virtual void horizon::AstNullInsn::Print (std::ostream &stream)
virtual std::string horizon::AstNullInsn::GetName ()
std::list< AstOperand * > & horizon::AstNullInsn::GetOperands ()
virtual void horizon::AstNullInsn::Identify (SymbolTable &symtab)
virtual void horizon::AstNullInsn::Resolve (SymbolTable &symtab)
virtual void horizon::AstNullInsn::ToCore (horizon::Module &module, horizon::FunctionSignature *fn, horizon::Block *block)
virtual horizon::AstOperand::~AstOperand ()
virtual horizon::Value * horizon::AstOperand::ToCore (horizon::Module &module, horizon::FunctionSignature *fn)
virtual bool horizon::AstOperand::IsDecl ()
horizon::AstParam::~AstParam ()
virtual void horizon::AstParam::Print (std::ostream &stream)
virtual std::string horizon::AstParam::GetName ()
AstType * horizon::AstParam::GetType ()
void horizon::AstParam::SetType (AstType *x)
AstRegister * horizon::AstParam::GetRegister ()
void horizon::AstParam::SetRegister (AstRegister *x)
void horizon::AstParam::Identify (SymbolTable &symtab)
void horizon::AstParam::Resolve (SymbolTable &symtab)
horizon::TupleTypeCtor::Member horizon::AstParam::ToCore (horizon::Module &module)
horizon::AstParInsn::AstParInsn (bool is_async)
horizon::AstParInsn::~AstParInsn ()
virtual void horizon::AstParInsn::Print (std::ostream &stream)
virtual std::string horizon::AstParInsn::GetName ()
void horizon::AstParInsn::SetIsAsync (bool x)
bool horizon::AstParInsn::GetIsAsync ()
void horizon::AstParInsn::SetQualifier (ParametricQualifier *qual)
void horizon::AstParInsn::AddInsn (AstCallInsn *x)
virtual void horizon::AstParInsn::Identify (SymbolTable &symtab)
virtual void horizon::AstParInsn::Resolve (SymbolTable &symtab)
virtual void horizon::AstParInsn::ToCore (horizon::Module &module, horizon::FunctionSignature *fn, horizon::Block *block)
horizon::AstRegister::~AstRegister ()
virtual void horizon::AstRegister::Print (std::ostream &stream)
virtual std::string horizon::AstRegister::GetName ()
void horizon::AstRegister::SetName (std::string x)
void horizon::AstRegister::SetIdentityDecl ()
virtual void horizon::AstRegister::Identify (SymbolTable &symtab)
virtual void horizon::AstRegister::Resolve (SymbolTable &symtab)
horizon::Register * horizon::AstRegister::ToCoreReg (horizon::Module &module, horizon::FunctionSignature *fn)
horizon::Value * horizon::AstRegister::ToCore (horizon::Module &module, horizon::FunctionSignature *fn)
horizon::AstRetInsn::~AstRetInsn ()
virtual void horizon::AstRetInsn::Print (std::ostream &stream)
std::list< AstOperand * > & horizon::AstRetInsn::GetValues ()
std::string horizon::AstRetInsn::GetName ()
virtual void horizon::AstRetInsn::Identify (SymbolTable &symtab)
virtual void horizon::AstRetInsn::Resolve (SymbolTable &symtab)
virtual void horizon::AstRetInsn::ToCore (horizon::Module &module, horizon::FunctionSignature *fn, horizon::Block *block)
horizon::AstStoreInsn::~AstStoreInsn ()
virtual void horizon::AstStoreInsn::Print (std::ostream &stream)
virtual std::string horizon::AstStoreInsn::GetName ()
AstRegister * horizon::AstStoreInsn::GetSource ()
void horizon::AstStoreInsn::SetSource (AstRegister *x)
std::string horizon::AstStoreInsn::GetTargetIdentifier ()
void horizon::AstStoreInsn::SetTargetIdentifier (std::string x)
AstRegister * horizon::AstStoreInsn::GetTargetRegister ()
void horizon::AstStoreInsn::SetTargetRegister (AstRegister *x)
int horizon::AstStoreInsn::GetIndex ()
void horizon::AstStoreInsn::SetIndex (int x)
AstRegister * horizon::AstStoreInsn::GetIndexReg ()
void horizon::AstStoreInsn::SetIndex (AstRegister *x)
virtual void horizon::AstStoreInsn::Identify (SymbolTable &symtab)
virtual void horizon::AstStoreInsn::Resolve (SymbolTable &symtab)
virtual void horizon::AstStoreInsn::ToCore (horizon::Module &module, horizon::FunctionSignature *fn, horizon::Block *block)
horizon::AstType::AstType ()
horizon::AstType::~AstType ()
virtual void horizon::AstType::Print (std::ostream &stream)
virtual std::string horizon::AstType::GetName ()
void horizon::AstType::SetName (std::string x)
Types horizon::AstType::GetType ()
void horizon::AstType::SetType (Types x)
size_t horizon::AstType::GetWidth ()
void horizon::AstType::SetWidth (size_t x)
AstNode * horizon::AstType::GetDecl ()
void horizon::AstType::SetDecl (AstNode *x)
bool horizon::AstType::GetReadOnly ()
void horizon::AstType::SetReadOnly (bool b)
bool horizon::AstType::GetSynchronised ()
void horizon::AstType::SetSynchronised (bool b)
std::map< std::string, AstType * > & horizon::AstType::GetPolymorphicBindings ()
std::map< std::string, int > & horizon::AstType::GetIntBindings ()
void horizon::AstType::Identify (SymbolTable &symtab)
void horizon::AstType::Resolve (SymbolTable &symtab)
horizon::Type * horizon::AstType::ToCore (horizon::Module &module)
horizon::AstUsingPackage::~AstUsingPackage ()
virtual void horizon::AstUsingPackage::Print (std::ostream &stream)
void horizon::AstUsingPackage::ToCore (horizon::Module &module)
virtual std::string horizon::AstUsingPackage::GetName ()
void horizon::AstUsingPackage::SetName (std::string x)
horizon::AstVariable::~AstVariable ()
virtual void horizon::AstVariable::Print (std::ostream &stream)
virtual std::string horizon::AstVariable::GetName ()
void horizon::AstVariable::SetName (std::string x)
AstType * horizon::AstVariable::GetType ()
void horizon::AstVariable::SetType (AstType *x)
AstConstExpr * horizon::AstVariable::GetValue ()
void horizon::AstVariable::SetValue (AstConstExpr *x)
virtual bool horizon::AstVariable::IsVariable ()
virtual void horizon::AstVariable::Identify (SymbolTable &symtab)
virtual void horizon::AstVariable::Resolve (SymbolTable &symtab)
virtual
horizon::ClassTypeCtor::Member horizon::AstVariable::GetClassMember (horizon::Module &module)
virtual
horizon::VariantTypeCtor::Member horizon::AstVariable::GetVariantMember (horizon::Module &module)
virtual void horizon::AstVariable::ToCore (horizon::Module &module)
virtual horizon::Symbol * horizon::AstVariable::GetRef (horizon::Module &module)
horizon::AstVariant::~AstVariant ()
virtual void horizon::AstVariant::Print (std::ostream &stream)
virtual std::string horizon::AstVariant::GetName ()
void horizon::AstVariant::SetName (std::string x)
std::string horizon::AstVariant::GetPackage ()
void horizon::AstVariant::SetPackage (std::string x)
std::list< AstVariable * > & horizon::AstVariant::GetMembers ()
virtual void horizon::AstVariant::Identify (SymbolTable &symtab)
virtual void horizon::AstVariant::Resolve (SymbolTable &symtab)
virtual void horizon::AstVariant::ToCore (horizon::Module &module)
virtual horizon::Symbol * horizon::AstVariant::GetRef (horizon::Module &module)
virtual
horizon::ClassTypeCtor::Member horizon::AstVariant::GetClassMember (horizon::Module &module)
Variables
horizon::CallInsn * horizon::AstCallInsn::m_core
int horizon::AstNode::m_line
AstRegister * horizon::AstParInsn::ParametricQualifier::reg
AstRegister * horizon::AstParInsn::ParametricQualifier::start_reg
AstRegister * horizon::AstParInsn::ParametricQualifier::end_reg
AstConstantInteger * horizon::AstParInsn::ParametricQualifier::start_const
AstConstantInteger * horizon::AstParInsn::ParametricQualifier::end_const
AstConstantInteger * horizon::AstParInsn::ParametricQualifier::step
unsigned int horizon::AstParInsn::ParametricQualifier::line
Define Documentation
#define ALIGNSTACK 330
Definition at line 93 of file tokens.h.
#define ALLOC 305
Definition at line 70 of file tokens.h.
#define API_ 321
Definition at line 84 of file tokens.h.
#define ASM 328
Definition at line 91 of file tokens.h.
#define ASTERISK 296
Definition at line 61 of file tokens.h.
#define AT 325
Definition at line 88 of file tokens.h.
#define B_MNEMONIC 268
Definition at line 39 of file tokens.h.
#define BACKTICK 317
Definition at line 50 of file tokens.h.
#define BC_MNEMONIC 269
Definition at line 40 of file tokens.h.
#define CALL 270
Definition at line 41 of file tokens.h.
#define CAST_MNEMONIC 271
Definition at line 42 of file tokens.h.
#define CHARACTER 303
Definition at line 68 of file tokens.h.
#define CLASS 285
Definition at line 55 of file tokens.h.
#define CLOSURE 323
Definition at line 86 of file tokens.h.
#define COLON 259
Definition at line 30 of file tokens.h.
#define COMMA 267
Definition at line 38 of file tokens.h.
#define CONST 299
Definition at line 64 of file tokens.h.
#define DEC_NUMBER 281
Definition at line 51 of file tokens.h.
#define DOT_DOT 313
Definition at line 77 of file tokens.h.
#define DOUBLE 291
Definition at line 58 of file tokens.h.
#define EQUALS 304
Definition at line 69 of file tokens.h.
#define EXTENDS 278
Definition at line 47 of file tokens.h.
#define FAT_COMMA 300
Definition at line 65 of file tokens.h.
#define FLOAT 276
Definition at line 45 of file tokens.h.
#define FLOAT_NUMBER 301
Definition at line 66 of file tokens.h.
#define FUNCTION 260
Definition at line 31 of file tokens.h.
#define IDENTIFIER 282
Definition at line 52 of file tokens.h.
#define IMPLEMENTS 277
Definition at line 46 of file tokens.h.
#define IN 279
Definition at line 48 of file tokens.h.
#define INTEGER 292
Definition at line 59 of file tokens.h.
#define INTERFACE 286
Definition at line 56 of file tokens.h.
#define IS_A 324
Definition at line 87 of file tokens.h.
#define LANGLE 306
Definition at line 71 of file tokens.h.
#define LBRACE 261
Definition at line 32 of file tokens.h.
#define LBRACKET 265
Definition at line 36 of file tokens.h.
#define LOAD 308
Definition at line 73 of file tokens.h.
#define LPAREN 263
Definition at line 34 of file tokens.h.
#define NEWLINE 283
Definition at line 53 of file tokens.h.
Referenced by horizon::AsmParser::Parse().
#define PAR 310
Definition at line 75 of file tokens.h.
#define PAR_ASYNC 311
Definition at line 76 of file tokens.h.
#define PERCENT 295
Definition at line 60 of file tokens.h.
#define PERIOD 284
Definition at line 54 of file tokens.h.
#define PRIVATE 319
Definition at line 82 of file tokens.h.
#define PROTECTED 320
Definition at line 83 of file tokens.h.
#define PUBLIC 318
Definition at line 81 of file tokens.h.
#define QUOTE 280
Definition at line 49 of file tokens.h.
#define RANGLE 307
Definition at line 72 of file tokens.h.
#define RBRACE 262
Definition at line 33 of file tokens.h.
#define RBRACKET 266
Definition at line 37 of file tokens.h.
#define RET 273
Definition at line 44 of file tokens.h.
#define RO 316
Definition at line 80 of file tokens.h.
#define RPAREN 264
Definition at line 35 of file tokens.h.
#define SIDEEFFECT 329
Definition at line 92 of file tokens.h.
#define SIMPLE_MNEMONIC 272
Definition at line 43 of file tokens.h.
#define STATIC 326
Definition at line 89 of file tokens.h.
#define STEP 314
Definition at line 78 of file tokens.h.
#define STORE 309
Definition at line 74 of file tokens.h.
#define STRING 302
Definition at line 67 of file tokens.h.
#define SYNC 315
Definition at line 79 of file tokens.h.
#define TOK_NULL 322
Definition at line 85 of file tokens.h.
#define TYPEDEF 331
Definition at line 94 of file tokens.h.
#define UNKNOWN 290
Definition at line 57 of file tokens.h.
#define USING 298
Definition at line 63 of file tokens.h.
#define VARIABLE 258
Definition at line 29 of file tokens.h.
#define VARIANT 297
Definition at line 62 of file tokens.h.
#define VIRTUAL 327
Definition at line 90 of file tokens.h.
Enumeration Type Documentation
enum horizon::AstAsm::ConstraintState [inherited]
Enumerator:
Output
Input
Clobber
Definition at line 37 of file Asm.h.
Function Documentation
void horizon::AstAsm::AddConstraint (std::string mode, AstRegister * r, int state) [inline, inherited]
Definition at line 61 of file Asm.h.
void horizon::AstParInsn::AddInsn (AstCallInsn * x) [inline, inherited]
Definition at line 79 of file ParInsn.h.
horizon::AstAsm::AstAsm (bool side, bool align, std::string a) [inline, inherited]
Definition at line 43 of file Asm.h.
horizon::AstCastInsn::AstCastInsn () [inline, inherited]
Definition at line 44 of file CastInsn.h.
horizon::AstConstantString::AstConstantString (const std::string & value, Encoding enc) [inline, inherited]
Todo:
Un-UTF-8 encode this.
Definition at line 195 of file ConstExpr.h.
horizon::AstDecl::AstDecl () [inline, inherited]
Creates a new AstDecl.
Definition at line 44 of file Decl.h.
horizon::AstParInsn::AstParInsn (bool is_async) [inline, inherited]
Definition at line 53 of file ParInsn.h.
horizon::AstType::AstType () [inline, inherited]
Definition at line 49 of file Type.h.
Access horizon::AstDecl::GetAccess () const [inline, inherited]
Definition at line 96 of file Decl.h.
Referenced by horizon::AstFunction::GetClassMember(), horizon::AstVariable::GetClassMember(), horizon::AstFunction::Print(), and horizon::AstVariable::Print().
Types horizon::AstCastInsn::GetCastType () [inline, inherited]
Definition at line 59 of file CastInsn.h.
virtual horizon::ClassTypeCtor::Member horizon::AstDecl::GetClassMember (horizon::Module & module) [inline, virtual, inherited]
Todo:
Push this function down to AstClass.
Reimplemented in horizon::AstFunction, horizon::AstVariable, and horizon::AstVariant.
Definition at line 66 of file Decl.h.
References Assert, horizon::Module::BuiltinClassObject(), horizon::Module::CreateInstantiation(), and horizon::ClassTypeCtor::Public.
Referenced by horizon::AstClass::GetRef().
ClassTypeCtor::Member AstFunction::GetClassMember (horizon::Module & module) [virtual, inherited]
Todo:
Push this function down to AstClass.
Reimplemented from horizon::AstDecl.
Definition at line 797 of file AstCore.cc.
References horizon::AstDecl::Api, horizon::Module::CreateInstantiation(), horizon::Symbol::Define(), horizon::Module::DefineAnonymousSymbol(), horizon::AstDecl::GetAccess(), horizon::AstNode::m_line, horizon::AstDecl::Private, horizon::AstDecl::Protected, horizon::AstDecl::Public, horizon::AstParam::ToCore(), and horizon::AstType::ToCore().
ClassTypeCtor::Member AstVariable::GetClassMember (horizon::Module & module) [virtual, inherited]
Todo:
Push this function down to AstClass.
Todo:
statics
Todo:
statics
Reimplemented from horizon::AstDecl.
Definition at line 768 of file AstCore.cc.
References horizon::AstDecl::Api, Assert, horizon::AstDecl::GetAccess(), horizon::AstNode::m_line, horizon::AstDecl::Private, horizon::AstDecl::Protected, horizon::AstDecl::Public, CoreBase::SetInputLocation(), horizon::AstType::ToCore(), and horizon::AstOperand::ToCore().
ClassTypeCtor::Member AstVariant::GetClassMember (horizon::Module & module) [virtual, inherited]
Todo:
Push this function down to AstClass.
Reimplemented from horizon::AstDecl.
Definition at line 754 of file AstCore.cc.
References Assert, horizon::Module::BuiltinClassObject(), horizon::Module::CreateInstantiation(), and horizon::ClassTypeCtor::Public.
AstRegister* horizon::AstIsA::GetCondition () [inline, inherited]
Definition at line 68 of file IsAInsn.h.
AstNode* horizon::AstBCInsn::GetConditionRegister () [inline, inherited]
Definition at line 49 of file BCInsn.h.
std::list<Constraint>& horizon::AstAsm::GetConstraints (ConstraintState state) [inline, inherited]
Definition at line 57 of file Asm.h.
std::list<AstInsn*>& horizon::AstFunction::GetContent () [inline, inherited]
Definition at line 68 of file Function.h.
std::list<AstInsn*>& horizon::AstClosure::GetContent () [inline, inherited]
Definition at line 58 of file Closure.h.
std::list<std::string>& horizon::AstMetadata::GetContent () [inline, inherited]
Definition at line 49 of file Metadata.h.
AstNode* horizon::AstType::GetDecl () [inline, inherited]
Gets the parent declaration.
Definition at line 88 of file Type.h.
std::string horizon::AstClass::GetExtends () [inline, inherited]
Definition at line 61 of file Class.h.
std::string horizon::AstBCInsn::GetFalseIdentifier () [inline, inherited]
Definition at line 63 of file BCInsn.h.
std::string horizon::AstBInsn::GetIdentifier () [inline, inherited]
Definition at line 50 of file BInsn.h.
std::list<std::string>& horizon::AstClass::GetImplements () [inline, inherited]
Definition at line 68 of file Class.h.
int horizon::AstStoreInsn::GetIndex () [inline, inherited]
Definition at line 71 of file StoreInsn.h.
int horizon::AstLoadInsn::GetIndex () [inline, inherited]
Definition at line 71 of file LoadInsn.h.
AstRegister* horizon::AstStoreInsn::GetIndexReg () [inline, inherited]
Definition at line 77 of file StoreInsn.h.
AstRegister* horizon::AstLoadInsn::GetIndexReg () [inline, inherited]
Definition at line 77 of file LoadInsn.h.
std::map<std::string, int>& horizon::AstType::GetIntBindings () [inline, inherited]
Definition at line 118 of file Type.h.
InterfaceTypeCtor::Member AstFunction::GetInterfaceMember (horizon::Module & module) [virtual, inherited]
Definition at line 832 of file AstCore.cc.
References horizon::Module::CreateInstantiation(), horizon::Symbol::Define(), horizon::Module::DefineAnonymousSymbol(), horizon::AstNode::m_line, horizon::AstParam::ToCore(), and horizon::AstType::ToCore().
Referenced by horizon::AstInterface::GetRef().
bool horizon::AstParInsn::GetIsAsync () [inline, inherited]
Definition at line 71 of file ParInsn.h.
std::string horizon::AstCallInsn::GetJumpTargetIdentifier () [inline, inherited]
Definition at line 58 of file CallInsn.h.
AstRegister* horizon::AstCallInsn::GetJumpTargetRegister () [inline, inherited]
Definition at line 65 of file CallInsn.h.
int horizon::AstNode::GetLine () [inline, inherited]
Gets the line number of where the node was scanned.
Definition at line 75 of file Node.h.
References horizon::AstNode::m_line.
std::list<AstDecl*>& horizon::AstClass::GetMembers () [inline, inherited]
Definition at line 71 of file Class.h.
std::list<AstVariable*>& horizon::AstVariant::GetMembers () [inline, inherited]
Definition at line 58 of file Variant.h.
std::list<AstFunction*>& horizon::AstInterface::GetMembers () [inline, inherited]
Definition at line 58 of file Interface.h.
virtual std::string horizon::AstParam::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 49 of file Param.h.
virtual std::string horizon::AstAlloc::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 51 of file AllocInsn.h.
virtual std::string horizon::AstClass::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 47 of file Class.h.
virtual std::string horizon::AstParInsn::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 63 of file ParInsn.h.
virtual std::string horizon::AstBInsn::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 46 of file BInsn.h.
virtual std::string horizon::AstRegister::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 46 of file Register.h.
Referenced by horizon::AstCallInsn::Identify(), and horizon::AstParam::ToCore().
virtual std::string horizon::AstEqInsn::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 45 of file EqInsn.h.
std::string horizon::AstRetInsn::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 48 of file RetInsn.h.
virtual std::string horizon::AstStoreInsn::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 46 of file StoreInsn.h.
virtual std::string horizon::AstFnPtr::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 45 of file FnPtr.h.
virtual std::string horizon::AstType::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 62 of file Type.h.
virtual std::string horizon::AstFunction::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 54 of file Function.h.
virtual std::string horizon::AstClosure::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 46 of file Closure.h.
virtual std::string horizon::AstUsingPackage::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 45 of file UsingPackage.h.
Referenced by horizon::AstUsingPackage::ToCore().
virtual std::string horizon::AstVariable::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 47 of file Variable.h.
virtual std::string horizon::AstCallInsn::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 47 of file CallInsn.h.
virtual std::string horizon::AstBCInsn::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 45 of file BCInsn.h.
virtual std::string horizon::AstVariant::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 44 of file Variant.h.
virtual std::string horizon::AstInPackage::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 45 of file InPackage.h.
virtual std::string horizon::AstInterface::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 44 of file Interface.h.
virtual std::string horizon::AstConstExpr::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 44 of file ConstExpr.h.
virtual std::string horizon::AstIsA::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 50 of file IsAInsn.h.
virtual std::string horizon::AstLabel::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 46 of file Label.h.
virtual std::string horizon::AstLoadInsn::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 46 of file LoadInsn.h.
virtual std::string horizon::AstCastInsn::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 55 of file CastInsn.h.
virtual std::string horizon::AstAsm::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 53 of file Asm.h.
virtual std::string horizon::AstMetadata::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 45 of file Metadata.h.
virtual std::string horizon::AstMovInsn::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 45 of file MovInsn.h.
virtual std::string horizon::AstNode::GetName () [pure virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implemented in horizon::AstAlloc, horizon::AstAsm, horizon::AstBCInsn, horizon::AstBInsn, horizon::AstCallInsn, horizon::AstCastInsn, horizon::AstClass, horizon::AstClosure, horizon::AstConstExpr, horizon::AstConstInsn, horizon::AstEqInsn, horizon::AstFnPtr, horizon::AstFunction, horizon::AstInPackage, horizon::AstInterface, horizon::AstIsA, horizon::AstLabel, horizon::AstLoadInsn, horizon::AstMetadata, horizon::AstMovInsn, horizon::AstNullInsn, horizon::AstParam, horizon::AstParInsn, horizon::AstRegister, horizon::AstRetInsn, horizon::AstStoreInsn, horizon::AstType, horizon::AstTypedef, horizon::AstUsingPackage, horizon::AstVariable, and horizon::AstVariant.
virtual std::string horizon::AstNullInsn::GetName () [inline, virtual, inherited]
Gets the Node's name (pure).
Deprecated:
Most nodes do not have a useful name.
Implements horizon::AstNode.
Definition at line 45 of file NullInsn.h.
std::list<AstOperand*>& horizon::AstEqInsn::GetOperands () [inline, inherited]
Definition at line 49 of file EqInsn.h.
std::list<AstOperand*>& horizon::AstMovInsn::GetOperands () [inline, inherited]
Definition at line 49 of file MovInsn.h.
std::list<AstOperand*>& horizon::AstNullInsn::GetOperands () [inline, inherited]
Definition at line 49 of file NullInsn.h.
std::string horizon::AstClass::GetPackage () [inline, inherited]
Definition at line 54 of file Class.h.
std::string horizon::AstVariant::GetPackage () [inline, inherited]
Definition at line 51 of file Variant.h.
std::string horizon::AstInterface::GetPackage () [inline, inherited]
Definition at line 51 of file Interface.h.
std::list<AstParam*>& horizon::AstFunction::GetParameters () [inline, inherited]
Definition at line 65 of file Function.h.
std::list<AstOperand*>& horizon::AstCallInsn::GetParameters () [inline, inherited]
Definition at line 51 of file CallInsn.h.
std::list<AstParam*>& horizon::AstClosure::GetParameters () [inline, inherited]
Definition at line 55 of file Closure.h.
std::map<std::string, AstType*>& horizon::AstType::GetPolymorphicBindings () [inline, inherited]
Gets the map of polymorphic bindings used in this type reference.
Definition at line 115 of file Type.h.
bool horizon::AstType::GetReadOnly () [inline, inherited]
Gets if the type is readonly
Definition at line 97 of file Type.h.
virtual horizon::Symbol* horizon::AstDecl::GetRef (horizon::Module & module) [inline, virtual, inherited]
Returns a Symbol reference to this declaration - called internally by ToCore() and is also publically accessible.
Reimplemented in horizon::AstClass, horizon::AstConstInsn, horizon::AstFunction, horizon::AstInterface, horizon::AstTypedef, horizon::AstVariable, and horizon::AstVariant.
Definition at line 61 of file Decl.h.
Referenced by horizon::AstClass::GetRef(), horizon::AstStoreInsn::ToCore(), and horizon::AstLoadInsn::ToCore().
Symbol * AstClass::GetRef (horizon::Module & module) [virtual, inherited]
Returns a Symbol reference to this declaration - called internally by ToCore() and is also publically accessible.
Reimplemented from horizon::AstDecl.
Definition at line 611 of file AstCore.cc.
References horizon::Module::BuiltinClassObject(), horizon::Module::CreateInstantiation(), horizon::Symbol::Define(), horizon::AstDecl::GetClassMember(), horizon::AstDecl::GetRef(), horizon::AstClass::GetRef(), horizon::Package::GetSymbol(), horizon::Symbol::IsUndefined(), horizon::AstNode::m_line, PARSE_ERROR, llvm::SmallVectorImpl< T >::push_back(), horizon::Module::RootPackage(), and CoreBase::SetInputLocation().
Referenced by horizon::AstClass::GetRef(), and horizon::AstClass::ToCore().
Symbol * AstFunction::GetRef (horizon::Module & module) [virtual, inherited]
Returns a Symbol reference to this declaration - called internally by ToCore() and is also publically accessible.
Reimplemented from horizon::AstDecl.
Definition at line 123 of file AstCore.cc.
References horizon::Function::CreateSignature(), horizon::Symbol::Define(), horizon::Symbol::Get(), horizon::Package::GetSymbol(), horizon::Symbol::IsUndefined(), horizon::AstNode::m_line, PARSE_ERROR, horizon::Module::RootPackage(), CoreBase::SetInputLocation(), horizon::AstParam::ToCore(), and horizon::AstType::ToCore().
Referenced by horizon::AstCallInsn::ToCore(), horizon::AstFnPtr::ToCore(), and horizon::AstFunction::ToCore().
Symbol * AstVariable::GetRef (horizon::Module & module) [virtual, inherited]
Returns a Symbol reference to this declaration - called internally by ToCore() and is also publically accessible.
Reimplemented from horizon::AstDecl.
Definition at line 686 of file AstCore.cc.
References horizon::Symbol::Define(), llvm::dyn_cast(), horizon::Package::GetSymbol(), horizon::Symbol::IsUndefined(), horizon::AstNode::m_line, PARSE_ERROR, horizon::Module::RootPackage(), CoreBase::SetInputLocation(), horizon::AstType::ToCore(), and horizon::AstOperand::ToCore().
Referenced by horizon::AstVariable::ToCore().
Symbol * AstVariant::GetRef (horizon::Module & module) [virtual, inherited]
Returns a Symbol reference to this declaration - called internally by ToCore() and is also publically accessible.
Reimplemented from horizon::AstDecl.
Definition at line 863 of file AstCore.cc.
References horizon::Symbol::Define(), horizon::Package::GetSymbol(), horizon::AstVariable::GetVariantMember(), horizon::Symbol::IsUndefined(), horizon::AstNode::m_line, PARSE_ERROR, horizon::Module::RootPackage(), and CoreBase::SetInputLocation().
Referenced by horizon::AstVariant::ToCore().
Symbol * AstInterface::GetRef (horizon::Module & module) [virtual, inherited]
Returns a Symbol reference to this declaration - called internally by ToCore() and is also publically accessible.
Reimplemented from horizon::AstDecl.
Definition at line 658 of file AstCore.cc.
References horizon::Symbol::Define(), horizon::AstFunction::GetInterfaceMember(), horizon::Package::GetSymbol(), horizon::Symbol::IsUndefined(), horizon::AstNode::m_line, PARSE_ERROR, horizon::Module::RootPackage(), and CoreBase::SetInputLocation().
Referenced by horizon::AstInterface::ToCore().
LabelInsn * AstLabel::GetRef (horizon::Block * block) [inherited]
Definition at line 531 of file AstCore.cc.
References horizon::AstNode::m_line, horizon::Block::MakeFloatingLabel(), and CoreBase::SetInputLocation().
Referenced by horizon::AstLabel::ToCore(), horizon::AstBCInsn::ToCore(), and horizon::AstBInsn::ToCore().
AstRegister* horizon::AstParam::GetRegister () [inline, inherited]
Definition at line 60 of file Param.h.
Referenced by horizon::AstClosure::ToCore().
std::list<AstType*>& horizon::AstFunction::GetReturnValues () [inline, inherited]
Definition at line 62 of file Function.h.
std::list<AstType*>& horizon::AstClosure::GetReturnValues () [inline, inherited]
Definition at line 52 of file Closure.h.
std::list<AstRegister*>& horizon::AstCallInsn::GetReturnValues () [inline, inherited]
Definition at line 54 of file CallInsn.h.
AstRegister* horizon::AstStoreInsn::GetSource () [inline, inherited]
Definition at line 50 of file StoreInsn.h.
std::string horizon::AstLoadInsn::GetSourceIdentifier () [inline, inherited]
Definition at line 57 of file LoadInsn.h.
AstRegister* horizon::AstLoadInsn::GetSourceRegister () [inline, inherited]
Definition at line 64 of file LoadInsn.h.
AstOperand* horizon::AstCastInsn::GetSourceRegister () [inline, inherited]
Definition at line 83 of file CastInsn.h.
bool horizon::AstType::GetSynchronised () [inline, inherited]
Gets if the type is synchronised
Definition at line 106 of file Type.h.
AstRegister* horizon::AstIsA::GetTarget () [inline, inherited]
Definition at line 61 of file IsAInsn.h.
AstRegister* horizon::AstLoadInsn::GetTarget () [inline, inherited]
Definition at line 50 of file LoadInsn.h.
AstRegister* horizon::AstAlloc::GetTarget () [inline, inherited]
Definition at line 62 of file AllocInsn.h.
std::string horizon::AstStoreInsn::GetTargetIdentifier () [inline, inherited]
Definition at line 57 of file StoreInsn.h.
AstRegister* horizon::AstStoreInsn::GetTargetRegister () [inline, inherited]
Definition at line 64 of file StoreInsn.h.
AstRegister* horizon::AstCastInsn::GetTargetRegister () [inline, inherited]
Definition at line 69 of file CastInsn.h.
AstType* horizon::AstCastInsn::GetTargetType () [inline, inherited]
Definition at line 76 of file CastInsn.h.
AstRegister* horizon::AstFnPtr::GetThis () const [inline, inherited]
Definition at line 51 of file FnPtr.h.
std::string horizon::AstBCInsn::GetTrueIdentifier () [inline, inherited]
Definition at line 56 of file BCInsn.h.
AstType* horizon::AstParam::GetType () [inline, inherited]
Definition at line 53 of file Param.h.
Types horizon::AstType::GetType () [inline, inherited]
Gets the type of the type.
Definition at line 70 of file Type.h.
AstType* horizon::AstVariable::GetType () [inline, inherited]
Definition at line 55 of file Variable.h.
AstType* horizon::AstAlloc::GetType () [inline, inherited]
Definition at line 55 of file AllocInsn.h.
AstType* horizon::AstIsA::GetType () [inline, inherited]
Definition at line 54 of file IsAInsn.h.
AstConstExpr* horizon::AstVariable::GetValue () [inline, inherited]
Definition at line 62 of file Variable.h.
unsigned long horizon::AstConstantInteger::GetValue () [inline, inherited]
Definition at line 112 of file ConstExpr.h.
double horizon::AstConstantFloat::GetValue () [inline, inherited]
Definition at line 146 of file ConstExpr.h.
unsigned int horizon::AstConstantChar::GetValue () [inline, inherited]
Definition at line 176 of file ConstExpr.h.
const std::string& horizon::AstConstantString::GetValue () const [inline, inherited]
Definition at line 205 of file ConstExpr.h.
std::list<AstOperand*>& horizon::AstRetInsn::GetValues () [inline, inherited]
Definition at line 44 of file RetInsn.h.
VariantTypeCtor::Member AstVariable::GetVariantMember (horizon::Module & module) [virtual, inherited]
Definition at line 761 of file AstCore.cc.
References horizon::AstNode::m_line, CoreBase::SetInputLocation(), and horizon::AstType::ToCore().
Referenced by horizon::AstVariant::GetRef().
size_t horizon::AstType::GetWidth () [inline, inherited]
Gets the bitwidth of the type.
Definition at line 79 of file Type.h.
int horizon::AstConstantInteger::GetWidth () [inline, inherited]
Definition at line 123 of file ConstExpr.h.
int horizon::AstConstantFloat::GetWidth () [inline, inherited]
Definition at line 153 of file ConstExpr.h.
virtual void horizon::AstDecl::Identify (SymbolTable & symtab) [inline, virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Reimplemented in horizon::AstClass, horizon::AstConstInsn, horizon::AstFunction, horizon::AstInterface, horizon::AstTypedef, horizon::AstVariable, and horizon::AstVariant.
Definition at line 50 of file Decl.h.
void AstCastInsn::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 222 of file AstIdentify.cc.
References horizon::AstNode::Identify(), horizon::AstType::Identify(), and horizon::AstRegister::Identify().
void AstParam::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 138 of file AstIdentify.cc.
References horizon::AstRegister::Identify(), and horizon::AstType::Identify().
Referenced by horizon::AstClosure::Identify(), and horizon::AstFunction::Identify().
void AstAsm::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 75 of file AstIdentify.cc.
void AstParInsn::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 348 of file AstIdentify.cc.
References horizon::AstCallInsn::Identify().
void AstRegister::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 168 of file AstIdentify.cc.
References SymbolTableBase< T >::Get(), SymbolTableBase< T >::Register, and SymbolTableBase< T >::Set().
Referenced by horizon::AstStoreInsn::Identify(), horizon::AstLoadInsn::Identify(), horizon::AstCastInsn::Identify(), horizon::AstIsA::Identify(), horizon::AstAlloc::Identify(), and horizon::AstParam::Identify().
void AstAlloc::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 176 of file AstIdentify.cc.
References horizon::AstRegister::Identify(), and horizon::AstType::Identify().
void AstRetInsn::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 266 of file AstIdentify.cc.
References horizon::AstNode::Identify().
void AstBInsn::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 190 of file AstIdentify.cc.
void AstEqInsn::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 240 of file AstIdentify.cc.
References horizon::AstNode::Identify().
void AstStoreInsn::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 256 of file AstIdentify.cc.
References horizon::AstRegister::Identify().
void AstVariant::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstDecl.
Definition at line 354 of file AstIdentify.cc.
References SymbolTableBase< T >::Declaration, SymbolTableBase< T >::Get(), horizon::AstNode::Identify(), horizon::AstNode::m_line, PARSE_ERROR, SymbolTableBase< T >::Set(), and SymbolTableBase< T >::Symbol.
void AstFnPtr::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 181 of file AstIdentify.cc.
void AstClass::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstDecl.
Definition at line 282 of file AstIdentify.cc.
References SymbolTableBase< T >::Declaration, SymbolTableBase< T >::Get(), horizon::AstNode::Identify(), horizon::AstNode::m_line, PARSE_ERROR, SymbolTableBase< T >::Set(), and SymbolTableBase< T >::Symbol.
void AstType::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 154 of file AstIdentify.cc.
References SymbolTableBase< T >::Declaration, SymbolTableBase< T >::Get(), horizon::AstType::Polymorphic, and SymbolTableBase< T >::Set().
Referenced by horizon::AstVariable::Identify(), horizon::AstCastInsn::Identify(), horizon::AstIsA::Identify(), horizon::AstAlloc::Identify(), horizon::AstTypedef::Identify(), horizon::AstParam::Identify(), horizon::AstClosure::Identify(), and horizon::AstFunction::Identify().
void AstFunction::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstDecl.
Definition at line 78 of file AstIdentify.cc.
References SymbolTableBase< T >::Function, SymbolTableBase< T >::Get(), horizon::AstNode::Identify(), horizon::AstParam::Identify(), horizon::AstType::Identify(), horizon::AstNode::m_line, PARSE_ERROR, SymbolTableBase< T >::Set(), and SymbolTableBase< T >::Symbol.
void AstVariable::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstDecl.
Definition at line 310 of file AstIdentify.cc.
References Assert, SymbolTableBase< T >::Declaration, horizon::AstType::Identify(), and SymbolTableBase< T >::Set().
void AstClosure::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 120 of file AstIdentify.cc.
References horizon::AstNode::Identify(), horizon::AstParam::Identify(), and horizon::AstType::Identify().
void AstInterface::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstDecl.
Definition at line 320 of file AstIdentify.cc.
References SymbolTableBase< T >::Declaration, SymbolTableBase< T >::Get(), horizon::AstNode::Identify(), horizon::AstNode::m_line, PARSE_ERROR, SymbolTableBase< T >::Set(), and SymbolTableBase< T >::Symbol.
void AstCallInsn::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 197 of file AstIdentify.cc.
References SymbolTableBase< T >::Get(), horizon::AstRegister::GetName(), horizon::AstNode::Identify(), horizon::AstNode::m_line, and PARSE_ERROR.
Referenced by horizon::AstParInsn::Identify().
void AstIsA::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 184 of file AstIdentify.cc.
References horizon::AstRegister::Identify(), and horizon::AstType::Identify().
void AstLabel::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 272 of file AstIdentify.cc.
References SymbolTableBase< T >::Get(), SymbolTableBase< T >::Label, horizon::AstNode::m_line, PARSE_ERROR, and SymbolTableBase< T >::Set().
void AstBCInsn::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 193 of file AstIdentify.cc.
References horizon::AstNode::Identify().
void AstLoadInsn::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 246 of file AstIdentify.cc.
References horizon::AstRegister::Identify().
void AstMovInsn::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 228 of file AstIdentify.cc.
References horizon::AstNode::Identify().
virtual void horizon::AstNode::Identify (SymbolTable & symtab) [inline, virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented in horizon::AstAlloc, horizon::AstAsm, horizon::AstBCInsn, horizon::AstBInsn, horizon::AstCallInsn, horizon::AstCastInsn, horizon::AstClass, horizon::AstClosure, horizon::AstConstInsn, horizon::AstDecl, horizon::AstEqInsn, horizon::AstFnPtr, horizon::AstFunction, horizon::AstInterface, horizon::AstIsA, horizon::AstLabel, horizon::AstLoadInsn, horizon::AstMovInsn, horizon::AstNullInsn, horizon::AstParam, horizon::AstParInsn, horizon::AstRegister, horizon::AstRetInsn, horizon::AstStoreInsn, horizon::AstType, horizon::AstTypedef, horizon::AstVariable, and horizon::AstVariant.
Definition at line 58 of file Node.h.
Referenced by horizon::AstVariant::Identify(), horizon::AstInterface::Identify(), horizon::AstClass::Identify(), horizon::AstRetInsn::Identify(), horizon::AstEqInsn::Identify(), horizon::AstNullInsn::Identify(), horizon::AstMovInsn::Identify(), horizon::AstCastInsn::Identify(), horizon::AstCallInsn::Identify(), horizon::AstBCInsn::Identify(), horizon::AstClosure::Identify(), and horizon::AstFunction::Identify().
void AstNullInsn::Identify (SymbolTable & symtab) [virtual, inherited]
First pass: Recursively populate symtab with functions, variables and type declarations.
Reimplemented from horizon::AstNode.
Definition at line 234 of file AstIdentify.cc.
References horizon::AstNode::Identify().
virtual bool horizon::AstDecl::IsClass () [inline, virtual, inherited]
Reimplemented in horizon::AstClass.
Definition at line 77 of file Decl.h.
Referenced by horizon::AstClass::Resolve().
virtual bool horizon::AstClass::IsClass () [inline, virtual, inherited]
Reimplemented from horizon::AstDecl.
Definition at line 75 of file Class.h.
virtual bool horizon::AstOperand::IsDecl () [inline, virtual, inherited]
Returns True if this Node is a Decl[aration], False otherwise.
See also:
AstResolve.cc
Reimplemented from horizon::AstNode.
Definition at line 51 of file Operand.h.
virtual bool horizon::AstDecl::IsDecl () [inline, virtual, inherited]
Returns True if this Node is a Decl[aration], False otherwise.
See also:
AstResolve.cc
Reimplemented from horizon::AstNode.
Definition at line 73 of file Decl.h.
virtual bool horizon::AstInsn::IsDecl () [inline, virtual, inherited]
Bug:
Should not be returning true. Would this break anything if fixed?
Reimplemented from horizon::AstNode.
Definition at line 58 of file Insn.h.
virtual bool horizon::AstNode::IsDecl () [inline, virtual, inherited]
Returns True if this Node is a Decl[aration], False otherwise.
See also:
AstResolve.cc
Reimplemented in horizon::AstDecl, horizon::AstInsn, and horizon::AstOperand.
Definition at line 81 of file Node.h.
Referenced by horizon::AstType::ToCore().
virtual bool horizon::AstDecl::IsFunction () [inline, virtual, inherited]
Reimplemented in horizon::AstFunction.
Definition at line 86 of file Decl.h.
Referenced by horizon::AstStoreInsn::Resolve(), and horizon::AstLoadInsn::Resolve().
virtual bool horizon::AstFunction::IsFunction () [inline, virtual, inherited]
Reimplemented from horizon::AstDecl.
Definition at line 72 of file Function.h.
virtual bool horizon::AstConstExpr::IsInteger () [inline, virtual, inherited]
Reimplemented in horizon::AstConstantIdentifier, horizon::AstConstantNull, and horizon::AstConstantInteger.
Definition at line 48 of file ConstExpr.h.
virtual bool horizon::AstConstantIdentifier::IsInteger () [inline, virtual, inherited]
Reimplemented from horizon::AstConstExpr.
Definition at line 69 of file ConstExpr.h.
virtual bool horizon::AstConstantNull::IsInteger () [inline, virtual, inherited]
Reimplemented from horizon::AstConstExpr.
Definition at line 93 of file ConstExpr.h.
virtual bool horizon::AstConstantInteger::IsInteger () [inline, virtual, inherited]
Reimplemented from horizon::AstConstExpr.
Definition at line 116 of file ConstExpr.h.
virtual bool horizon::AstDecl::IsInterface () [inline, virtual, inherited]
Reimplemented in horizon::AstInterface.
Definition at line 80 of file Decl.h.
Referenced by horizon::AstClass::Resolve().
virtual bool horizon::AstInterface::IsInterface () [inline, virtual, inherited]
Reimplemented from horizon::AstDecl.
Definition at line 62 of file Interface.h.
virtual bool horizon::AstDecl::IsTypedef () [inline, virtual, inherited]
Reimplemented in horizon::AstTypedef.
Definition at line 89 of file Decl.h.
virtual bool horizon::AstDecl::IsVariable () [inline, virtual, inherited]
Reimplemented in horizon::AstVariable.
Definition at line 83 of file Decl.h.
Referenced by horizon::AstStoreInsn::Resolve(), and horizon::AstLoadInsn::Resolve().
virtual bool horizon::AstVariable::IsVariable () [inline, virtual, inherited]
Reimplemented from horizon::AstDecl.
Definition at line 69 of file Variable.h.
void AstBInsn::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 84 of file AstPrint.cc.
void AstParam::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 183 of file AstPrint.cc.
void AstVariable::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 203 of file AstPrint.cc.
References horizon::AstDecl::Api, horizon::AstDecl::GetAccess(), horizon::AstDecl::Private, horizon::AstDecl::Protected, and horizon::AstDecl::Public.
void AstParInsn::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 466 of file AstPrint.cc.
References horizon::AstParInsn::ParametricQualifier::end_reg, Maybe(), horizon::AstCallInsn::Print(), horizon::AstParInsn::ParametricQualifier::reg, horizon::AstParInsn::ParametricQualifier::start_reg, and horizon::AstParInsn::ParametricQualifier::step.
void AstClass::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 243 of file AstPrint.cc.
References Maybe().
void AstRegister::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 394 of file AstPrint.cc.
void AstRetInsn::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 187 of file AstPrint.cc.
void AstEqInsn::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 505 of file AstPrint.cc.
void AstStoreInsn::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 462 of file AstPrint.cc.
References Maybe().
void AstClosure::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 321 of file AstPrint.cc.
void AstFunction::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 271 of file AstPrint.cc.
References horizon::AstDecl::Api, horizon::AstDecl::GetAccess(), horizon::AstDecl::Private, horizon::AstDecl::Protected, and horizon::AstDecl::Public.
void AstCallInsn::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 215 of file AstPrint.cc.
References Maybe().
Referenced by horizon::AstParInsn::Print().
void AstUsingPackage::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 438 of file AstPrint.cc.
void AstInPackage::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 159 of file AstPrint.cc.
void AstType::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 398 of file AstPrint.cc.
References horizon::AstType::Float, horizon::AstType::Integer, horizon::AstType::Invalid, Maybe(), horizon::AstType::Polymorphic, and horizon::AstType::Reference.
void AstVariant::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 442 of file AstPrint.cc.
void AstInterface::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 362 of file AstPrint.cc.
void AstConstExpr::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Reimplemented in horizon::AstConstantIdentifier, horizon::AstConstantNull, horizon::AstConstantInteger, horizon::AstConstantFloat, horizon::AstConstantChar, horizon::AstConstantString, and horizon::AstDefaultValue.
Definition at line 112 of file AstPrint.cc.
void AstFnPtr::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 108 of file AstPrint.cc.
void AstConstantIdentifier::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Reimplemented from horizon::AstConstExpr.
Definition at line 120 of file AstPrint.cc.
void AstIsA::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 485 of file AstPrint.cc.
void AstAlloc::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 80 of file AstPrint.cc.
void AstConstantNull::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Reimplemented from horizon::AstConstExpr.
Definition at line 124 of file AstPrint.cc.
void AstLabel::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 163 of file AstPrint.cc.
void AstConstantInteger::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Reimplemented from horizon::AstConstExpr.
Definition at line 128 of file AstPrint.cc.
void AstLoadInsn::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 458 of file AstPrint.cc.
References Maybe().
void AstBCInsn::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 88 of file AstPrint.cc.
References Maybe().
void AstCastInsn::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 92 of file AstPrint.cc.
References horizon::AstCastInsn::Down, horizon::AstCastInsn::Interface, horizon::AstCastInsn::SignExtend, horizon::AstCastInsn::Truncate, horizon::AstCastInsn::Up, and horizon::AstCastInsn::ZeroExtend.
void AstAsm::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 76 of file AstPrint.cc.
void AstConstantFloat::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Reimplemented from horizon::AstConstExpr.
Definition at line 132 of file AstPrint.cc.
void AstMetadata::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 378 of file AstPrint.cc.
void AstMovInsn::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 167 of file AstPrint.cc.
void AstConstantChar::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Todo:
Full unicode printing.
Reimplemented from horizon::AstConstExpr.
Definition at line 136 of file AstPrint.cc.
virtual void horizon::AstNode::Print (std::ostream & stream) [pure virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implemented in horizon::AstAlloc, horizon::AstAsm, horizon::AstBCInsn, horizon::AstBInsn, horizon::AstCallInsn, horizon::AstCastInsn, horizon::AstClass, horizon::AstClosure, horizon::AstConstExpr, horizon::AstConstantIdentifier, horizon::AstConstantNull, horizon::AstConstantInteger, horizon::AstConstantFloat, horizon::AstConstantChar, horizon::AstConstantString, horizon::AstDefaultValue, horizon::AstConstInsn, horizon::AstEqInsn, horizon::AstFnPtr, horizon::AstFunction, horizon::AstInPackage, horizon::AstInterface, horizon::AstIsA, horizon::AstLabel, horizon::AstLoadInsn, horizon::AstMetadata, horizon::AstMovInsn, horizon::AstNullInsn, horizon::AstParam, horizon::AstParInsn, horizon::AstRegister, horizon::AstRetInsn, horizon::AstStoreInsn, horizon::AstType, horizon::AstTypedef, horizon::AstUsingPackage, horizon::AstVariable, and horizon::AstVariant.
Referenced by main(), and Maybe().
void AstConstantString::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Todo:
Re-encode this.
Reimplemented from horizon::AstConstExpr.
Definition at line 141 of file AstPrint.cc.
References horizon::AstConstantString::Utf32, and horizon::AstConstantString::Utf8.
void AstNullInsn::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Implements horizon::AstNode.
Definition at line 489 of file AstPrint.cc.
void AstDefaultValue::Print (std::ostream & stream) [virtual, inherited]
Prints out the current node in JSON-style form.
Parameters:
stream The stream to which the output should be written.
Reimplemented from horizon::AstConstExpr.
Definition at line 155 of file AstPrint.cc.
void AstCastInsn::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 236 of file AstResolve.cc.
References horizon::AstNode::Resolve(), horizon::AstType::Resolve(), and horizon::AstRegister::Resolve().
void AstParam::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 129 of file AstResolve.cc.
References horizon::AstRegister::Resolve(), and horizon::AstType::Resolve().
Referenced by horizon::AstClosure::Resolve(), and horizon::AstFunction::Resolve().
virtual void horizon::AstDecl::Resolve (SymbolTable & symtab) [inline, virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Reimplemented in horizon::AstClass, horizon::AstConstInsn, horizon::AstFunction, horizon::AstInterface, horizon::AstTypedef, horizon::AstVariable, and horizon::AstVariant.
Definition at line 52 of file Decl.h.
void AstRegister::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 157 of file AstResolve.cc.
References SymbolTableBase< T >::Get(), PARSE_ERROR, and SymbolTableBase< T >::Register.
Referenced by horizon::AstStoreInsn::Resolve(), horizon::AstLoadInsn::Resolve(), horizon::AstCastInsn::Resolve(), horizon::AstFnPtr::Resolve(), horizon::AstCallInsn::Resolve(), horizon::AstIsA::Resolve(), horizon::AstAlloc::Resolve(), and horizon::AstParam::Resolve().
void AstAlloc::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 171 of file AstResolve.cc.
References horizon::AstRegister::Resolve(), and horizon::AstType::Resolve().
void AstAsm::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 79 of file AstResolve.cc.
void AstBInsn::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 182 of file AstResolve.cc.
References SymbolTableBase< T >::Get(), SymbolTableBase< T >::Label, and PARSE_ERROR.
void AstStoreInsn::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 286 of file AstResolve.cc.
References SymbolTableBase< T >::Declaration, SymbolTableBase< T >::Get(), horizon::AstDecl::IsFunction(), horizon::AstDecl::IsVariable(), PARSE_ERROR, horizon::AstRegister::Resolve(), and SymbolTableBase< T >::Symbol.
void AstClass::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstDecl.
Definition at line 321 of file AstResolve.cc.
References SymbolTableBase< T >::Declaration, horizon::Symbol::Get(), SymbolTableBase< T >::Get(), horizon::AstDecl::IsClass(), horizon::AstDecl::IsInterface(), horizon::AstNode::m_line, PARSE_ERROR, horizon::AstNode::Resolve(), and SymbolTableBase< T >::Symbol.
void AstVariable::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstDecl.
Definition at line 389 of file AstResolve.cc.
References Assert, and horizon::AstType::Resolve().
void AstParInsn::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 411 of file AstResolve.cc.
References horizon::AstCallInsn::Resolve().
void AstFnPtr::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 223 of file AstResolve.cc.
References SymbolTableBase< T >::Function, SymbolTableBase< T >::Get(), PARSE_ERROR, and horizon::AstRegister::Resolve().
void AstClosure::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 114 of file AstResolve.cc.
References horizon::AstNode::Resolve(), horizon::AstParam::Resolve(), and horizon::AstType::Resolve().
void AstVariant::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstDecl.
Definition at line 417 of file AstResolve.cc.
References horizon::AstNode::Resolve().
void AstInterface::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstDecl.
Definition at line 395 of file AstResolve.cc.
References horizon::AstNode::Resolve().
void AstConstantIdentifier::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 164 of file AstResolve.cc.
References SymbolTableBase< T >::Get(), PARSE_ERROR, and SymbolTableBase< T >::Symbol.
void AstType::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 138 of file AstResolve.cc.
References SymbolTableBase< T >::Declaration, SymbolTableBase< T >::Get(), PARSE_ERROR, horizon::AstType::Polymorphic, horizon::AstType::Reference, and SymbolTableBase< T >::Symbol.
Referenced by horizon::AstVariable::Resolve(), horizon::AstCastInsn::Resolve(), horizon::AstIsA::Resolve(), horizon::AstAlloc::Resolve(), horizon::AstTypedef::Resolve(), horizon::AstParam::Resolve(), horizon::AstClosure::Resolve(), and horizon::AstFunction::Resolve().
void AstCallInsn::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 204 of file AstResolve.cc.
References SymbolTableBase< T >::Function, SymbolTableBase< T >::Get(), horizon::AstRegister::Resolve(), and horizon::AstNode::Resolve().
Referenced by horizon::AstParInsn::Resolve().
void AstIsA::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 176 of file AstResolve.cc.
References horizon::AstRegister::Resolve(), and horizon::AstType::Resolve().
void AstLabel::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 318 of file AstResolve.cc.
void AstRetInsn::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 312 of file AstResolve.cc.
References horizon::AstNode::Resolve().
void AstLoadInsn::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 260 of file AstResolve.cc.
References SymbolTableBase< T >::Declaration, SymbolTableBase< T >::Get(), horizon::AstDecl::IsFunction(), horizon::AstDecl::IsVariable(), PARSE_ERROR, horizon::AstRegister::Resolve(), and SymbolTableBase< T >::Symbol.
void AstEqInsn::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 254 of file AstResolve.cc.
References horizon::AstNode::Resolve().
void AstMovInsn::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 242 of file AstResolve.cc.
References horizon::AstNode::Resolve().
void AstFunction::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstDecl.
Definition at line 93 of file AstResolve.cc.
References horizon::AstNode::Resolve(), horizon::AstParam::Resolve(), and horizon::AstType::Resolve().
virtual void horizon::AstNode::Resolve (SymbolTable & symtab) [inline, virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented in horizon::AstAlloc, horizon::AstAsm, horizon::AstBCInsn, horizon::AstBInsn, horizon::AstCallInsn, horizon::AstCastInsn, horizon::AstClass, horizon::AstClosure, horizon::AstConstantIdentifier, horizon::AstConstInsn, horizon::AstDecl, horizon::AstEqInsn, horizon::AstFnPtr, horizon::AstFunction, horizon::AstInterface, horizon::AstIsA, horizon::AstLabel, horizon::AstLoadInsn, horizon::AstMovInsn, horizon::AstNullInsn, horizon::AstParam, horizon::AstParInsn, horizon::AstRegister, horizon::AstRetInsn, horizon::AstStoreInsn, horizon::AstType, horizon::AstTypedef, horizon::AstVariable, and horizon::AstVariant.
Definition at line 62 of file Node.h.
Referenced by horizon::AstVariant::Resolve(), horizon::AstInterface::Resolve(), horizon::AstClass::Resolve(), horizon::AstRetInsn::Resolve(), horizon::AstEqInsn::Resolve(), horizon::AstNullInsn::Resolve(), horizon::AstMovInsn::Resolve(), horizon::AstCastInsn::Resolve(), horizon::AstCallInsn::Resolve(), horizon::AstBCInsn::Resolve(), horizon::AstClosure::Resolve(), and horizon::AstFunction::Resolve().
void AstBCInsn::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 189 of file AstResolve.cc.
References SymbolTableBase< T >::Get(), SymbolTableBase< T >::Label, PARSE_ERROR, and horizon::AstNode::Resolve().
void AstNullInsn::Resolve (SymbolTable & symtab) [virtual, inherited]
Second pass: Use data in symtab to resolve type references.
Reimplemented from horizon::AstNode.
Definition at line 248 of file AstResolve.cc.
References horizon::AstNode::Resolve().
void horizon::AstDecl::SetAccess (Access a) [inline, inherited]
Definition at line 93 of file Decl.h.
void horizon::AstCastInsn::SetCastType (Types x) [inline, inherited]
Definition at line 62 of file CastInsn.h.
void horizon::AstIsA::SetCondition (AstRegister * x) [inline, inherited]
Definition at line 71 of file IsAInsn.h.
void horizon::AstBCInsn::SetConditionRegister (AstNode * x) [inline, inherited]
Definition at line 52 of file BCInsn.h.
void horizon::AstType::SetDecl (AstNode * x) [inline, inherited]
Sets the parent declaration.
Definition at line 92 of file Type.h.
void horizon::AstClass::SetExtends (std::string x) [inline, inherited]
Definition at line 64 of file Class.h.
void horizon::AstBCInsn::SetFalseIdentifier (std::string x) [inline, inherited]
Definition at line 66 of file BCInsn.h.
void horizon::AstBInsn::SetIdentifier (std::string x) [inline, inherited]
Definition at line 53 of file BInsn.h.
void horizon::AstRegister::SetIdentityDecl () [inline, inherited]
Definition at line 52 of file Register.h.
void horizon::AstStoreInsn::SetIndex (int x) [inline, inherited]
Definition at line 74 of file StoreInsn.h.
void horizon::AstStoreInsn::SetIndex (AstRegister * x) [inline, inherited]
Definition at line 80 of file StoreInsn.h.
void horizon::AstLoadInsn::SetIndex (int x) [inline, inherited]
Definition at line 74 of file LoadInsn.h.
void horizon::AstLoadInsn::SetIndex (AstRegister * x) [inline, inherited]
Definition at line 80 of file LoadInsn.h.
void horizon::AstParInsn::SetIsAsync (bool x) [inline, inherited]
Definition at line 68 of file ParInsn.h.
void horizon::AstCallInsn::SetJumpTargetIdentifier (std::string x) [inline, inherited]
Definition at line 61 of file CallInsn.h.
void horizon::AstCallInsn::SetJumpTargetRegister (AstRegister * x) [inline, inherited]
Definition at line 68 of file CallInsn.h.
void horizon::AstNode::SetLine (int line) [inline, inherited]
Third pass (convert to Core representation) has a different type signature for decls and insns, so is declared there instead.
See also:
AstDecl
AstInsn Sets the line number of where the node was scanned.
Definition at line 71 of file Node.h.
References horizon::AstNode::m_line.
void horizon::AstClass::SetName (std::string x) [inline, inherited]
Definition at line 50 of file Class.h.
void horizon::AstType::SetName (std::string x) [inline, inherited]
Definition at line 65 of file Type.h.
void horizon::AstVariable::SetName (std::string x) [inline, inherited]
Definition at line 51 of file Variable.h.
void horizon::AstUsingPackage::SetName (std::string x) [inline, inherited]
Definition at line 48 of file UsingPackage.h.
void horizon::AstRegister::SetName (std::string x) [inline, inherited]
Definition at line 49 of file Register.h.
void horizon::AstInPackage::SetName (std::string x) [inline, inherited]
Definition at line 48 of file InPackage.h.
void horizon::AstFnPtr::SetName (std::string x) [inline, inherited]
Definition at line 48 of file FnPtr.h.
void horizon::AstInterface::SetName (std::string x) [inline, inherited]
Definition at line 47 of file Interface.h.
void horizon::AstFunction::SetName (std::string x) [inline, inherited]
Definition at line 58 of file Function.h.
void horizon::AstVariant::SetName (std::string x) [inline, inherited]
Definition at line 47 of file Variant.h.
void horizon::AstLabel::SetName (std::string x) [inline, inherited]
Definition at line 49 of file Label.h.
void horizon::AstVariant::SetPackage (std::string x) [inline, inherited]
Definition at line 54 of file Variant.h.
void horizon::AstClass::SetPackage (std::string x) [inline, inherited]
Definition at line 57 of file Class.h.
void horizon::AstInterface::SetPackage (std::string x) [inline, inherited]
Definition at line 54 of file Interface.h.
void horizon::AstParInsn::SetQualifier (ParametricQualifier * qual) [inline, inherited]
Definition at line 75 of file ParInsn.h.
void horizon::AstType::SetReadOnly (bool b) [inline, inherited]
Sets if the type is readonly
Definition at line 101 of file Type.h.
void horizon::AstParam::SetRegister (AstRegister * x) [inline, inherited]
Definition at line 63 of file Param.h.
void horizon::AstStoreInsn::SetSource (AstRegister * x) [inline, inherited]
Definition at line 53 of file StoreInsn.h.
void horizon::AstLoadInsn::SetSourceIdentifier (std::string x) [inline, inherited]
Definition at line 60 of file LoadInsn.h.
void horizon::AstCastInsn::SetSourceRegister (AstOperand * x) [inline, inherited]
Definition at line 80 of file CastInsn.h.
void horizon::AstLoadInsn::SetSourceRegister (AstRegister * x) [inline, inherited]
Definition at line 67 of file LoadInsn.h.
void horizon::AstType::SetSynchronised (bool b) [inline, inherited]
Sets if the type is synchronised
Definition at line 110 of file Type.h.
void horizon::AstIsA::SetTarget (AstRegister * x) [inline, inherited]
Definition at line 64 of file IsAInsn.h.
void horizon::AstLoadInsn::SetTarget (AstRegister * x) [inline, inherited]
Definition at line 53 of file LoadInsn.h.
void horizon::AstAlloc::SetTarget (AstRegister * x) [inline, inherited]
Definition at line 65 of file AllocInsn.h.
void horizon::AstStoreInsn::SetTargetIdentifier (std::string x) [inline, inherited]
Definition at line 60 of file StoreInsn.h.
void horizon::AstCastInsn::SetTargetRegister (AstRegister * x) [inline, inherited]
Definition at line 66 of file CastInsn.h.
void horizon::AstStoreInsn::SetTargetRegister (AstRegister * x) [inline, inherited]
Definition at line 67 of file StoreInsn.h.
void horizon::AstCastInsn::SetTargetType (AstType * x) [inline, inherited]
Definition at line 73 of file CastInsn.h.
void horizon::AstBCInsn::SetTrueIdentifier (std::string x) [inline, inherited]
Definition at line 59 of file BCInsn.h.
void horizon::AstIsA::SetType (AstType * x) [inline, inherited]
Definition at line 57 of file IsAInsn.h.
void horizon::AstType::SetType (Types x) [inline, inherited]
Sets the type of the type.
Definition at line 74 of file Type.h.
void horizon::AstVariable::SetType (AstType * x) [inline, inherited]
Definition at line 58 of file Variable.h.
void horizon::AstAlloc::SetType (AstType * x) [inline, inherited]
Definition at line 58 of file AllocInsn.h.
void horizon::AstParam::SetType (AstType * x) [inline, inherited]
Definition at line 56 of file Param.h.
void horizon::AstVariable::SetValue (AstConstExpr * x) [inline, inherited]
Definition at line 65 of file Variable.h.
void horizon::AstConstantInteger::SetWidth (int x) [inline, inherited]
Definition at line 120 of file ConstExpr.h.
void horizon::AstType::SetWidth (size_t x) [inline, inherited]
Sets the bitwidth of the type.
Definition at line 83 of file Type.h.
void horizon::AstConstantFloat::SetWidth (int x) [inline, inherited]
Definition at line 150 of file ConstExpr.h.
void AstAsm::ToCore (horizon::Module & module, horizon::FunctionSignature * fn, horizon::Block * block) [virtual, inherited]
Converts to a Core representation.
Parameters:
module The horizon module that should own the result.
fn The function that this instrution is part of.
block The block that this instruction is part of.
Reimplemented from horizon::AstInsn.
Definition at line 93 of file AstCore.cc.
References horizon::AsmInsn::AddConstraint(), horizon::AstNode::m_line, horizon::Block::MakeAsm(), and CoreBase::SetInputLocation().
void AstBCInsn::ToCore (horizon::Module & module, horizon::FunctionSignature * fn, horizon::Block * block) [virtual, inherited]
Converts to a Core representation.
Parameters:
module The horizon module that should own the result.
fn The function that this instrution is part of.
block The block that this instruction is part of.
Todo:
Remove this cast.
Reimplemented from horizon::AstInsn.
Definition at line 340 of file AstCore.cc.
References horizon::AstLabel::GetRef(), horizon::AstNode::m_line, horizon::Block::MakeBc(), and CoreBase::SetInputLocation().
virtual horizon::Value* horizon::AstOperand::ToCore (horizon::Module & module, horizon::FunctionSignature * fn) [inline, virtual, inherited]
Converts to a Core representation.
Reimplemented in horizon::AstClosure, horizon::AstConstantIdentifier, horizon::AstConstantNull, horizon::AstConstantInteger, horizon::AstConstantFloat, horizon::AstConstantChar, horizon::AstConstantString, horizon::AstDefaultValue, horizon::AstFnPtr, and horizon::AstRegister.
Definition at line 47 of file Operand.h.
References horizon::Module::GetConstantInt().
Referenced by horizon::AstVariable::GetClassMember(), horizon::AstVariable::GetRef(), horizon::AstConstInsn::GetRef(), horizon::AstMovInsn::ToCore(), horizon::AstRetInsn::ToCore(), horizon::AstCastInsn::ToCore(), and horizon::AstCallInsn::ToCore().
void AstIsA::ToCore (horizon::Module & module, horizon::FunctionSignature * fn, horizon::Block * block) [virtual, inherited]
Converts to a Core representation.
Parameters:
module The horizon module that should own the result.
fn The function that this instrution is part of.
block The block that this instruction is part of.
Reimplemented from horizon::AstInsn.
Definition at line 331 of file AstCore.cc.
References horizon::AstNode::m_line, horizon::Block::MakeIsA(), horizon::AstType::ToCore(), and horizon::AstRegister::ToCoreReg().
Value * AstConstantNull::ToCore (horizon::Module & module, horizon::FunctionSignature * fn) [virtual, inherited]
Converts to a Core representation.
Reimplemented from horizon::AstOperand.
Definition at line 553 of file AstCore.cc.
References horizon::Module::GetNull(), horizon::AstNode::m_line, and CoreBase::SetInputLocation().
void AstCastInsn::ToCore (horizon::Module & module, horizon::FunctionSignature * fn, horizon::Block * block) [virtual, inherited]
Converts to a Core representation.
Parameters:
module The horizon module that should own the result.
fn The function that this instrution is part of.
block The block that this instruction is part of.
Reimplemented from horizon::AstInsn.
Definition at line 411 of file AstCore.cc.
References Assert, horizon::AstCastInsn::Down, horizon::AstCastInsn::Interface, horizon::AstNode::m_line, horizon::Block::MakeDcast(), horizon::Block::MakeIcast(), horizon::Block::MakeSext(), horizon::Block::MakeTrunc(), horizon::Block::MakeUcast(), horizon::Block::MakeZext(), CoreBase::SetInputLocation(), horizon::AstCastInsn::SignExtend, horizon::AstType::ToCore(), horizon::AstOperand::ToCore(), horizon::AstRegister::ToCoreReg(), horizon::AstCastInsn::Truncate, horizon::AstCastInsn::Up, and horizon::AstCastInsn::ZeroExtend.
Value * AstRegister::ToCore (horizon::Module & module, horizon::FunctionSignature * fn) [virtual, inherited]
Converts to a Core representation.
Reimplemented from horizon::AstOperand.
Definition at line 278 of file AstCore.cc.
References horizon::AstRegister::ToCoreReg().
Referenced by horizon::AstParInsn::ToCore(), horizon::AstStoreInsn::ToCore(), horizon::AstLoadInsn::ToCore(), and horizon::AstClosure::ToCore().
void AstMovInsn::ToCore (horizon::Module & module, horizon::FunctionSignature * fn, horizon::Block * block) [virtual, inherited]
Converts to a Core representation.
Parameters:
module The horizon module that should own the result.
fn The function that this instrution is part of.
block The block that this instruction is part of.
Reimplemented from horizon::AstInsn.
Definition at line 450 of file AstCore.cc.
References horizon::AstNode::m_line, horizon::Block::MakeMov(), horizon::AstOperand::ToCore(), and horizon::AstRegister::ToCoreReg().
Value * AstDefaultValue::ToCore (horizon::Module & module, horizon::FunctionSignature * fn) [virtual, inherited]
Converts to a Core representation.
Reimplemented from horizon::AstOperand.
Definition at line 543 of file AstCore.cc.
References Fixme, horizon::Module::GetConstantInt(), horizon::AstNode::m_line, and CoreBase::SetInputLocation().
void AstNullInsn::ToCore (horizon::Module & module, horizon::FunctionSignature * fn, horizon::Block * block) [virtual, inherited]
Converts to a Core representation.
Parameters:
module The horizon module that should own the result.
fn The function that this instrution is part of.
block The block that this instruction is part of.
Reimplemented from horizon::AstInsn.
Definition at line 459 of file AstCore.cc.
References horizon::AstNode::m_line, horizon::Block::MakeNull(), and horizon::AstRegister::ToCoreReg().
Value * AstClosure::ToCore (horizon::Module & module, horizon::FunctionSignature * fn) [virtual, inherited]
Converts to a Core representation.
Reimplemented from horizon::AstOperand.
Definition at line 282 of file AstCore.cc.
References horizon::Module::CreateInstantiation(), horizon::Symbol::Define(), horizon::Module::DefineAnonymousSymbol(), horizon::AstParam::GetRegister(), horizon::AstNode::m_line, CoreBase::SetInputLocation(), horizon::AstInsn::ToCore(), horizon::AstRegister::ToCore(), horizon::AstParam::ToCore(), and horizon::AstType::ToCore().
virtual void horizon::AstDecl::ToCore (horizon::Module & module) [inline, virtual, inherited]
Convert this declaration to its Core form.
Reimplemented in horizon::AstClass, horizon::AstConstInsn, horizon::AstFunction, horizon::AstInterface, horizon::AstTypedef, horizon::AstUsingPackage, horizon::AstVariable, and horizon::AstVariant.
Definition at line 56 of file Decl.h.
void AstLabel::ToCore (horizon::Module & module, horizon::FunctionSignature * fn, horizon::Block * block) [virtual, inherited]
Converts to a Core representation.
Parameters:
module The horizon module that should own the result.
fn The function that this instrution is part of.
block The block that this instruction is part of.
Reimplemented from horizon::AstInsn.
Definition at line 539 of file AstCore.cc.
References horizon::Instruction::AppendTo(), and horizon::AstLabel::GetRef().
Value * AstFnPtr::ToCore (horizon::Module & module, horizon::FunctionSignature * fn) [virtual, inherited]
Converts to a Core representation.
Reimplemented from horizon::AstOperand.
Definition at line 322 of file AstCore.cc.
References horizon::AstFunction::GetRef(), and horizon::AstRegister::ToCoreReg().
void AstInterface::ToCore (horizon::Module & module) [virtual, inherited]
Convert this declaration to its Core form.
Reimplemented from horizon::AstDecl.
Definition at line 655 of file AstCore.cc.
References horizon::AstInterface::GetRef().
void AstLoadInsn::ToCore (horizon::Module & module, horizon::FunctionSignature * fn, horizon::Block * block) [virtual, inherited]
Converts to a Core representation.
Parameters:
module The horizon module that should own the result.
fn The function that this instrution is part of.
block The block that this instruction is part of.
Reimplemented from horizon::AstInsn.
Definition at line 480 of file AstCore.cc.
References Assert, horizon::Module::GetConstantInt(), horizon::AstDecl::GetRef(), horizon::AstNode::m_line, horizon::Block::MakeLoad(), horizon::AstRegister::ToCore(), and horizon::AstRegister::ToCoreReg().
Type * AstType::ToCore (horizon::Module & module) [inherited]
Definition at line 170 of file AstCore.cc.
References Assert, horizon::Module::BuiltinClassFloat(), horizon::Module::BuiltinClassInteger(), horizon::Module::BuiltinClassNativeint(), horizon::Module::CreateInstantiation(), horizon::Module::CreatePlaceholder(), horizon::AstType::Float, horizon::Type::GetConcreteInts(), horizon::Type::GetConcreteTypes(), horizon::AstType::Integer, horizon::AstType::Invalid, horizon::AstNode::IsDecl(), horizon::AstNode::m_line, horizon::AstType::Polymorphic, horizon::AstType::Reference, and CoreBase::SetInputLocation().
Referenced by horizon::AstFunction::GetClassMember(), horizon::AstVariable::GetClassMember(), horizon::AstFunction::GetInterfaceMember(), horizon::AstVariable::GetRef(), horizon::AstFunction::GetRef(), horizon::AstVariable::GetVariantMember(), horizon::AstCastInsn::ToCore(), horizon::AstIsA::ToCore(), horizon::AstAlloc::ToCore(), horizon::AstClosure::ToCore(), horizon::AstParam::ToCore(), and horizon::AstTypedef::ToCoreTy().
Value * AstConstantInteger::ToCore (horizon::Module & module, horizon::FunctionSignature * fn) [virtual, inherited]
Converts to a Core representation.
Reimplemented from horizon::AstOperand.
Definition at line 558 of file AstCore.cc.
References horizon::Module::BuiltinClassInteger(), horizon::Module::CreateInstantiation(), horizon::Module::GetConstantInt(), horizon::AstNode::m_line, and CoreBase::SetInputLocation().
Referenced by horizon::AstParInsn::ToCore().
void AstParInsn::ToCore (horizon::Module & module, horizon::FunctionSignature * fn, horizon::Block * block) [virtual, inherited]
Converts to a Core representation.
Parameters:
module The horizon module that should own the result.
fn The function that this instrution is part of.
block The block that this instruction is part of.
Reimplemented from horizon::AstInsn.
Definition at line 711 of file AstCore.cc.
References horizon::ParBlock::AddInsn(), Assert, llvm::dyn_cast(), horizon::AstParInsn::ParametricQualifier::end_const, horizon::AstParInsn::ParametricQualifier::end_reg, horizon::ParBlock::GetBlock(), horizon::Module::GetConstantInt(), horizon::AstParInsn::ParametricQualifier::line, horizon::AstCallInsn::m_core, horizon::Block::MakePar(), horizon::AstParInsn::ParametricQualifier::reg, CoreBase::SetInputLocation(), horizon::ParBlock::SetQualifier(), horizon::AstParInsn::ParametricQualifier::start_const, horizon::AstParInsn::ParametricQualifier::start_reg, horizon::AstParInsn::ParametricQualifier::step, horizon::AstCallInsn::ToCore(), horizon::AstConstantInteger::ToCore(), and horizon::AstRegister::ToCore().
Value * AstConstantFloat::ToCore (horizon::Module & module, horizon::FunctionSignature * fn) [virtual, inherited]
Converts to a Core representation.
Reimplemented from horizon::AstOperand.
Definition at line 567 of file AstCore.cc.
References horizon::Module::BuiltinClassFloat(), horizon::Module::CreateInstantiation(), horizon::Module::GetConstantFloat(), horizon::AstNode::m_line, and CoreBase::SetInputLocation().
virtual void horizon::AstInsn::ToCore (horizon::Module & module, horizon::FunctionSignature * fn, horizon::Block * block) [inline, virtual, inherited]
Converts to a Core representation.
Parameters:
module The horizon module that should own the result.
fn The function that this instrution is part of.
block The block that this instruction is part of.
Reimplemented in horizon::AstAlloc, horizon::AstAsm, horizon::AstBCInsn, horizon::AstBInsn, horizon::AstCallInsn, horizon::AstCastInsn, horizon::AstEqInsn, horizon::AstIsA, horizon::AstLabel, horizon::AstLoadInsn, horizon::AstMovInsn, horizon::AstNullInsn, horizon::AstParInsn, horizon::AstRetInsn, and horizon::AstStoreInsn.
Definition at line 53 of file Insn.h.
Referenced by horizon::AstClosure::ToCore(), and horizon::AstFunction::ToCore().
void AstUsingPackage::ToCore (horizon::Module & module) [virtual, inherited]
Convert this declaration to its Core form.
Reimplemented from horizon::AstDecl.
Definition at line 110 of file AstCore.cc.
References g_parser, horizon::AsmParser::GetErrors(), horizon::AstUsingPackage::GetName(), and horizon::Module::UsingPackage().
void AstVariable::ToCore (horizon::Module & module) [virtual, inherited]
Convert this declaration to its Core form.
Reimplemented from horizon::AstDecl.
Definition at line 683 of file AstCore.cc.
References horizon::AstVariable::GetRef().
void AstAlloc::ToCore (horizon::Module & module, horizon::FunctionSignature * fn, horizon::Block * block) [virtual, inherited]
Converts to a Core representation.
Parameters:
module The horizon module that should own the result.
fn The function that this instrution is part of.
block The block that this instruction is part of.
Reimplemented from horizon::AstInsn.
Definition at line 327 of file AstCore.cc.
References horizon::AstNode::m_line, horizon::Block::MakeAlloc(), horizon::AstType::ToCore(), and horizon::AstRegister::ToCoreReg().
void AstRetInsn::ToCore (horizon::Module & module, horizon::FunctionSignature * fn, horizon::Block * block) [virtual, inherited]
Converts to a Core representation.
Parameters:
module The horizon module that should own the result.
fn The function that this instrution is part of.
block The block that this instruction is part of.
Reimplemented from horizon::AstInsn.
Definition at line 440 of file AstCore.cc.
References horizon::AstNode::m_line, horizon::Block::MakeRet(), CoreBase::SetInputLocation(), and horizon::AstOperand::ToCore().
Value * AstConstantString::ToCore (horizon::Module & module, horizon::FunctionSignature * fn) [virtual, inherited]
Converts to a Core representation.
Reimplemented from horizon::AstOperand.
Definition at line 582 of file AstCore.cc.
References horizon::Module::GetConstantString(), horizon::AstNode::m_line, CoreBase::SetInputLocation(), horizon::AstConstantString::Utf32, and horizon::AstConstantString::Utf8.
void AstEqInsn::ToCore (horizon::Module & module, horizon::FunctionSignature * fn, horizon::Block * block) [virtual, inherited]
Converts to a Core representation.
Parameters:
module The horizon module that should own the result.
fn The function that this instrution is part of.
block The block that this instruction is part of.
Reimplemented from horizon::AstInsn.
Definition at line 468 of file AstCore.cc.
References horizon::AstNode::m_line, horizon::Block::MakeEq(), and horizon::AstRegister::ToCoreReg().
void AstStoreInsn::ToCore (horizon::Module & module, horizon::FunctionSignature * fn, horizon::Block * block) [virtual, inherited]
Converts to a Core representation.
Parameters:
module The horizon module that should own the result.
fn The function that this instrution is part of.
block The block that this instruction is part of.
Reimplemented from horizon::AstInsn.
Definition at line 505 of file AstCore.cc.
References Assert, horizon::Module::GetConstantInt(), horizon::AstDecl::GetRef(), horizon::AstNode::m_line, horizon::Block::MakeStore(), horizon::AstRegister::ToCore(), and horizon::AstRegister::ToCoreReg().
void AstCallInsn::ToCore (horizon::Module & module, horizon::FunctionSignature * fn, horizon::Block * block) [virtual, inherited]
Converts to a Core representation.
Parameters:
module The horizon module that should own the result.
fn The function that this instrution is part of.
block The block that this instruction is part of.
Reimplemented from horizon::AstInsn.
Definition at line 351 of file AstCore.cc.
References horizon::AstFunction::GetRef(), horizon::Module::GetSymbol(), horizon::AstCallInsn::m_core, horizon::AstNode::m_line, horizon::Block::MakeCall(), PARSE_ERROR, horizon::AstOperand::ToCore(), and horizon::AstRegister::ToCoreReg().
Referenced by horizon::AstParInsn::ToCore().
TupleTypeCtor::Member AstParam::ToCore (horizon::Module & module) [inherited]
Definition at line 166 of file AstCore.cc.
References horizon::AstRegister::GetName(), and horizon::AstType::ToCore().
Referenced by horizon::AstFunction::GetClassMember(), horizon::AstFunction::GetInterfaceMember(), horizon::AstFunction::GetRef(), and horizon::AstClosure::ToCore().
void AstBInsn::ToCore (horizon::Module & module, horizon::FunctionSignature * fn, horizon::Block * block) [virtual, inherited]
Converts to a Core representation.
Parameters:
module The horizon module that should own the result.
fn The function that this instrution is part of.
block The block that this instruction is part of.
Reimplemented from horizon::AstInsn.
Definition at line 335 of file AstCore.cc.
References horizon::AstLabel::GetRef(), horizon::AstNode::m_line, horizon::Block::MakeB(), and CoreBase::SetInputLocation().
void AstFunction::ToCore (horizon::Module & module) [virtual, inherited]
Convert this declaration to its Core form.
Reimplemented from horizon::AstDecl.
Definition at line 114 of file AstCore.cc.
References horizon::AstFunction::GetRef(), horizon::AstNode::m_line, horizon::FunctionSignature::MainBlock(), CoreBase::SetInputLocation(), and horizon::AstInsn::ToCore().
void AstVariant::ToCore (horizon::Module & module) [virtual, inherited]
Convert this declaration to its Core form.
Reimplemented from horizon::AstDecl.
Definition at line 860 of file AstCore.cc.
References horizon::AstVariant::GetRef().
Value * AstConstantIdentifier::ToCore (horizon::Module & module, horizon::FunctionSignature * fn) [virtual, inherited]
Converts to a Core representation.
Reimplemented from horizon::AstOperand.
Definition at line 549 of file AstCore.cc.
References horizon::AstConstInsn::GetRef().
Value * AstConstantChar::ToCore (horizon::Module & module, horizon::FunctionSignature * fn) [virtual, inherited]
Converts to a Core representation.
Reimplemented from horizon::AstOperand.
Definition at line 576 of file AstCore.cc.
References horizon::Module::BuiltinClassInteger(), horizon::Module::CreateInstantiation(), horizon::Module::GetConstantInt(), horizon::AstNode::m_line, and CoreBase::SetInputLocation().
void AstClass::ToCore (horizon::Module & module) [virtual, inherited]
Convert this declaration to its Core form.
Reimplemented from horizon::AstDecl.
Definition at line 608 of file AstCore.cc.
References horizon::AstClass::GetRef().
horizon::Register* horizon::AstFnPtr::ToCoreReg (horizon::Module & module, horizon::FunctionSignature * fn) [inherited]
Register * AstRegister::ToCoreReg (horizon::Module & module, horizon::FunctionSignature * fn) [inherited]
Definition at line 245 of file AstCore.cc.
References Assert, horizon::AstNode::m_line, horizon::FunctionSignature::NewRegister(), horizon::FunctionSignature::ParameterRegister(), PARSE_ERROR, CoreBase::SetInputLocation(), horizon::FunctionSignature::ThisRegister(), and horizon::AstRegister::ToCoreReg().
Referenced by horizon::AstStoreInsn::ToCore(), horizon::AstLoadInsn::ToCore(), horizon::AstEqInsn::ToCore(), horizon::AstNullInsn::ToCore(), horizon::AstMovInsn::ToCore(), horizon::AstCastInsn::ToCore(), horizon::AstCallInsn::ToCore(), horizon::AstIsA::ToCore(), horizon::AstAlloc::ToCore(), horizon::AstFnPtr::ToCore(), horizon::AstRegister::ToCore(), and horizon::AstRegister::ToCoreReg().
horizon::AstAlloc::~AstAlloc () [inline, inherited]
Definition at line 44 of file AllocInsn.h.
horizon::AstAsm::~AstAsm () [inline, inherited]
Definition at line 48 of file Asm.h.
horizon::AstBCInsn::~AstBCInsn () [inline, inherited]
Definition at line 40 of file BCInsn.h.
horizon::AstBInsn::~AstBInsn () [inline, inherited]
Definition at line 41 of file BInsn.h.
horizon::AstCallInsn::~AstCallInsn () [inline, inherited]
Definition at line 42 of file CallInsn.h.
horizon::AstCastInsn::~AstCastInsn () [inline, inherited]
Definition at line 50 of file CastInsn.h.
horizon::AstClass::~AstClass () [inline, inherited]
Definition at line 42 of file Class.h.
horizon::AstClosure::~AstClosure () [inline, inherited]
Definition at line 43 of file Closure.h.
horizon::AstConstantChar::~AstConstantChar () [inline, inherited]
Definition at line 171 of file ConstExpr.h.
horizon::AstConstantFloat::~AstConstantFloat () [inline, inherited]
Definition at line 141 of file ConstExpr.h.
horizon::AstConstantIdentifier::~AstConstantIdentifier () [inline, inherited]
Definition at line 62 of file ConstExpr.h.
horizon::AstConstantInteger::~AstConstantInteger () [inline, inherited]
Definition at line 107 of file ConstExpr.h.
horizon::AstConstantNull::~AstConstantNull () [inline, inherited]
Definition at line 88 of file ConstExpr.h.
horizon::AstConstantString::~AstConstantString () [inline, inherited]
Definition at line 200 of file ConstExpr.h.
horizon::AstConstExpr::~AstConstExpr () [inline, inherited]
Definition at line 39 of file ConstExpr.h.
virtual horizon::AstDecl::~AstDecl () [inline, virtual, inherited]
Destroys the AstDecl and all its descendants.
Definition at line 47 of file Decl.h.
horizon::AstDefaultValue::~AstDefaultValue () [inline, inherited]
Definition at line 223 of file ConstExpr.h.
horizon::AstEqInsn::~AstEqInsn () [inline, inherited]
Definition at line 40 of file EqInsn.h.
horizon::AstFnPtr::~AstFnPtr () [inline, inherited]
Definition at line 40 of file FnPtr.h.
horizon::AstFunction::~AstFunction () [inline, inherited]
Definition at line 49 of file Function.h.
horizon::AstInPackage::~AstInPackage () [inline, inherited]
Definition at line 40 of file InPackage.h.
virtual horizon::AstInsn::~AstInsn () [inline, virtual, inherited]
Destroys the AstInsn and all its descendants.
Definition at line 46 of file Insn.h.
horizon::AstInterface::~AstInterface () [inline, inherited]
Definition at line 39 of file Interface.h.
horizon::AstIsA::~AstIsA () [inline, inherited]
Definition at line 42 of file IsAInsn.h.
horizon::AstLabel::~AstLabel () [inline, inherited]
Definition at line 41 of file Label.h.
horizon::AstLoadInsn::~AstLoadInsn () [inline, inherited]
Definition at line 41 of file LoadInsn.h.
horizon::AstMetadata::~AstMetadata () [inline, inherited]
Definition at line 40 of file Metadata.h.
horizon::AstMovInsn::~AstMovInsn () [inline, inherited]
Definition at line 40 of file MovInsn.h.
virtual horizon::AstNode::~AstNode () [inline, virtual, inherited]
Destroys the AstNode and all its descendants.
Definition at line 45 of file Node.h.
horizon::AstNullInsn::~AstNullInsn () [inline, inherited]
Definition at line 40 of file NullInsn.h.
virtual horizon::AstOperand::~AstOperand () [inline, virtual, inherited]
Destroys the AstOperand and all its descendants.
Definition at line 43 of file Operand.h.
horizon::AstParam::~AstParam () [inline, inherited]
Definition at line 44 of file Param.h.
horizon::AstParInsn::~AstParInsn () [inline, inherited]
Definition at line 58 of file ParInsn.h.
horizon::AstRegister::~AstRegister () [inline, inherited]
Definition at line 41 of file Register.h.
horizon::AstRetInsn::~AstRetInsn () [inline, inherited]
Definition at line 39 of file RetInsn.h.
horizon::AstStoreInsn::~AstStoreInsn () [inline, inherited]
Definition at line 41 of file StoreInsn.h.
horizon::AstType::~AstType () [inline, inherited]
Definition at line 57 of file Type.h.
horizon::AstUsingPackage::~AstUsingPackage () [inline, inherited]
Definition at line 39 of file UsingPackage.h.
horizon::AstVariable::~AstVariable () [inline, inherited]
Definition at line 42 of file Variable.h.
horizon::AstVariant::~AstVariant () [inline, inherited]
Definition at line 39 of file Variant.h.
Variable Documentation
AstConstantInteger * horizon::AstParInsn::ParametricQualifier::end_const [inherited]
Definition at line 48 of file ParInsn.h.
Referenced by horizon::AstParInsn::ToCore().
AstRegister * horizon::AstParInsn::ParametricQualifier::end_reg [inherited]
Definition at line 47 of file ParInsn.h.
Referenced by horizon::AstParInsn::Print(), and horizon::AstParInsn::ToCore().
unsigned int horizon::AstParInsn::ParametricQualifier::line [inherited]
Definition at line 50 of file ParInsn.h.
Referenced by horizon::AstParInsn::ToCore().
horizon::CallInsn* horizon::AstCallInsn::m_core [inherited]
Definition at line 84 of file CallInsn.h.
Referenced by horizon::AstParInsn::ToCore(), and horizon::AstCallInsn::ToCore().
int horizon::AstNode::m_line [inherited]
The line where this node was scanned.
Definition at line 86 of file Node.h.
Referenced by horizon::AstFunction::GetClassMember(), horizon::AstVariable::GetClassMember(), horizon::AstFunction::GetInterfaceMember(), horizon::AstNode::GetLine(), horizon::AstVariant::GetRef(), horizon::AstVariable::GetRef(), horizon::AstInterface::GetRef(), horizon::AstClass::GetRef(), horizon::AstLabel::GetRef(), horizon::AstConstInsn::GetRef(), horizon::AstFunction::GetRef(), horizon::AstVariable::GetVariantMember(), horizon::AstVariant::Identify(), horizon::AstInterface::Identify(), horizon::AstClass::Identify(), horizon::AstLabel::Identify(), horizon::AstConstInsn::Identify(), horizon::AstCallInsn::Identify(), horizon::AstTypedef::Identify(), horizon::AstFunction::Identify(), horizon::AstClass::Resolve(), horizon::AstNode::SetLine(), horizon::AstConstantString::ToCore(), horizon::AstConstantChar::ToCore(), horizon::AstConstantFloat::ToCore(), horizon::AstConstantInteger::ToCore(), horizon::AstConstantNull::ToCore(), horizon::AstDefaultValue::ToCore(), horizon::AstStoreInsn::ToCore(), horizon::AstLoadInsn::ToCore(), horizon::AstEqInsn::ToCore(), horizon::AstNullInsn::ToCore(), horizon::AstMovInsn::ToCore(), horizon::AstRetInsn::ToCore(), horizon::AstCastInsn::ToCore(), horizon::AstCallInsn::ToCore(), horizon::AstBCInsn::ToCore(), horizon::AstBInsn::ToCore(), horizon::AstIsA::ToCore(), horizon::AstAlloc::ToCore(), horizon::AstClosure::ToCore(), horizon::AstType::ToCore(), horizon::AstFunction::ToCore(), horizon::AstAsm::ToCore(), and horizon::AstRegister::ToCoreReg().
AstRegister* horizon::AstParInsn::ParametricQualifier::reg [inherited]
Definition at line 46 of file ParInsn.h.
Referenced by horizon::AstParInsn::Print(), and horizon::AstParInsn::ToCore().
AstConstantInteger* horizon::AstParInsn::ParametricQualifier::start_const [inherited]
Definition at line 48 of file ParInsn.h.
Referenced by horizon::AstParInsn::ToCore().
AstRegister* horizon::AstParInsn::ParametricQualifier::start_reg [inherited]
Definition at line 47 of file ParInsn.h.
Referenced by horizon::AstParInsn::Print(), and horizon::AstParInsn::ToCore().
AstConstantInteger* horizon::AstParInsn::ParametricQualifier::step [inherited]
Definition at line 49 of file ParInsn.h.
Referenced by horizon::AstParInsn::Print(), and horizon::AstParInsn::ToCore().