Horizon: H
H
Classes
class h::AstNode
class h::AstExpr
class h::AstIdentifier
class h::AstType
class h::AstDecl
class h::AstGlobalVariable
class h::AstTypedef
class h::AstConst
class h::AstUsing
class h::AstClass
class h::AstClassMember
class h::AstMemberFunction
class h::AstMemberVariable
class h::AstInterface
class h::AstInterfaceMember
class h::AstVariant
class h::AstVariantMember
class h::AstFunction
class h::AstStatement
class h::AstAsmConstraint
class h::AstAsmStmt
class h::AstIfStmt
class h::AstForStmt
class h::AstWhileStmt
class h::AstReturnStmt
class h::AstVariableDecl
class h::AstAssign
class h::AstAddAssign
class h::AstSubAssign
class h::AstMulAssign
class h::AstDivAssign
class h::AstAndAssign
class h::AstOrAssign
class h::AstShrAssign
class h::AstShlAssign
class h::AstXorAssign
class h::AstParStmt
class h::AstUnaryExpr
class h::AstBinaryExpr
class h::AstBoolExpr
class h::AstIndexExpr
class h::AstMemberExpr
class h::AstNewExpr
class h::AstBlock
class h::AstTuple
class h::AstPreIncExpr
class h::AstPreDecExpr
class h::AstNegExpr
class h::AstNotExpr
class h::AstComplementExpr
class h::AstPostIncExpr
class h::AstPostDecExpr
class h::AstCastExpr
class h::AstCallExpr
class h::AstNullExpr
class h::AstInteger
class h::AstString
class h::AstFloat
class h::AstCharacter
class h::AstClosureType
class h::AstArrayType
class h::AstPolyType
class h::AstIdentifierType
class h::AstIntegerType
class h::AstBoolType
class h::AstStringType
class h::AstCharacterType
class h::AstFloatType
class h::PtNode
class h::PtDecl
class h::PtGlobalVariable
class h::PtTypedef
class h::PtConst
class h::PtUsing
class h::PtClass
class h::PtClassMember
class h::PtMemberFunction
class h::PtMemberVariable
class h::PtParameter
class h::PtInterface
class h::PtInterfaceMember
class h::PtVariant
class h::PtVariantMember
class h::PtFunction
class h::PtStatement
class h::PtAsmMode
class h::PtAsmConstraint
class h::PtAsmStmt
class h::PtIfStmt
class h::PtForStmt
class h::PtWhileStmt
class h::PtReturnStmt
class h::PtVariableDecl
class h::PtAssign
class h::PtAddAssign
class h::PtSubAssign
class h::PtMulAssign
class h::PtDivAssign
class h::PtAndAssign
class h::PtOrAssign
class h::PtShrAssign
class h::PtShlAssign
class h::PtXorAssign
class h::PtParStmt
class h::PtExpr
class h::PtNewExpr
class h::PtBlock
class h::PtTuple
class h::PtPreIncExpr
class h::PtPreDecExpr
class h::PtNegExpr
class h::PtNotExpr
class h::PtComplementExpr
class h::PtPostIncExpr
class h::PtPostDecExpr
class h::PtCastExpr
class h::PtCallExpr
class h::PtBool
class h::PtNull
class h::PtInteger
class h::PtIdentifier
class h::PtString
class h::PtFloat
class h::PtCharacter
class h::PtType
class h::PtClosureType
class h::PtArrayType
class h::PtPolyType
class h::PtIdentifierType
class h::PtList
class h::PtBindingList
Defines
#define VIRTUAL_MEMBERS
#define GENERIC_EXPR(x)
#define GENERIC_EXPR_B(x)
#define VIRTUAL_MEMBERS
#define VIRTUAL_MEMBERS_PURE
#define GENERIC_EXPR(x)
#define PT_LIST(N, TY)
Functions
virtual h::AstNode::~AstNode ()
virtual void h::AstNode::Print (std::ostream &s)=0
virtual void h::AstNode::Identify (SymbolTable &symtab, horizon::Module &module)=0
virtual void h::AstNode::Resolve (SymbolTable &symtab, horizon::Module &module)=0
virtual bool h::AstNode::Verify (horizon::Module &module)=0
void h::AstNode::Dump ()
YYLTYPE h::AstNode::GetLocationAsYYLTYPE ()
virtual AstExpr * h::AstExpr::GetTypeExpr ()=0
virtual bool h::AstExpr::IsLValue ()=0
virtual bool h::AstExpr::IsInteger ()
virtual bool h::AstExpr::IsString ()
virtual bool h::AstExpr::IsBool ()
virtual bool h::AstExpr::IsFloat ()
virtual bool h::AstExpr::IsChar ()
virtual bool h::AstExpr::IsNull ()
VIRTUAL_MEMBERS std::string & h::AstIdentifier::str ()
virtual AstExpr * h::AstIdentifier::GetTypeExpr ()
virtual bool h::AstIdentifier::IsLValue ()
virtual bool h::AstType::IsInteger ()
virtual bool h::AstType::IsString ()
virtual bool h::AstType::IsBool ()
virtual bool h::AstType::IsFloat ()
virtual bool h::AstType::IsChar ()
virtual bool h::AstType::IsRef ()
bool h::AstType::CompatibleWith (AstExpr *ty)
virtual std::string h::AstDecl::GetName ()
virtual bool h::AstDecl::IsClass ()
virtual bool h::AstDecl::IsInterface ()
virtual VIRTUAL_MEMBERS std::string h::AstTypedef::GetName ()
virtual bool h::AstTypedef::IsClass ()
virtual bool h::AstTypedef::IsInterface ()
virtual VIRTUAL_MEMBERS std::string h::AstConst::GetName ()
virtual VIRTUAL_MEMBERS std::string h::AstUsing::GetName ()
void h::AstClass::AddImplements (AstIdentifier *x)
void h::AstClass::AddMember (AstClassMember *x)
virtual VIRTUAL_MEMBERS bool h::AstClass::IsClass ()
virtual std::string h::AstClass::GetName ()
h::AstClassMember::AstClassMember (YYLTYPE loc)
void h::AstMemberFunction::AddReturnType (AstType *x)
void h::AstMemberFunction::AddParameter (std::pair< AstType *, AstIdentifier * > x)
void h::AstInterface::AddMember (AstInterfaceMember *x)
virtual VIRTUAL_MEMBERS std::string h::AstInterface::GetName ()
virtual bool h::AstInterface::IsInterface ()
void h::AstInterfaceMember::AddReturnType (AstType *x)
void h::AstInterfaceMember::AddParameter (std::pair< AstType *, AstIdentifier * > x)
void h::AstVariant::AddMember (AstVariantMember *x)
virtual VIRTUAL_MEMBERS std::string h::AstVariant::GetName ()
void h::AstFunction::AddReturnType (AstType *x)
void h::AstFunction::AddParameter (std::pair< AstType *, AstIdentifier * > x)
void h::AstFunction::AddStatement (AstStatement *x)
virtual VIRTUAL_MEMBERS std::string h::AstFunction::GetName ()
void h::AstAsmStmt::AddConstraint (AstAsmConstraint *x, int i)
void h::AstIfStmt::AddThenStatement (AstStatement *x)
void h::AstIfStmt::AddElseStatement (AstStatement *x)
void h::AstForStmt::AddStatement (AstStatement *x)
void h::AstWhileStmt::AddStatement (AstStatement *x)
void h::AstParStmt::AddStatement (AstStatement *x)
void h::AstUnaryExpr::SetNode (AstExpr *n)
virtual AstExpr * h::AstUnaryExpr::GetTypeExpr ()
virtual AstExpr * h::AstBinaryExpr::GetTypeExpr ()
virtual bool h::AstBinaryExpr::IsLValue ()
virtual VIRTUAL_MEMBERS bool h::AstBoolExpr::IsBool ()
virtual AstExpr * h::AstBoolExpr::GetTypeExpr ()
virtual bool h::AstBoolExpr::IsLValue ()
static AstBoolExpr * h::AstBoolExpr::get (bool b)
h::GENERIC_EXPR_B (LogicalOr)
h::GENERIC_EXPR_B (LogicalAnd)
h::GENERIC_EXPR (Or)
h::GENERIC_EXPR (And)
h::GENERIC_EXPR (Xor)
h::GENERIC_EXPR (Eq)
h::GENERIC_EXPR (Ne)
h::GENERIC_EXPR (Lt)
h::GENERIC_EXPR (Leq)
h::GENERIC_EXPR (Gt)
h::GENERIC_EXPR (Geq)
h::GENERIC_EXPR (Shl)
h::GENERIC_EXPR (Shr)
h::GENERIC_EXPR (Add)
h::GENERIC_EXPR (Sub)
h::GENERIC_EXPR (Mul)
h::GENERIC_EXPR (Div)
h::GENERIC_EXPR (Mod)
virtual VIRTUAL_MEMBERS AstExpr * h::AstIndexExpr::GetTypeExpr ()
virtual bool h::AstIndexExpr::IsLValue ()
virtual VIRTUAL_MEMBERS AstExpr * h::AstMemberExpr::GetTypeExpr ()
virtual bool h::AstMemberExpr::IsLValue ()
void h::AstNewExpr::AddArgument (AstExpr *x)
virtual VIRTUAL_MEMBERS AstExpr * h::AstNewExpr::GetTypeExpr ()
virtual bool h::AstNewExpr::IsLValue ()
void h::AstBlock::AddParameter (std::pair< AstType *, AstIdentifier * > x)
void h::AstBlock::AddStatement (AstStatement *x)
virtual VIRTUAL_MEMBERS AstExpr * h::AstBlock::GetTypeExpr ()
virtual bool h::AstBlock::IsLValue ()
void h::AstTuple::AddMember (AstExpr *x)
virtual VIRTUAL_MEMBERS AstExpr * h::AstTuple::GetTypeExpr ()
virtual bool h::AstTuple::IsLValue ()
virtual VIRTUAL_MEMBERS bool h::AstPreIncExpr::IsLValue ()
virtual VIRTUAL_MEMBERS bool h::AstPreDecExpr::IsLValue ()
virtual VIRTUAL_MEMBERS bool h::AstNegExpr::IsLValue ()
virtual VIRTUAL_MEMBERS bool h::AstNotExpr::IsLValue ()
virtual VIRTUAL_MEMBERS bool h::AstComplementExpr::IsLValue ()
virtual VIRTUAL_MEMBERS bool h::AstPostIncExpr::IsLValue ()
virtual VIRTUAL_MEMBERS bool h::AstPostDecExpr::IsLValue ()
virtual bool h::AstCastExpr::IsLValue ()
void h::AstCallExpr::AddArgument (AstExpr *x)
virtual VIRTUAL_MEMBERS AstExpr * h::AstCallExpr::GetTypeExpr ()
virtual bool h::AstCallExpr::IsLValue ()
virtual VIRTUAL_MEMBERS bool h::AstNullExpr::IsNull ()
virtual AstExpr * h::AstNullExpr::GetTypeExpr ()
virtual bool h::AstNullExpr::IsLValue ()
virtual VIRTUAL_MEMBERS bool h::AstInteger::IsInteger ()
virtual AstExpr * h::AstInteger::GetTypeExpr ()
virtual bool h::AstInteger::IsLValue ()
virtual VIRTUAL_MEMBERS bool h::AstString::IsString ()
virtual AstExpr * h::AstString::GetTypeExpr ()
virtual bool h::AstString::IsLValue ()
virtual VIRTUAL_MEMBERS bool h::AstFloat::IsFloat ()
virtual AstExpr * h::AstFloat::GetTypeExpr ()
virtual bool h::AstFloat::IsLValue ()
virtual VIRTUAL_MEMBERS bool h::AstCharacter::IsChar ()
virtual AstExpr * h::AstCharacter::GetTypeExpr ()
virtual bool h::AstCharacter::IsLValue ()
void h::AstClosureType::AddParameter (AstType *x)
void h::AstClosureType::AddReturnType (AstType *x)
virtual VIRTUAL_MEMBERS bool h::AstIdentifierType::IsRef ()
virtual VIRTUAL_MEMBERS bool h::AstIntegerType::IsInteger ()
virtual VIRTUAL_MEMBERS bool h::AstBoolType::IsBool ()
virtual VIRTUAL_MEMBERS bool h::AstStringType::IsString ()
virtual VIRTUAL_MEMBERS bool h::AstCharacterType::IsChar ()
virtual VIRTUAL_MEMBERS bool h::AstFloatType::IsFloat ()
virtual h::PtNode::~PtNode ()
virtual void h::PtNode::Print (std::ostream &s)=0
virtual AstNode * h::PtNode::ToAst ()=0
void h::PtNode::Dump ()
YYLTYPE h::PtNode::GetLocationAsYYLTYPE ()
h::PtAsmMode::PtAsmMode (int i, bool output, YYLTYPE loc)
h::PtForStmt::PtForStmt (PtExpr *init, PtExpr *cond, PtExpr *each, PtStatementList *stmts, YYLTYPE loc)
h::GENERIC_EXPR (LogicalOr)
h::GENERIC_EXPR (LogicalAnd)
h::GENERIC_EXPR (Prefix)
h::GENERIC_EXPR (Postfix)
h::GENERIC_EXPR (Index)
h::GENERIC_EXPR (Member)
void h::PtIdentifier::PrependWithPeriod (char *c)
void h::PtType::SetBindingList (class PtBindingList *l)
VIRTUAL_MEMBERS_PURE AstBindingList h::PtType::GetAstBindingList ()
void h::PtList::AddN (PtNode *x)
h::PT_LIST (Argument, Expr)
h::PT_LIST (ClassMember, ClassMember)
h::PT_LIST (Implements, Identifier)
h::PT_LIST (InterfaceMember, InterfaceMember)
h::PT_LIST (Param, Parameter)
h::PT_LIST (Statement, Statement)
h::PT_LIST (Tuple, Expr)
h::PT_LIST (Type, Type)
h::PT_LIST (VariantMember, VariantMember)
h::PT_LIST (AsmConstraint, AsmConstraint)
void h::PtBindingList::Add (PtType *t1, PtType *t2)
Variables
YYLTYPE h::AstNode::m_loc
std::string h::AstIdentifier::m_str
AstDecl * h::AstIdentifier::m_decl
AstBindingList h::AstType::m_binding_list
VIRTUAL_MEMBERS AstType * h::AstGlobalVariable::m_type
AstIdentifier * h::AstGlobalVariable::m_name
AstExpr * h::AstGlobalVariable::m_initialiser
AstType * h::AstTypedef::m_ty
AstIdentifier * h::AstTypedef::m_id
AstType * h::AstConst::m_ty
AstIdentifier * h::AstConst::m_name
AstExpr * h::AstConst::m_expr
AstIdentifier * h::AstUsing::m_name
AstIdentifier * h::AstClass::m_name
AstIdentifier * h::AstClass::m_extends
std::list< AstIdentifier * > h::AstClass::m_implements
std::list< AstClassMember * > h::AstClass::m_members
AstDecl * h::AstClass::m_extends_decl
std::list< AstDecl * > h::AstClass::m_implements_decls
VIRTUAL_MEMBERS Visibility h::AstMemberFunction::m_visibility
bool h::AstMemberFunction::m_static
bool h::AstMemberFunction::m_virtual
AstIdentifier * h::AstMemberFunction::m_name
std::list< AstType * > h::AstMemberFunction::m_returns
std::list< std::pair< AstType
*, AstIdentifier * > > h::AstMemberFunction::m_params
VIRTUAL_MEMBERS Visibility h::AstMemberVariable::m_visibility
bool h::AstMemberVariable::m_static
bool h::AstMemberVariable::m_virtual
AstType * h::AstMemberVariable::m_type
AstIdentifier * h::AstMemberVariable::m_name
AstExpr * h::AstMemberVariable::m_initialiser
AstIdentifier * h::AstInterface::m_name
std::list< AstInterfaceMember * > h::AstInterface::m_members
VIRTUAL_MEMBERS AstIdentifier * h::AstInterfaceMember::m_name
std::list< AstType * > h::AstInterfaceMember::m_returns
std::list< std::pair< AstType
*, AstIdentifier * > > h::AstInterfaceMember::m_params
AstIdentifier * h::AstVariant::m_name
std::list< AstVariantMember * > h::AstVariant::m_members
VIRTUAL_MEMBERS AstType * h::AstVariantMember::m_type
AstIdentifier * h::AstVariantMember::m_name
AstIdentifier * h::AstFunction::m_name
std::list< AstType * > h::AstFunction::m_returns
std::list< std::pair< AstType
*, AstIdentifier * > > h::AstFunction::m_params
std::list< AstStatement * > h::AstFunction::m_stmts
VIRTUAL_MEMBERS bool h::AstAsmConstraint::m_output
std::string h::AstAsmConstraint::m_id
AstExpr * h::AstAsmConstraint::m_expr
VIRTUAL_MEMBERS bool h::AstAsmStmt::m_sideeffect
VIRTUAL_MEMBERS bool h::AstAsmStmt::m_alignstack
std::string h::AstAsmStmt::m_str
std::list< AstAsmConstraint * > h::AstAsmStmt::m_constraints [3]
VIRTUAL_MEMBERS AstExpr * h::AstIfStmt::m_test
std::list< AstStatement * > h::AstIfStmt::m_stmts
std::list< AstStatement * > h::AstIfStmt::m_else_stmts
VIRTUAL_MEMBERS AstExpr * h::AstForStmt::m_init_expr
AstVariableDecl * h::AstForStmt::m_init_decl
AstExpr * h::AstForStmt::m_cond
AstExpr * h::AstForStmt::m_each
std::list< AstStatement * > h::AstForStmt::m_stmts
VIRTUAL_MEMBERS bool h::AstWhileStmt::m_tail_cond
AstExpr * h::AstWhileStmt::m_expr
std::list< AstStatement * > h::AstWhileStmt::m_stmts
VIRTUAL_MEMBERS AstExpr * h::AstReturnStmt::m_expr
VIRTUAL_MEMBERS AstType * h::AstVariableDecl::m_type
AstIdentifier * h::AstVariableDecl::m_name
AstExpr * h::AstVariableDecl::m_initialiser
VIRTUAL_MEMBERS AstExpr * h::AstAssign::m_lhs
VIRTUAL_MEMBERS AstExpr * h::AstAssign::m_rhs
VIRTUAL_MEMBERS AstExpr * h::AstAddAssign::m_lhs
VIRTUAL_MEMBERS AstExpr * h::AstAddAssign::m_rhs
VIRTUAL_MEMBERS AstExpr * h::AstSubAssign::m_lhs
VIRTUAL_MEMBERS AstExpr * h::AstSubAssign::m_rhs
VIRTUAL_MEMBERS AstExpr * h::AstMulAssign::m_lhs
VIRTUAL_MEMBERS AstExpr * h::AstMulAssign::m_rhs
VIRTUAL_MEMBERS AstExpr * h::AstDivAssign::m_lhs
VIRTUAL_MEMBERS AstExpr * h::AstDivAssign::m_rhs
VIRTUAL_MEMBERS AstExpr * h::AstAndAssign::m_lhs
VIRTUAL_MEMBERS AstExpr * h::AstAndAssign::m_rhs
VIRTUAL_MEMBERS AstExpr * h::AstOrAssign::m_lhs
VIRTUAL_MEMBERS AstExpr * h::AstOrAssign::m_rhs
VIRTUAL_MEMBERS AstExpr * h::AstShrAssign::m_lhs
VIRTUAL_MEMBERS AstExpr * h::AstShrAssign::m_rhs
VIRTUAL_MEMBERS AstExpr * h::AstShlAssign::m_lhs
VIRTUAL_MEMBERS AstExpr * h::AstShlAssign::m_rhs
VIRTUAL_MEMBERS AstExpr * h::AstXorAssign::m_lhs
VIRTUAL_MEMBERS AstExpr * h::AstXorAssign::m_rhs
VIRTUAL_MEMBERS std::list
< AstStatement * > h::AstParStmt::m_calls
bool h::AstParStmt::m_is_async
AstExpr * h::AstUnaryExpr::m_n
AstExpr * h::AstBinaryExpr::m_n1
AstExpr * h::AstBinaryExpr::m_n2
static AstBoolExpr h::AstBoolExpr::s_true
static AstBoolExpr h::AstBoolExpr::s_false
bool h::AstBoolExpr::m_b
AstIdentifier * h::AstNewExpr::m_id
std::list< AstExpr * > h::AstNewExpr::m_args
std::list< std::pair< AstType
*, AstIdentifier * > > h::AstBlock::m_params
std::list< AstStatement * > h::AstBlock::m_stmts
std::list< AstExpr * > h::AstTuple::m_members
VIRTUAL_MEMBERS AstType * h::AstCastExpr::m_ty
std::list< AstExpr * > h::AstCallExpr::m_args
AstBlock * h::AstCallExpr::m_block
uint64_t h::AstInteger::m_n
std::string h::AstString::m_str
double h::AstFloat::m_d
char * h::AstCharacter::m_str
VIRTUAL_MEMBERS std::list
< AstType * > h::AstClosureType::m_params
VIRTUAL_MEMBERS std::list
< AstType * > h::AstClosureType::m_returns
VIRTUAL_MEMBERS AstType * h::AstArrayType::m_ty
VIRTUAL_MEMBERS AstType * h::AstArrayType::m_ty2
AstExpr * h::AstArrayType::m_length
VIRTUAL_MEMBERS AstIdentifier * h::AstPolyType::m_name
AstDecl * h::AstPolyType::m_decl
AstIdentifier * h::AstIdentifierType::m_name
AstDecl * h::AstIdentifierType::m_decl
bool h::AstIntegerType::m_signed
int h::AstIntegerType::m_width
bool h::AstFloatType::m_double
YYLTYPE h::PtNode::m_loc
VIRTUAL_MEMBERS PtType * h::PtGlobalVariable::m_type
PtIdentifier * h::PtGlobalVariable::m_name
PtExpr * h::PtGlobalVariable::m_initialiser
VIRTUAL_MEMBERS PtType * h::PtTypedef::m_ty
PtIdentifier * h::PtTypedef::m_id
VIRTUAL_MEMBERS PtType * h::PtConst::m_ty
PtIdentifier * h::PtConst::m_name
PtExpr * h::PtConst::m_expr
VIRTUAL_MEMBERS PtIdentifier * h::PtUsing::m_name
VIRTUAL_MEMBERS PtIdentifier * h::PtClass::m_name
VIRTUAL_MEMBERS PtIdentifier * h::PtClass::m_extends
PtImplementsList * h::PtClass::m_implements
PtClassMemberList * h::PtClass::m_members
VIRTUAL_MEMBERS unsigned long h::PtMemberFunction::m_visibility
bool h::PtMemberFunction::m_static
bool h::PtMemberFunction::m_virtual
PtTypeList * h::PtMemberFunction::m_returns
PtIdentifier * h::PtMemberFunction::m_name
PtParamList * h::PtMemberFunction::m_params
VIRTUAL_MEMBERS int h::PtMemberVariable::m_visibility
bool h::PtMemberVariable::m_static
bool h::PtMemberVariable::m_virtual
PtType * h::PtMemberVariable::m_type
PtIdentifier * h::PtMemberVariable::m_name
PtExpr * h::PtMemberVariable::m_initialiser
VIRTUAL_MEMBERS PtType * h::PtParameter::m_type
PtIdentifier * h::PtParameter::m_name
VIRTUAL_MEMBERS PtIdentifier * h::PtInterface::m_name
PtInterfaceMemberList * h::PtInterface::m_members
VIRTUAL_MEMBERS PtTypeList * h::PtInterfaceMember::m_returns
PtIdentifier * h::PtInterfaceMember::m_name
PtParamList * h::PtInterfaceMember::m_params
VIRTUAL_MEMBERS PtIdentifier * h::PtVariant::m_name
PtVariantMemberList * h::PtVariant::m_members
VIRTUAL_MEMBERS PtType * h::PtVariantMember::m_type
PtIdentifier * h::PtVariantMember::m_name
VIRTUAL_MEMBERS PtTypeList * h::PtFunction::m_returns
PtIdentifier * h::PtFunction::m_name
PtParamList * h::PtFunction::m_params
PtStatementList * h::PtFunction::m_stmts
VIRTUAL_MEMBERS std::string h::PtAsmMode::m_str
bool h::PtAsmMode::m_output
VIRTUAL_MEMBERS PtAsmMode * h::PtAsmConstraint::m_mode
PtExpr * h::PtAsmConstraint::m_expr
VIRTUAL_MEMBERS std::string h::PtAsmStmt::m_str
PtAsmConstraintList * h::PtAsmStmt::m_outputs
PtAsmConstraintList * h::PtAsmStmt::m_inputs
PtAsmConstraintList * h::PtAsmStmt::m_clobbers
VIRTUAL_MEMBERS PtExpr * h::PtIfStmt::m_test
PtStatementList * h::PtIfStmt::m_stmts
PtStatementList * h::PtIfStmt::m_else_stmts
VIRTUAL_MEMBERS PtExpr * h::PtForStmt::m_init_expr
PtVariableDecl * h::PtForStmt::m_init_decl
PtExpr * h::PtForStmt::m_cond
PtExpr * h::PtForStmt::m_each
PtStatementList * h::PtForStmt::m_stmts
VIRTUAL_MEMBERS bool h::PtWhileStmt::m_tail_cond
PtExpr * h::PtWhileStmt::m_expr
PtStatementList * h::PtWhileStmt::m_stmts
VIRTUAL_MEMBERS PtExpr * h::PtReturnStmt::m_expr
VIRTUAL_MEMBERS PtType * h::PtVariableDecl::m_type
PtIdentifier * h::PtVariableDecl::m_name
PtExpr * h::PtVariableDecl::m_initialiser
VIRTUAL_MEMBERS PtExpr * h::PtAssign::m_lhs
VIRTUAL_MEMBERS PtExpr * h::PtAssign::m_rhs
VIRTUAL_MEMBERS PtExpr * h::PtAddAssign::m_lhs
VIRTUAL_MEMBERS PtExpr * h::PtAddAssign::m_rhs
VIRTUAL_MEMBERS PtExpr * h::PtSubAssign::m_lhs
VIRTUAL_MEMBERS PtExpr * h::PtSubAssign::m_rhs
VIRTUAL_MEMBERS PtExpr * h::PtMulAssign::m_lhs
VIRTUAL_MEMBERS PtExpr * h::PtMulAssign::m_rhs
VIRTUAL_MEMBERS PtExpr * h::PtDivAssign::m_lhs
VIRTUAL_MEMBERS PtExpr * h::PtDivAssign::m_rhs
VIRTUAL_MEMBERS PtExpr * h::PtAndAssign::m_lhs
VIRTUAL_MEMBERS PtExpr * h::PtAndAssign::m_rhs
VIRTUAL_MEMBERS PtExpr * h::PtOrAssign::m_lhs
VIRTUAL_MEMBERS PtExpr * h::PtOrAssign::m_rhs
VIRTUAL_MEMBERS PtExpr * h::PtShrAssign::m_lhs
VIRTUAL_MEMBERS PtExpr * h::PtShrAssign::m_rhs
VIRTUAL_MEMBERS PtExpr * h::PtShlAssign::m_lhs
VIRTUAL_MEMBERS PtExpr * h::PtShlAssign::m_rhs
VIRTUAL_MEMBERS PtExpr * h::PtXorAssign::m_lhs
VIRTUAL_MEMBERS PtExpr * h::PtXorAssign::m_rhs
VIRTUAL_MEMBERS PtStatementList * h::PtParStmt::m_calls
bool h::PtParStmt::m_is_async
VIRTUAL_MEMBERS_PURE PtExpr * h::PtExpr::m_n1
VIRTUAL_MEMBERS_PURE PtExpr * h::PtExpr::m_n2
VIRTUAL_MEMBERS PtIdentifier * h::PtNewExpr::m_id
PtArgumentList * h::PtNewExpr::m_args
VIRTUAL_MEMBERS PtParamList * h::PtBlock::m_params
PtStatementList * h::PtBlock::m_stmts
VIRTUAL_MEMBERS PtTupleList * h::PtTuple::m_tl
VIRTUAL_MEMBERS PtType * h::PtCastExpr::m_ty
VIRTUAL_MEMBERS PtArgumentList * h::PtCallExpr::m_args
PtBlock * h::PtCallExpr::m_block
VIRTUAL_MEMBERS bool h::PtBool::m_b
VIRTUAL_MEMBERS uint64_t h::PtInteger::m_n
VIRTUAL_MEMBERS std::string h::PtIdentifier::m_str
VIRTUAL_MEMBERS std::string h::PtString::m_str
VIRTUAL_MEMBERS double h::PtFloat::m_d
VIRTUAL_MEMBERS char * h::PtCharacter::m_str
class PtBindingList * h::PtType::m_binding_list
VIRTUAL_MEMBERS class PtTypeList * h::PtClosureType::m_params
VIRTUAL_MEMBERS class PtTypeList * h::PtClosureType::m_returns
VIRTUAL_MEMBERS PtType * h::PtArrayType::m_ty
VIRTUAL_MEMBERS PtType * h::PtArrayType::m_ty2
PtExpr * h::PtArrayType::m_length
VIRTUAL_MEMBERS PtIdentifier * h::PtPolyType::m_name
VIRTUAL_MEMBERS PtIdentifier * h::PtIdentifierType::m_name
VIRTUAL_MEMBERS std::list
< PtNode * > h::PtList::m_list
VIRTUAL_MEMBERS std::list
< std::pair< PtType *, PtType * > > h::PtBindingList::m_list
Define Documentation
#define GENERIC_EXPR (x)
Value:
class Ast##x##Expr : public AstBinaryExpr {     \
        public:                                 \
        Ast##x##Expr(AstExpr *n1, AstExpr *n2, YYLTYPE loc) :   \
        AstBinaryExpr(n1, n2, loc) {                                    \
        }                                                       \
        VIRTUAL_MEMBERS                                         \
        }
Definition at line 681 of file astNodes.h.
#define GENERIC_EXPR (x)
Value:
class Pt##x##Expr : public PtExpr {     \
        public:                                 \
        Pt##x##Expr(PtExpr *n1, PtExpr *n2, YYLTYPE loc) :      \
        PtExpr(n1, n2, loc) {                                   \
        }                                                       \
        VIRTUAL_MEMBERS                                         \
        }
Definition at line 481 of file ptNodes.h.
#define GENERIC_EXPR_B (x)
Value:
class Ast##x##Expr : public AstBinaryExpr {     \
        public:                                 \
        Ast##x##Expr(AstExpr *n1, AstExpr *n2, YYLTYPE loc) :   \
        AstBinaryExpr(n1, n2, loc) {                                    \
        }                                                       \
        VIRTUAL_MEMBERS                                         \
        virtual AstExpr *GetTypeExpr() {                        \
                return AstBoolExpr::get(true);                  \
        }                                                       \
        }
Definition at line 689 of file astNodes.h.
#define PT_LIST (N, TY)
Value:
class Pt##N##List : public PtList {     \
public:                                         \
Pt##N##List(Pt##TY *e) :                                \
PtList((PtNode*)e) {                            \
}                                               \
void Add(Pt##TY *e) {                           \
        AddN((PtNode*)e);                       \
}                                               \
        }
Definition at line 783 of file ptNodes.h.
#define VIRTUAL_MEMBERS
Value:
virtual void Print(std::ostream &s);    \
        virtual AstNode *ToAst();
Definition at line 42 of file ptNodes.h.
#define VIRTUAL_MEMBERS
Value:
virtual void Print(std::ostream &s);    \
        virtual void Identify(SymbolTable &symtab, horizon::Module &module); \
        virtual void Resolve(SymbolTable &symtab, horizon::Module &module); \
        virtual bool Verify(horizon::Module &module);
Definition at line 58 of file astNodes.h.
#define VIRTUAL_MEMBERS_PURE
Value:
virtual void Print(std::ostream &s) =0; \
        virtual AstNode *ToAst() =0;
Definition at line 45 of file ptNodes.h.
Function Documentation
void h::PtBindingList::Add (PtType * t1, PtType * t2) [inline, inherited]
Definition at line 811 of file ptNodes.h.
References h::PtBindingList::m_list.
Referenced by h::PtBindingList::PtBindingList().
void h::AstNewExpr::AddArgument (AstExpr * x) [inline, inherited]
Definition at line 756 of file astNodes.h.
References h::AstNewExpr::m_args.
void h::AstCallExpr::AddArgument (AstExpr * x) [inline, inherited]
Definition at line 921 of file astNodes.h.
References h::AstCallExpr::m_args.
void h::AstAsmStmt::AddConstraint (AstAsmConstraint * x, int i) [inline, inherited]
Definition at line 410 of file astNodes.h.
References h::AstAsmStmt::m_constraints.
void h::AstIfStmt::AddElseStatement (AstStatement * x) [inline, inherited]
Definition at line 429 of file astNodes.h.
References h::AstIfStmt::m_else_stmts.
void h::AstClass::AddImplements (AstIdentifier * x) [inline, inherited]
Definition at line 222 of file astNodes.h.
References h::AstClass::m_implements.
void h::AstClass::AddMember (AstClassMember * x) [inline, inherited]
Definition at line 225 of file astNodes.h.
References h::AstClass::m_members.
void h::AstInterface::AddMember (AstInterfaceMember * x) [inline, inherited]
Definition at line 299 of file astNodes.h.
References h::AstInterface::m_members.
void h::AstVariant::AddMember (AstVariantMember * x) [inline, inherited]
Definition at line 336 of file astNodes.h.
References h::AstVariant::m_members.
void h::AstTuple::AddMember (AstExpr * x) [inline, inherited]
Definition at line 803 of file astNodes.h.
References h::AstTuple::m_members.
void h::PtList::AddN (PtNode * x) [inline, inherited]
Definition at line 774 of file ptNodes.h.
References h::PtList::m_list.
Referenced by h::PtList::PtList().
void h::AstMemberFunction::AddParameter (std::pair< AstType *, AstIdentifier * > x) [inline, inherited]
Definition at line 265 of file astNodes.h.
References h::AstMemberFunction::m_params.
void h::AstBlock::AddParameter (std::pair< AstType *, AstIdentifier * > x) [inline, inherited]
Definition at line 778 of file astNodes.h.
References h::AstBlock::m_params.
void h::AstInterfaceMember::AddParameter (std::pair< AstType *, AstIdentifier * > x) [inline, inherited]
Definition at line 320 of file astNodes.h.
References h::AstInterfaceMember::m_params.
void h::AstFunction::AddParameter (std::pair< AstType *, AstIdentifier * > x) [inline, inherited]
Definition at line 368 of file astNodes.h.
References h::AstFunction::m_params.
void h::AstClosureType::AddParameter (AstType * x) [inline, inherited]
Definition at line 1032 of file astNodes.h.
References h::AstClosureType::m_params.
void h::AstMemberFunction::AddReturnType (AstType * x) [inline, inherited]
Definition at line 262 of file astNodes.h.
References h::AstMemberFunction::m_returns.
void h::AstInterfaceMember::AddReturnType (AstType * x) [inline, inherited]
Definition at line 317 of file astNodes.h.
References h::AstInterfaceMember::m_returns.
void h::AstFunction::AddReturnType (AstType * x) [inline, inherited]
Definition at line 365 of file astNodes.h.
References h::AstFunction::m_returns.
void h::AstClosureType::AddReturnType (AstType * x) [inline, inherited]
Definition at line 1035 of file astNodes.h.
References h::AstClosureType::m_returns.
void h::AstBlock::AddStatement (AstStatement * x) [inline, inherited]
Definition at line 781 of file astNodes.h.
References h::AstBlock::m_stmts.
void h::AstFunction::AddStatement (AstStatement * x) [inline, inherited]
Definition at line 371 of file astNodes.h.
References h::AstFunction::m_stmts.
void h::AstForStmt::AddStatement (AstStatement * x) [inline, inherited]
Definition at line 445 of file astNodes.h.
References h::AstForStmt::m_stmts.
void h::AstParStmt::AddStatement (AstStatement * x) [inline, inherited]
Definition at line 605 of file astNodes.h.
References h::AstParStmt::m_calls.
void h::AstWhileStmt::AddStatement (AstStatement * x) [inline, inherited]
Definition at line 463 of file astNodes.h.
References h::AstWhileStmt::m_stmts.
void h::AstIfStmt::AddThenStatement (AstStatement * x) [inline, inherited]
Definition at line 426 of file astNodes.h.
References h::AstIfStmt::m_stmts.
h::AstClassMember::AstClassMember (YYLTYPE loc) [inline, inherited]
Definition at line 251 of file astNodes.h.
bool h::AstType::CompatibleWith (AstExpr * ty) [inline, inherited]
Definition at line 120 of file astNodes.h.
References h::AstExpr::GetTypeExpr(), h::AstType::IsBool(), h::AstExpr::IsBool(), h::AstType::IsChar(), h::AstExpr::IsChar(), h::AstType::IsFloat(), h::AstExpr::IsFloat(), h::AstType::IsInteger(), h::AstExpr::IsInteger(), h::AstExpr::IsNull(), h::AstType::IsRef(), h::AstType::IsString(), and h::AstExpr::IsString().
void h::PtNode::Dump () [inline, inherited]
Print out a representation of the node to std::cerr.
Note:
Callable from GDB.
Definition at line 82 of file PtNode.h.
References Print().
void h::AstNode::Dump () [inline, inherited]
Print out a representation of the node to std::cerr.
Note:
Callable from GDB.
Definition at line 62 of file AstNode.h.
References h::AstNode::Print().
h::GENERIC_EXPR (Or)
h::GENERIC_EXPR (And)
h::GENERIC_EXPR (Xor)
h::GENERIC_EXPR (Eq)
h::GENERIC_EXPR (Ne)
h::GENERIC_EXPR (Lt)
h::GENERIC_EXPR (LogicalAnd)
h::GENERIC_EXPR (Postfix)
h::GENERIC_EXPR (Leq)
h::GENERIC_EXPR (Member)
h::GENERIC_EXPR (Gt)
h::GENERIC_EXPR (Geq)
h::GENERIC_EXPR (Shl)
h::GENERIC_EXPR (Shr)
h::GENERIC_EXPR (Add)
h::GENERIC_EXPR (Index)
h::GENERIC_EXPR (Sub)
h::GENERIC_EXPR (Mul)
h::GENERIC_EXPR (Div)
h::GENERIC_EXPR (Mod)
h::GENERIC_EXPR (LogicalOr)
h::GENERIC_EXPR (Prefix)
h::GENERIC_EXPR_B (LogicalAnd)
h::GENERIC_EXPR_B (LogicalOr)
static AstBoolExpr* h::AstBoolExpr::get (bool b) [inline, static, inherited]
Definition at line 664 of file astNodes.h.
References h::AstBoolExpr::s_false, and h::AstBoolExpr::s_true.
Referenced by h::AstMemberExpr::GetTypeExpr(), and h::AstIndexExpr::GetTypeExpr().
VIRTUAL_MEMBERS_PURE AstBindingList h::PtType::GetAstBindingList () [inherited]
YYLTYPE h::PtNode::GetLocationAsYYLTYPE () [inline, inherited]
Definition at line 86 of file PtNode.h.
YYLTYPE h::AstNode::GetLocationAsYYLTYPE () [inline, inherited]
Definition at line 66 of file AstNode.h.
References h::AstNode::m_loc.
virtual VIRTUAL_MEMBERS std::string h::AstConst::GetName () [inline, virtual, inherited]
Reimplemented from h::AstDecl.
Definition at line 196 of file astNodes.h.
References h::AstConst::m_name, and h::AstIdentifier::str().
virtual std::string h::AstClass::GetName () [inline, virtual, inherited]
Reimplemented from h::AstDecl.
Definition at line 232 of file astNodes.h.
References h::AstClass::m_name, and h::AstIdentifier::str().
virtual VIRTUAL_MEMBERS std::string h::AstInterface::GetName () [inline, virtual, inherited]
Reimplemented from h::AstDecl.
Definition at line 305 of file astNodes.h.
References h::AstInterface::m_name, and h::AstIdentifier::str().
virtual VIRTUAL_MEMBERS std::string h::AstVariant::GetName () [inline, virtual, inherited]
Reimplemented from h::AstDecl.
Definition at line 342 of file astNodes.h.
References h::AstVariant::m_name, and h::AstIdentifier::str().
virtual VIRTUAL_MEMBERS std::string h::AstFunction::GetName () [inline, virtual, inherited]
Reimplemented from h::AstDecl.
Definition at line 377 of file astNodes.h.
References h::AstFunction::m_name, and h::AstIdentifier::str().
virtual VIRTUAL_MEMBERS std::string h::AstUsing::GetName () [inline, virtual, inherited]
Reimplemented from h::AstDecl.
Definition at line 211 of file astNodes.h.
References h::AstUsing::m_name, and h::AstIdentifier::str().
virtual std::string h::AstDecl::GetName () [inline, virtual, inherited]
Reimplemented in h::AstTypedef, h::AstConst, h::AstUsing, h::AstClass, h::AstInterface, h::AstVariant, h::AstFunction, and h::SymbolWrapper.
Definition at line 148 of file astNodes.h.
virtual VIRTUAL_MEMBERS std::string h::AstTypedef::GetName () [inline, virtual, inherited]
Reimplemented from h::AstDecl.
Definition at line 174 of file astNodes.h.
References h::AstTypedef::m_id, and h::AstIdentifier::str().
virtual AstExpr* h::AstIdentifier::GetTypeExpr () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 95 of file astNodes.h.
virtual VIRTUAL_MEMBERS AstExpr* h::AstIndexExpr::GetTypeExpr () [inline, virtual, inherited]
Reimplemented from h::AstBinaryExpr.
Definition at line 728 of file astNodes.h.
References h::AstBoolExpr::get().
virtual VIRTUAL_MEMBERS AstExpr* h::AstMemberExpr::GetTypeExpr () [inline, virtual, inherited]
Reimplemented from h::AstBinaryExpr.
Definition at line 742 of file astNodes.h.
References h::AstBoolExpr::get().
virtual VIRTUAL_MEMBERS AstExpr* h::AstNewExpr::GetTypeExpr () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 762 of file astNodes.h.
References h::AstNewExpr::m_id.
virtual VIRTUAL_MEMBERS AstExpr* h::AstBlock::GetTypeExpr () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 787 of file astNodes.h.
virtual AstExpr* h::AstExpr::GetTypeExpr () [pure virtual, inherited]
Implemented in h::AstIdentifier, h::AstUnaryExpr, h::AstBinaryExpr, h::AstBoolExpr, h::AstIndexExpr, h::AstMemberExpr, h::AstNewExpr, h::AstBlock, h::AstTuple, h::AstCallExpr, h::AstNullExpr, h::AstInteger, h::AstString, h::AstFloat, and h::AstCharacter.
Referenced by h::AstType::CompatibleWith(), h::AstBinaryExpr::GetTypeExpr(), and h::AstUnaryExpr::GetTypeExpr().
virtual VIRTUAL_MEMBERS AstExpr* h::AstTuple::GetTypeExpr () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 809 of file astNodes.h.
virtual VIRTUAL_MEMBERS AstExpr* h::AstCallExpr::GetTypeExpr () [inline, virtual, inherited]
Reimplemented from h::AstUnaryExpr.
Definition at line 927 of file astNodes.h.
virtual AstExpr* h::AstNullExpr::GetTypeExpr () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 946 of file astNodes.h.
virtual AstExpr* h::AstInteger::GetTypeExpr () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 963 of file astNodes.h.
virtual AstExpr* h::AstUnaryExpr::GetTypeExpr () [inline, virtual, inherited]
Implements h::AstExpr.
Reimplemented in h::AstCallExpr.
Definition at line 624 of file astNodes.h.
References h::AstExpr::GetTypeExpr(), and h::AstUnaryExpr::m_n.
virtual AstExpr* h::AstString::GetTypeExpr () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 981 of file astNodes.h.
virtual AstExpr* h::AstFloat::GetTypeExpr () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 999 of file astNodes.h.
virtual AstExpr* h::AstCharacter::GetTypeExpr () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 1017 of file astNodes.h.
virtual AstExpr* h::AstBinaryExpr::GetTypeExpr () [inline, virtual, inherited]
Implements h::AstExpr.
Reimplemented in h::AstIndexExpr, and h::AstMemberExpr.
Definition at line 638 of file astNodes.h.
References h::AstExpr::GetTypeExpr(), and h::AstBinaryExpr::m_n1.
virtual AstExpr* h::AstBoolExpr::GetTypeExpr () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 657 of file astNodes.h.
virtual void h::AstNode::Identify (SymbolTable & symtab, horizon::Module & module) [pure virtual, inherited]
Identify all symbols to the symtab, and load all external symbols to module.
Implemented in h::SymbolWrapper.
virtual VIRTUAL_MEMBERS bool h::AstBoolType::IsBool () [inline, virtual, inherited]
Reimplemented from h::AstType.
Definition at line 1103 of file astNodes.h.
virtual bool h::AstType::IsBool () [inline, virtual, inherited]
Reimplemented in h::AstBoolType.
Definition at line 115 of file astNodes.h.
Referenced by h::AstType::CompatibleWith().
virtual bool h::AstExpr::IsBool () [inline, virtual, inherited]
Reimplemented in h::AstBoolExpr.
Definition at line 77 of file astNodes.h.
Referenced by h::AstType::CompatibleWith().
virtual VIRTUAL_MEMBERS bool h::AstBoolExpr::IsBool () [inline, virtual, inherited]
Reimplemented from h::AstExpr.
Definition at line 656 of file astNodes.h.
virtual VIRTUAL_MEMBERS bool h::AstCharacterType::IsChar () [inline, virtual, inherited]
Reimplemented from h::AstType.
Definition at line 1123 of file astNodes.h.
virtual bool h::AstExpr::IsChar () [inline, virtual, inherited]
Reimplemented in h::AstCharacter.
Definition at line 79 of file astNodes.h.
Referenced by h::AstType::CompatibleWith().
virtual bool h::AstType::IsChar () [inline, virtual, inherited]
Reimplemented in h::AstCharacterType.
Definition at line 117 of file astNodes.h.
Referenced by h::AstType::CompatibleWith().
virtual VIRTUAL_MEMBERS bool h::AstCharacter::IsChar () [inline, virtual, inherited]
Reimplemented from h::AstExpr.
Definition at line 1016 of file astNodes.h.
virtual bool h::AstDecl::IsClass () [inline, virtual, inherited]
Reimplemented in h::AstTypedef, h::AstClass, and h::SymbolWrapper.
Definition at line 149 of file astNodes.h.
Referenced by h::AstTypedef::IsClass().
virtual VIRTUAL_MEMBERS bool h::AstClass::IsClass () [inline, virtual, inherited]
Reimplemented from h::AstDecl.
Definition at line 231 of file astNodes.h.
virtual bool h::AstTypedef::IsClass () [inline, virtual, inherited]
Reimplemented from h::AstDecl.
Definition at line 175 of file astNodes.h.
References Assert, h::AstDecl::IsClass(), h::AstIdentifier::m_decl, and h::AstTypedef::m_id.
virtual VIRTUAL_MEMBERS bool h::AstFloatType::IsFloat () [inline, virtual, inherited]
Reimplemented from h::AstType.
Definition at line 1133 of file astNodes.h.
virtual VIRTUAL_MEMBERS bool h::AstFloat::IsFloat () [inline, virtual, inherited]
Reimplemented from h::AstExpr.
Definition at line 998 of file astNodes.h.
virtual bool h::AstType::IsFloat () [inline, virtual, inherited]
Reimplemented in h::AstFloatType.
Definition at line 116 of file astNodes.h.
Referenced by h::AstType::CompatibleWith().
virtual bool h::AstExpr::IsFloat () [inline, virtual, inherited]
Reimplemented in h::AstFloat.
Definition at line 78 of file astNodes.h.
Referenced by h::AstType::CompatibleWith().
virtual VIRTUAL_MEMBERS bool h::AstIntegerType::IsInteger () [inline, virtual, inherited]
Reimplemented from h::AstType.
Definition at line 1090 of file astNodes.h.
virtual bool h::AstExpr::IsInteger () [inline, virtual, inherited]
Reimplemented in h::AstInteger.
Definition at line 75 of file astNodes.h.
Referenced by h::AstType::CompatibleWith().
virtual bool h::AstType::IsInteger () [inline, virtual, inherited]
Reimplemented in h::AstIntegerType.
Definition at line 113 of file astNodes.h.
Referenced by h::AstType::CompatibleWith().
virtual VIRTUAL_MEMBERS bool h::AstInteger::IsInteger () [inline, virtual, inherited]
Reimplemented from h::AstExpr.
Definition at line 962 of file astNodes.h.
virtual bool h::AstDecl::IsInterface () [inline, virtual, inherited]
Reimplemented in h::AstTypedef, h::AstInterface, and h::SymbolWrapper.
Definition at line 150 of file astNodes.h.
Referenced by h::AstTypedef::IsInterface().
virtual bool h::AstTypedef::IsInterface () [inline, virtual, inherited]
Reimplemented from h::AstDecl.
Definition at line 179 of file astNodes.h.
References Assert, h::AstDecl::IsInterface(), h::AstIdentifier::m_decl, and h::AstTypedef::m_id.
virtual bool h::AstInterface::IsInterface () [inline, virtual, inherited]
Reimplemented from h::AstDecl.
Definition at line 306 of file astNodes.h.
virtual bool h::AstMemberExpr::IsLValue () [inline, virtual, inherited]
Reimplemented from h::AstBinaryExpr.
Definition at line 745 of file astNodes.h.
References h::AstExpr::IsLValue(), and h::AstBinaryExpr::m_n1.
virtual VIRTUAL_MEMBERS bool h::AstPostIncExpr::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 885 of file astNodes.h.
virtual bool h::AstExpr::IsLValue () [pure virtual, inherited]
Implemented in h::AstIdentifier, h::AstBinaryExpr, h::AstBoolExpr, h::AstIndexExpr, h::AstMemberExpr, h::AstNewExpr, h::AstBlock, h::AstTuple, h::AstPreIncExpr, h::AstPreDecExpr, h::AstNegExpr, h::AstNotExpr, h::AstComplementExpr, h::AstPostIncExpr, h::AstPostDecExpr, h::AstCastExpr, h::AstCallExpr, h::AstNullExpr, h::AstInteger, h::AstString, h::AstFloat, and h::AstCharacter.
Referenced by h::AstMemberExpr::IsLValue(), and h::AstIndexExpr::IsLValue().
virtual bool h::AstFloat::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 1002 of file astNodes.h.
virtual bool h::AstCallExpr::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 930 of file astNodes.h.
virtual bool h::AstBoolExpr::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 660 of file astNodes.h.
virtual bool h::AstCharacter::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 1020 of file astNodes.h.
virtual bool h::AstIdentifier::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 98 of file astNodes.h.
virtual VIRTUAL_MEMBERS bool h::AstComplementExpr::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 873 of file astNodes.h.
virtual bool h::AstString::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 984 of file astNodes.h.
virtual VIRTUAL_MEMBERS bool h::AstPostDecExpr::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 897 of file astNodes.h.
virtual bool h::AstCastExpr::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 911 of file astNodes.h.
virtual bool h::AstNewExpr::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 765 of file astNodes.h.
virtual bool h::AstBlock::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 790 of file astNodes.h.
virtual VIRTUAL_MEMBERS bool h::AstPreDecExpr::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 838 of file astNodes.h.
virtual VIRTUAL_MEMBERS bool h::AstPreIncExpr::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 826 of file astNodes.h.
virtual VIRTUAL_MEMBERS bool h::AstNegExpr::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 850 of file astNodes.h.
virtual VIRTUAL_MEMBERS bool h::AstNotExpr::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 861 of file astNodes.h.
virtual bool h::AstTuple::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 812 of file astNodes.h.
virtual bool h::AstNullExpr::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 949 of file astNodes.h.
virtual bool h::AstInteger::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Definition at line 966 of file astNodes.h.
virtual bool h::AstBinaryExpr::IsLValue () [inline, virtual, inherited]
Implements h::AstExpr.
Reimplemented in h::AstIndexExpr, and h::AstMemberExpr.
Definition at line 642 of file astNodes.h.
virtual bool h::AstIndexExpr::IsLValue () [inline, virtual, inherited]
Reimplemented from h::AstBinaryExpr.
Definition at line 731 of file astNodes.h.
References h::AstExpr::IsLValue(), and h::AstBinaryExpr::m_n1.
virtual VIRTUAL_MEMBERS bool h::AstNullExpr::IsNull () [inline, virtual, inherited]
Reimplemented from h::AstExpr.
Definition at line 945 of file astNodes.h.
virtual bool h::AstExpr::IsNull () [inline, virtual, inherited]
Reimplemented in h::AstNullExpr.
Definition at line 80 of file astNodes.h.
Referenced by h::AstType::CompatibleWith().
virtual VIRTUAL_MEMBERS bool h::AstIdentifierType::IsRef () [inline, virtual, inherited]
Reimplemented from h::AstType.
Definition at line 1076 of file astNodes.h.
virtual bool h::AstType::IsRef () [inline, virtual, inherited]
Reimplemented in h::AstIdentifierType.
Definition at line 118 of file astNodes.h.
Referenced by h::AstType::CompatibleWith().
virtual VIRTUAL_MEMBERS bool h::AstString::IsString () [inline, virtual, inherited]
Reimplemented from h::AstExpr.
Definition at line 980 of file astNodes.h.
virtual VIRTUAL_MEMBERS bool h::AstStringType::IsString () [inline, virtual, inherited]
Reimplemented from h::AstType.
Definition at line 1113 of file astNodes.h.
virtual bool h::AstExpr::IsString () [inline, virtual, inherited]
Reimplemented in h::AstString.
Definition at line 76 of file astNodes.h.
Referenced by h::AstType::CompatibleWith().
virtual bool h::AstType::IsString () [inline, virtual, inherited]
Reimplemented in h::AstStringType.
Definition at line 114 of file astNodes.h.
Referenced by h::AstType::CompatibleWith().
void h::PtIdentifier::PrependWithPeriod (char * c) [inline, inherited]
Definition at line 663 of file ptNodes.h.
References h::PtIdentifier::m_str.
virtual void h::PtNode::Print (std::ostream & s) [pure virtual, inherited]
Print out a representation of the node to the given stream.
virtual void h::AstNode::Print (std::ostream & s) [pure virtual, inherited]
Print out a representation of the node to the given stream.
Implemented in h::SymbolWrapper.
Referenced by h::AstNode::Dump().
h::PT_LIST (Type , Type)
h::PT_LIST (ClassMember , ClassMember)
h::PT_LIST (Implements , Identifier)
h::PT_LIST (Argument , Expr)
h::PT_LIST (Statement , Statement)
h::PT_LIST (AsmConstraint , AsmConstraint)
h::PT_LIST (Tuple , Expr)
h::PT_LIST (VariantMember , VariantMember)
h::PT_LIST (InterfaceMember , InterfaceMember)
h::PT_LIST (Param , Parameter)
h::PtAsmMode::PtAsmMode (int i, bool output, YYLTYPE loc) [inline, inherited]
Definition at line 247 of file ptNodes.h.
References h::PtAsmMode::m_str.
h::PtForStmt::PtForStmt (PtExpr * init, PtExpr * cond, PtExpr * each, PtStatementList * stmts, YYLTYPE loc) [inline, inherited]
Definition at line 302 of file ptNodes.h.
virtual void h::AstNode::Resolve (SymbolTable & symtab, horizon::Module & module) [pure virtual, inherited]
Resolve all symbols from the symtab.
Implemented in h::SymbolWrapper.
void h::PtType::SetBindingList (class PtBindingList * l) [inline, inherited]
Definition at line 709 of file ptNodes.h.
References h::PtType::m_binding_list.
void h::AstUnaryExpr::SetNode (AstExpr * n) [inline, inherited]
Definition at line 620 of file astNodes.h.
References h::AstUnaryExpr::m_n.
VIRTUAL_MEMBERS std::string& h::AstIdentifier::str () [inline, inherited]
Definition at line 91 of file astNodes.h.
References h::AstIdentifier::m_str.
Referenced by h::AstFunction::GetName(), h::AstVariant::GetName(), h::AstInterface::GetName(), h::AstClass::GetName(), h::AstUsing::GetName(), h::AstConst::GetName(), and h::AstTypedef::GetName().
virtual AstNode* h::PtNode::ToAst () [pure virtual, inherited]
Convert the node to its AST form.
virtual bool h::AstNode::Verify (horizon::Module & module) [pure virtual, inherited]
Ensures the validity of the AST.
Implemented in h::SymbolWrapper.
virtual h::AstNode::~AstNode () [inline, virtual, inherited]
Definition at line 45 of file AstNode.h.
virtual h::PtNode::~PtNode () [inline, virtual, inherited]
Definition at line 73 of file PtNode.h.
Variable Documentation
VIRTUAL_MEMBERS bool h::AstAsmStmt::m_alignstack [inherited]
Definition at line 416 of file astNodes.h.
std::list<AstExpr*> h::AstNewExpr::m_args [inherited]
Definition at line 770 of file astNodes.h.
Referenced by h::AstNewExpr::AddArgument().
std::list<AstExpr*> h::AstCallExpr::m_args [inherited]
Definition at line 934 of file astNodes.h.
Referenced by h::AstCallExpr::AddArgument().
PtArgumentList* h::PtNewExpr::m_args [inherited]
Definition at line 523 of file ptNodes.h.
VIRTUAL_MEMBERS PtArgumentList* h::PtCallExpr::m_args [inherited]
Definition at line 622 of file ptNodes.h.
bool h::AstBoolExpr::m_b [inherited]
Definition at line 675 of file astNodes.h.
VIRTUAL_MEMBERS bool h::PtBool::m_b [inherited]
Definition at line 636 of file ptNodes.h.
AstBindingList h::AstType::m_binding_list [inherited]
Definition at line 139 of file astNodes.h.
class PtBindingList* h::PtType::m_binding_list [inherited]
Definition at line 717 of file ptNodes.h.
Referenced by h::PtType::SetBindingList().
AstBlock* h::AstCallExpr::m_block [inherited]
Definition at line 935 of file astNodes.h.
PtBlock* h::PtCallExpr::m_block [inherited]
Definition at line 623 of file ptNodes.h.
VIRTUAL_MEMBERS std::list<AstStatement*> h::AstParStmt::m_calls [inherited]
Definition at line 611 of file astNodes.h.
Referenced by h::AstParStmt::AddStatement().
VIRTUAL_MEMBERS PtStatementList* h::PtParStmt::m_calls [inherited]
Definition at line 460 of file ptNodes.h.
PtAsmConstraintList * h::PtAsmStmt::m_clobbers [inherited]
Definition at line 281 of file ptNodes.h.
PtExpr* h::PtForStmt::m_cond [inherited]
Definition at line 310 of file ptNodes.h.
AstExpr* h::AstForStmt::m_cond [inherited]
Definition at line 453 of file astNodes.h.
std::list<AstAsmConstraint*> h::AstAsmStmt::m_constraints[3] [inherited]
Definition at line 418 of file astNodes.h.
Referenced by h::AstAsmStmt::AddConstraint().
double h::AstFloat::m_d [inherited]
Definition at line 1006 of file astNodes.h.
VIRTUAL_MEMBERS double h::PtFloat::m_d [inherited]
Definition at line 689 of file ptNodes.h.
AstDecl* h::AstIdentifier::m_decl [inherited]
Definition at line 103 of file astNodes.h.
Referenced by h::AstTypedef::IsClass(), and h::AstTypedef::IsInterface().
AstDecl* h::AstPolyType::m_decl [inherited]
Definition at line 1065 of file astNodes.h.
AstDecl* h::AstIdentifierType::m_decl [inherited]
Definition at line 1079 of file astNodes.h.
bool h::AstFloatType::m_double [inherited]
Definition at line 1135 of file astNodes.h.
PtExpr * h::PtForStmt::m_each [inherited]
Definition at line 310 of file ptNodes.h.
AstExpr * h::AstForStmt::m_each [inherited]
Definition at line 453 of file astNodes.h.
PtStatementList * h::PtIfStmt::m_else_stmts [inherited]
Definition at line 293 of file ptNodes.h.
std::list<AstStatement*> h::AstIfStmt::m_else_stmts [inherited]
Definition at line 436 of file astNodes.h.
Referenced by h::AstIfStmt::AddElseStatement().
AstExpr* h::AstAsmConstraint::m_expr [inherited]
Definition at line 402 of file astNodes.h.
PtExpr* h::PtAsmConstraint::m_expr [inherited]
Definition at line 269 of file ptNodes.h.
PtExpr* h::PtWhileStmt::m_expr [inherited]
Definition at line 323 of file ptNodes.h.
VIRTUAL_MEMBERS PtExpr* h::PtReturnStmt::m_expr [inherited]
Definition at line 335 of file ptNodes.h.
AstExpr* h::AstConst::m_expr [inherited]
Definition at line 200 of file astNodes.h.
AstExpr* h::AstWhileStmt::m_expr [inherited]
Definition at line 470 of file astNodes.h.
VIRTUAL_MEMBERS AstExpr* h::AstReturnStmt::m_expr [inherited]
Definition at line 483 of file astNodes.h.
PtExpr* h::PtConst::m_expr [inherited]
Definition at line 94 of file ptNodes.h.
VIRTUAL_MEMBERS PtIdentifier * h::PtClass::m_extends [inherited]
Definition at line 116 of file ptNodes.h.
AstIdentifier * h::AstClass::m_extends [inherited]
Definition at line 234 of file astNodes.h.
AstDecl* h::AstClass::m_extends_decl [inherited]
Definition at line 238 of file astNodes.h.
AstIdentifier* h::AstTypedef::m_id [inherited]
Definition at line 185 of file astNodes.h.
Referenced by h::AstTypedef::GetName(), h::AstTypedef::IsClass(), and h::AstTypedef::IsInterface().
std::string h::AstAsmConstraint::m_id [inherited]
Definition at line 401 of file astNodes.h.
AstIdentifier* h::AstNewExpr::m_id [inherited]
Definition at line 769 of file astNodes.h.
Referenced by h::AstNewExpr::GetTypeExpr().
VIRTUAL_MEMBERS PtIdentifier* h::PtNewExpr::m_id [inherited]
Definition at line 522 of file ptNodes.h.
PtIdentifier* h::PtTypedef::m_id [inherited]
Definition at line 81 of file ptNodes.h.
std::list<AstIdentifier*> h::AstClass::m_implements [inherited]
Definition at line 235 of file astNodes.h.
Referenced by h::AstClass::AddImplements().
PtImplementsList* h::PtClass::m_implements [inherited]
Definition at line 117 of file ptNodes.h.
std::list<AstDecl*> h::AstClass::m_implements_decls [inherited]
Definition at line 239 of file astNodes.h.
PtVariableDecl* h::PtForStmt::m_init_decl [inherited]
Definition at line 309 of file ptNodes.h.
AstVariableDecl* h::AstForStmt::m_init_decl [inherited]
Definition at line 452 of file astNodes.h.
VIRTUAL_MEMBERS PtExpr* h::PtForStmt::m_init_expr [inherited]
Definition at line 308 of file ptNodes.h.
VIRTUAL_MEMBERS AstExpr* h::AstForStmt::m_init_expr [inherited]
Definition at line 451 of file astNodes.h.
AstExpr* h::AstVariableDecl::m_initialiser [inherited]
Definition at line 496 of file astNodes.h.
PtExpr* h::PtMemberVariable::m_initialiser [inherited]
Definition at line 157 of file ptNodes.h.
PtExpr* h::PtVariableDecl::m_initialiser [inherited]
Definition at line 348 of file ptNodes.h.
AstExpr* h::AstGlobalVariable::m_initialiser [inherited]
Definition at line 163 of file astNodes.h.
AstExpr* h::AstMemberVariable::m_initialiser [inherited]
Definition at line 291 of file astNodes.h.
PtExpr* h::PtGlobalVariable::m_initialiser [inherited]
Definition at line 69 of file ptNodes.h.
PtAsmConstraintList * h::PtAsmStmt::m_inputs [inherited]
Definition at line 281 of file ptNodes.h.
bool h::AstParStmt::m_is_async [inherited]
Definition at line 612 of file astNodes.h.
bool h::PtParStmt::m_is_async [inherited]
Definition at line 461 of file ptNodes.h.
AstExpr* h::AstArrayType::m_length [inherited]
Definition at line 1053 of file astNodes.h.
PtExpr* h::PtArrayType::m_length [inherited]
Definition at line 740 of file ptNodes.h.
VIRTUAL_MEMBERS AstExpr* h::AstAssign::m_lhs [inherited]
Definition at line 507 of file astNodes.h.
VIRTUAL_MEMBERS AstExpr* h::AstAddAssign::m_lhs [inherited]
Definition at line 517 of file astNodes.h.
VIRTUAL_MEMBERS AstExpr* h::AstSubAssign::m_lhs [inherited]
Definition at line 527 of file astNodes.h.
VIRTUAL_MEMBERS AstExpr* h::AstMulAssign::m_lhs [inherited]
Definition at line 537 of file astNodes.h.
VIRTUAL_MEMBERS AstExpr* h::AstDivAssign::m_lhs [inherited]
Definition at line 547 of file astNodes.h.
VIRTUAL_MEMBERS AstExpr* h::AstAndAssign::m_lhs [inherited]
Definition at line 557 of file astNodes.h.
VIRTUAL_MEMBERS AstExpr* h::AstOrAssign::m_lhs [inherited]
Definition at line 567 of file astNodes.h.
VIRTUAL_MEMBERS AstExpr* h::AstShlAssign::m_lhs [inherited]
Definition at line 587 of file astNodes.h.
VIRTUAL_MEMBERS AstExpr* h::AstShrAssign::m_lhs [inherited]
Definition at line 577 of file astNodes.h.
VIRTUAL_MEMBERS AstExpr* h::AstXorAssign::m_lhs [inherited]
Definition at line 597 of file astNodes.h.
VIRTUAL_MEMBERS PtExpr* h::PtAssign::m_lhs [inherited]
Definition at line 359 of file ptNodes.h.
VIRTUAL_MEMBERS PtExpr* h::PtAddAssign::m_lhs [inherited]
Definition at line 369 of file ptNodes.h.
VIRTUAL_MEMBERS PtExpr* h::PtSubAssign::m_lhs [inherited]
Definition at line 379 of file ptNodes.h.
VIRTUAL_MEMBERS PtExpr* h::PtMulAssign::m_lhs [inherited]
Definition at line 389 of file ptNodes.h.
VIRTUAL_MEMBERS PtExpr* h::PtDivAssign::m_lhs [inherited]
Definition at line 399 of file ptNodes.h.
VIRTUAL_MEMBERS PtExpr* h::PtAndAssign::m_lhs [inherited]
Definition at line 409 of file ptNodes.h.
VIRTUAL_MEMBERS PtExpr* h::PtOrAssign::m_lhs [inherited]
Definition at line 419 of file ptNodes.h.
VIRTUAL_MEMBERS PtExpr* h::PtShrAssign::m_lhs [inherited]
Definition at line 429 of file ptNodes.h.
VIRTUAL_MEMBERS PtExpr* h::PtShlAssign::m_lhs [inherited]
Definition at line 439 of file ptNodes.h.
VIRTUAL_MEMBERS PtExpr* h::PtXorAssign::m_lhs [inherited]
Definition at line 449 of file ptNodes.h.
VIRTUAL_MEMBERS std::list<PtNode*> h::PtList::m_list [inherited]
Definition at line 779 of file ptNodes.h.
Referenced by h::PtList::AddN().
VIRTUAL_MEMBERS std::list<std::pair<PtType*,PtType*> > h::PtBindingList::m_list [inherited]
Definition at line 816 of file ptNodes.h.
Referenced by h::PtBindingList::Add().
YYLTYPE h::PtNode::m_loc [inherited]
Definition at line 90 of file PtNode.h.
YYLTYPE h::AstNode::m_loc [protected, inherited]
Definition at line 71 of file AstNode.h.
Referenced by h::AstNode::GetLocationAsYYLTYPE().
PtClassMemberList* h::PtClass::m_members [inherited]
Definition at line 118 of file ptNodes.h.
std::list<AstInterfaceMember*> h::AstInterface::m_members [inherited]
Definition at line 309 of file astNodes.h.
Referenced by h::AstInterface::AddMember().
std::list<AstClassMember*> h::AstClass::m_members [inherited]
Definition at line 236 of file astNodes.h.
Referenced by h::AstClass::AddMember().
PtInterfaceMemberList* h::PtInterface::m_members [inherited]
Definition at line 181 of file ptNodes.h.
PtVariantMemberList* h::PtVariant::m_members [inherited]
Definition at line 206 of file ptNodes.h.
std::list<AstVariantMember*> h::AstVariant::m_members [inherited]
Definition at line 345 of file astNodes.h.
Referenced by h::AstVariant::AddMember().
std::list<AstExpr*> h::AstTuple::m_members [inherited]
Definition at line 816 of file astNodes.h.
Referenced by h::AstTuple::AddMember().
VIRTUAL_MEMBERS PtAsmMode* h::PtAsmConstraint::m_mode [inherited]
Definition at line 268 of file ptNodes.h.
AstExpr* h::AstUnaryExpr::m_n [inherited]
Definition at line 628 of file astNodes.h.
Referenced by h::AstUnaryExpr::GetTypeExpr(), and h::AstUnaryExpr::SetNode().
uint64_t h::AstInteger::m_n [inherited]
Definition at line 970 of file astNodes.h.
VIRTUAL_MEMBERS uint64_t h::PtInteger::m_n [inherited]
Definition at line 654 of file ptNodes.h.
AstExpr* h::AstBinaryExpr::m_n1 [inherited]
Definition at line 646 of file astNodes.h.
Referenced by h::AstBinaryExpr::GetTypeExpr(), h::AstMemberExpr::IsLValue(), and h::AstIndexExpr::IsLValue().
VIRTUAL_MEMBERS_PURE PtExpr* h::PtExpr::m_n1 [inherited]
Definition at line 475 of file ptNodes.h.
VIRTUAL_MEMBERS_PURE PtExpr * h::PtExpr::m_n2 [inherited]
Definition at line 475 of file ptNodes.h.
AstExpr * h::AstBinaryExpr::m_n2 [inherited]
Definition at line 646 of file astNodes.h.
VIRTUAL_MEMBERS PtIdentifier* h::PtUsing::m_name [inherited]
Definition at line 105 of file ptNodes.h.
VIRTUAL_MEMBERS PtIdentifier* h::PtClass::m_name [inherited]
Definition at line 116 of file ptNodes.h.
AstIdentifier* h::AstVariableDecl::m_name [inherited]
Definition at line 495 of file astNodes.h.
AstIdentifier* h::AstConst::m_name [inherited]
Definition at line 199 of file astNodes.h.
Referenced by h::AstConst::GetName().
AstIdentifier* h::AstInterface::m_name [inherited]
Definition at line 308 of file astNodes.h.
Referenced by h::AstInterface::GetName().
PtIdentifier* h::PtMemberFunction::m_name [inherited]
Definition at line 140 of file ptNodes.h.
VIRTUAL_MEMBERS AstIdentifier* h::AstInterfaceMember::m_name [inherited]
Definition at line 326 of file astNodes.h.
PtIdentifier* h::PtMemberVariable::m_name [inherited]
Definition at line 156 of file ptNodes.h.
AstIdentifier* h::AstVariant::m_name [inherited]
Definition at line 344 of file astNodes.h.
Referenced by h::AstVariant::GetName().
PtIdentifier* h::PtParameter::m_name [inherited]
Definition at line 169 of file ptNodes.h.
VIRTUAL_MEMBERS PtIdentifier* h::PtInterface::m_name [inherited]
Definition at line 180 of file ptNodes.h.
PtIdentifier* h::PtInterfaceMember::m_name [inherited]
Definition at line 193 of file ptNodes.h.
VIRTUAL_MEMBERS PtIdentifier* h::PtVariant::m_name [inherited]
Definition at line 205 of file ptNodes.h.
PtIdentifier* h::PtVariantMember::m_name [inherited]
Definition at line 218 of file ptNodes.h.
PtIdentifier* h::PtFunction::m_name [inherited]
Definition at line 230 of file ptNodes.h.
AstIdentifier* h::AstFunction::m_name [inherited]
Definition at line 379 of file astNodes.h.
Referenced by h::AstFunction::GetName().
AstIdentifier* h::AstVariantMember::m_name [inherited]
Definition at line 357 of file astNodes.h.
VIRTUAL_MEMBERS AstIdentifier* h::AstPolyType::m_name [inherited]
Definition at line 1064 of file astNodes.h.
PtIdentifier* h::PtVariableDecl::m_name [inherited]
Definition at line 347 of file ptNodes.h.
AstIdentifier* h::AstMemberFunction::m_name [inherited]
Definition at line 273 of file astNodes.h.
AstIdentifier* h::AstGlobalVariable::m_name [inherited]
Definition at line 162 of file astNodes.h.
VIRTUAL_MEMBERS PtIdentifier* h::PtPolyType::m_name [inherited]
Definition at line 751 of file ptNodes.h.
AstIdentifier* h::AstIdentifierType::m_name [inherited]
Definition at line 1078 of file astNodes.h.
AstIdentifier* h::AstClass::m_name [inherited]
Definition at line 234 of file astNodes.h.
Referenced by h::AstClass::GetName().
VIRTUAL_MEMBERS PtIdentifier* h::PtIdentifierType::m_name [inherited]
Definition at line 762 of file ptNodes.h.
AstIdentifier* h::AstUsing::m_name [inherited]
Definition at line 213 of file astNodes.h.
Referenced by h::AstUsing::GetName().
PtIdentifier* h::PtGlobalVariable::m_name [inherited]
Definition at line 68 of file ptNodes.h.
AstIdentifier* h::AstMemberVariable::m_name [inherited]
Definition at line 290 of file astNodes.h.
PtIdentifier* h::PtConst::m_name [inherited]
Definition at line 93 of file ptNodes.h.
bool h::PtAsmMode::m_output [inherited]
Definition at line 257 of file ptNodes.h.
VIRTUAL_MEMBERS bool h::AstAsmConstraint::m_output [inherited]
Definition at line 400 of file astNodes.h.
PtAsmConstraintList* h::PtAsmStmt::m_outputs [inherited]
Definition at line 281 of file ptNodes.h.
PtParamList* h::PtMemberFunction::m_params [inherited]
Definition at line 141 of file ptNodes.h.
std::list<std::pair<AstType*,AstIdentifier*> > h::AstMemberFunction::m_params [inherited]
Definition at line 275 of file astNodes.h.
Referenced by h::AstMemberFunction::AddParameter().
std::list<std::pair<AstType*,AstIdentifier*> > h::AstInterfaceMember::m_params [inherited]
Definition at line 328 of file astNodes.h.
Referenced by h::AstInterfaceMember::AddParameter().
PtParamList* h::PtFunction::m_params [inherited]
Definition at line 231 of file ptNodes.h.
std::list<std::pair<AstType*,AstIdentifier*> > h::AstFunction::m_params [inherited]
Definition at line 381 of file astNodes.h.
Referenced by h::AstFunction::AddParameter().
std::list<std::pair<AstType*,AstIdentifier*> > h::AstBlock::m_params [inherited]
Definition at line 794 of file astNodes.h.
Referenced by h::AstBlock::AddParameter().
VIRTUAL_MEMBERS class PtTypeList* h::PtClosureType::m_params [inherited]
Definition at line 728 of file ptNodes.h.
VIRTUAL_MEMBERS PtParamList* h::PtBlock::m_params [inherited]
Definition at line 534 of file ptNodes.h.
VIRTUAL_MEMBERS std::list<AstType*> h::AstClosureType::m_params [inherited]
Definition at line 1041 of file astNodes.h.
Referenced by h::AstClosureType::AddParameter().
PtParamList* h::PtInterfaceMember::m_params [inherited]
Definition at line 194 of file ptNodes.h.
PtTypeList* h::PtMemberFunction::m_returns [inherited]
Definition at line 139 of file ptNodes.h.
std::list<AstType*> h::AstInterfaceMember::m_returns [inherited]
Definition at line 327 of file astNodes.h.
Referenced by h::AstInterfaceMember::AddReturnType().
VIRTUAL_MEMBERS PtTypeList* h::PtFunction::m_returns [inherited]
Definition at line 229 of file ptNodes.h.
std::list<AstType*> h::AstFunction::m_returns [inherited]
Definition at line 380 of file astNodes.h.
Referenced by h::AstFunction::AddReturnType().
VIRTUAL_MEMBERS class PtTypeList * h::PtClosureType::m_returns [inherited]
Definition at line 728 of file ptNodes.h.
VIRTUAL_MEMBERS std::list<AstType*> h::AstClosureType::m_returns [inherited]
Definition at line 1041 of file astNodes.h.
Referenced by h::AstClosureType::AddReturnType().
VIRTUAL_MEMBERS PtTypeList* h::PtInterfaceMember::m_returns [inherited]
Definition at line 192 of file ptNodes.h.
std::list<AstType*> h::AstMemberFunction::m_returns [inherited]
Definition at line 274 of file astNodes.h.
Referenced by h::AstMemberFunction::AddReturnType().
VIRTUAL_MEMBERS PtExpr * h::PtAndAssign::m_rhs [inherited]
Definition at line 409 of file ptNodes.h.
VIRTUAL_MEMBERS AstExpr * h::AstSubAssign::m_rhs [inherited]
Definition at line 527 of file astNodes.h.
VIRTUAL_MEMBERS AstExpr * h::AstShlAssign::m_rhs [inherited]
Definition at line 587 of file astNodes.h.
VIRTUAL_MEMBERS AstExpr * h::AstAddAssign::m_rhs [inherited]
Definition at line 517 of file astNodes.h.
VIRTUAL_MEMBERS PtExpr * h::PtSubAssign::m_rhs [inherited]
Definition at line 379 of file ptNodes.h.
VIRTUAL_MEMBERS PtExpr * h::PtOrAssign::m_rhs [inherited]
Definition at line 419 of file ptNodes.h.
VIRTUAL_MEMBERS AstExpr * h::AstOrAssign::m_rhs [inherited]
Definition at line 567 of file astNodes.h.
VIRTUAL_MEMBERS AstExpr * h::AstShrAssign::m_rhs [inherited]
Definition at line 577 of file astNodes.h.
VIRTUAL_MEMBERS AstExpr * h::AstXorAssign::m_rhs [inherited]
Definition at line 597 of file astNodes.h.
VIRTUAL_MEMBERS PtExpr * h::PtDivAssign::m_rhs [inherited]
Definition at line 399 of file ptNodes.h.
VIRTUAL_MEMBERS AstExpr * h::AstAndAssign::m_rhs [inherited]
Definition at line 557 of file astNodes.h.
VIRTUAL_MEMBERS PtExpr * h::PtAssign::m_rhs [inherited]
Definition at line 359 of file ptNodes.h.
VIRTUAL_MEMBERS PtExpr * h::PtAddAssign::m_rhs [inherited]
Definition at line 369 of file ptNodes.h.
VIRTUAL_MEMBERS AstExpr * h::AstDivAssign::m_rhs [inherited]
Definition at line 547 of file astNodes.h.
VIRTUAL_MEMBERS PtExpr * h::PtShlAssign::m_rhs [inherited]
Definition at line 439 of file ptNodes.h.
VIRTUAL_MEMBERS AstExpr * h::AstAssign::m_rhs [inherited]
Definition at line 507 of file astNodes.h.
VIRTUAL_MEMBERS PtExpr * h::PtShrAssign::m_rhs [inherited]
Definition at line 429 of file ptNodes.h.
VIRTUAL_MEMBERS PtExpr * h::PtMulAssign::m_rhs [inherited]
Definition at line 389 of file ptNodes.h.
VIRTUAL_MEMBERS PtExpr * h::PtXorAssign::m_rhs [inherited]
Definition at line 449 of file ptNodes.h.
VIRTUAL_MEMBERS AstExpr * h::AstMulAssign::m_rhs [inherited]
Definition at line 537 of file astNodes.h.
VIRTUAL_MEMBERS bool h::AstAsmStmt::m_sideeffect [inherited]
Definition at line 416 of file astNodes.h.
bool h::AstIntegerType::m_signed [inherited]
Definition at line 1092 of file astNodes.h.
bool h::AstMemberFunction::m_static [inherited]
Definition at line 272 of file astNodes.h.
bool h::PtMemberFunction::m_static [inherited]
Definition at line 138 of file ptNodes.h.
bool h::PtMemberVariable::m_static [inherited]
Definition at line 154 of file ptNodes.h.
bool h::AstMemberVariable::m_static [inherited]
Definition at line 288 of file astNodes.h.
std::list<AstStatement*> h::AstIfStmt::m_stmts [inherited]
Definition at line 436 of file astNodes.h.
Referenced by h::AstIfStmt::AddThenStatement().
std::list<AstStatement*> h::AstBlock::m_stmts [inherited]
Definition at line 795 of file astNodes.h.
Referenced by h::AstBlock::AddStatement().
std::list<AstStatement*> h::AstFunction::m_stmts [inherited]
Definition at line 382 of file astNodes.h.
Referenced by h::AstFunction::AddStatement().
PtStatementList* h::PtIfStmt::m_stmts [inherited]
Definition at line 293 of file ptNodes.h.
PtStatementList* h::PtWhileStmt::m_stmts [inherited]
Definition at line 324 of file ptNodes.h.
PtStatementList* h::PtFunction::m_stmts [inherited]
Definition at line 232 of file ptNodes.h.
PtStatementList* h::PtForStmt::m_stmts [inherited]
Definition at line 311 of file ptNodes.h.
std::list<AstStatement*> h::AstForStmt::m_stmts [inherited]
Definition at line 455 of file astNodes.h.
Referenced by h::AstForStmt::AddStatement().
PtStatementList* h::PtBlock::m_stmts [inherited]
Definition at line 535 of file ptNodes.h.
std::list<AstStatement*> h::AstWhileStmt::m_stmts [inherited]
Definition at line 471 of file astNodes.h.
Referenced by h::AstWhileStmt::AddStatement().
VIRTUAL_MEMBERS std::string h::PtString::m_str [inherited]
Definition at line 679 of file ptNodes.h.
std::string h::AstIdentifier::m_str [inherited]
Definition at line 102 of file astNodes.h.
Referenced by h::AstIdentifier::str().
std::string h::AstString::m_str [inherited]
Definition at line 988 of file astNodes.h.
VIRTUAL_MEMBERS std::string h::PtAsmMode::m_str [inherited]
Definition at line 256 of file ptNodes.h.
Referenced by h::PtAsmMode::PtAsmMode().
std::string h::AstAsmStmt::m_str [inherited]
Definition at line 417 of file astNodes.h.
char* h::AstCharacter::m_str [inherited]
Definition at line 1024 of file astNodes.h.
VIRTUAL_MEMBERS std::string h::PtAsmStmt::m_str [inherited]
Definition at line 280 of file ptNodes.h.
VIRTUAL_MEMBERS std::string h::PtIdentifier::m_str [inherited]
Definition at line 669 of file ptNodes.h.
Referenced by h::PtIdentifier::PrependWithPeriod().
VIRTUAL_MEMBERS char* h::PtCharacter::m_str [inherited]
Definition at line 699 of file ptNodes.h.
VIRTUAL_MEMBERS bool h::AstWhileStmt::m_tail_cond [inherited]
Definition at line 469 of file astNodes.h.
VIRTUAL_MEMBERS bool h::PtWhileStmt::m_tail_cond [inherited]
Definition at line 322 of file ptNodes.h.
VIRTUAL_MEMBERS PtExpr* h::PtIfStmt::m_test [inherited]
Definition at line 292 of file ptNodes.h.
VIRTUAL_MEMBERS AstExpr* h::AstIfStmt::m_test [inherited]
Definition at line 435 of file astNodes.h.
VIRTUAL_MEMBERS PtTupleList* h::PtTuple::m_tl [inherited]
Definition at line 545 of file ptNodes.h.
AstType* h::AstTypedef::m_ty [inherited]
Definition at line 184 of file astNodes.h.
VIRTUAL_MEMBERS AstType* h::AstArrayType::m_ty [inherited]
Definition at line 1052 of file astNodes.h.
VIRTUAL_MEMBERS PtType* h::PtConst::m_ty [inherited]
Definition at line 92 of file ptNodes.h.
VIRTUAL_MEMBERS PtType* h::PtCastExpr::m_ty [inherited]
Definition at line 611 of file ptNodes.h.
AstType* h::AstConst::m_ty [inherited]
Definition at line 198 of file astNodes.h.
VIRTUAL_MEMBERS PtType* h::PtTypedef::m_ty [inherited]
Definition at line 80 of file ptNodes.h.
VIRTUAL_MEMBERS AstType* h::AstCastExpr::m_ty [inherited]
Definition at line 909 of file astNodes.h.
VIRTUAL_MEMBERS PtType* h::PtArrayType::m_ty [inherited]
Definition at line 739 of file ptNodes.h.
VIRTUAL_MEMBERS AstType * h::AstArrayType::m_ty2 [inherited]
Definition at line 1052 of file astNodes.h.
VIRTUAL_MEMBERS PtType * h::PtArrayType::m_ty2 [inherited]
Definition at line 739 of file ptNodes.h.
VIRTUAL_MEMBERS AstType* h::AstGlobalVariable::m_type [inherited]
Definition at line 161 of file astNodes.h.
VIRTUAL_MEMBERS PtType* h::PtParameter::m_type [inherited]
Definition at line 168 of file ptNodes.h.
AstType* h::AstMemberVariable::m_type [inherited]
Definition at line 289 of file astNodes.h.
VIRTUAL_MEMBERS PtType* h::PtVariantMember::m_type [inherited]
Definition at line 217 of file ptNodes.h.
VIRTUAL_MEMBERS PtType* h::PtGlobalVariable::m_type [inherited]
Definition at line 67 of file ptNodes.h.
PtType* h::PtMemberVariable::m_type [inherited]
Definition at line 155 of file ptNodes.h.
VIRTUAL_MEMBERS AstType* h::AstVariableDecl::m_type [inherited]
Definition at line 494 of file astNodes.h.
VIRTUAL_MEMBERS AstType* h::AstVariantMember::m_type [inherited]
Definition at line 356 of file astNodes.h.
VIRTUAL_MEMBERS PtType* h::PtVariableDecl::m_type [inherited]
Definition at line 346 of file ptNodes.h.
bool h::AstMemberFunction::m_virtual [inherited]
Definition at line 272 of file astNodes.h.
bool h::AstMemberVariable::m_virtual [inherited]
Definition at line 288 of file astNodes.h.
bool h::PtMemberVariable::m_virtual [inherited]
Definition at line 154 of file ptNodes.h.
bool h::PtMemberFunction::m_virtual [inherited]
Definition at line 138 of file ptNodes.h.
VIRTUAL_MEMBERS unsigned long h::PtMemberFunction::m_visibility [inherited]
Definition at line 137 of file ptNodes.h.
VIRTUAL_MEMBERS int h::PtMemberVariable::m_visibility [inherited]
Definition at line 153 of file ptNodes.h.
VIRTUAL_MEMBERS Visibility h::AstMemberVariable::m_visibility [inherited]
Definition at line 287 of file astNodes.h.
VIRTUAL_MEMBERS Visibility h::AstMemberFunction::m_visibility [inherited]
Definition at line 271 of file astNodes.h.
int h::AstIntegerType::m_width [inherited]
Definition at line 1093 of file astNodes.h.
AstBoolExpr h::AstBoolExpr::s_false [static, inherited]
Definition at line 674 of file astNodes.h.
Referenced by h::AstBoolExpr::get().
AstBoolExpr h::AstBoolExpr::s_true [static, inherited]
Note:
Defined in astPrint.cc
Definition at line 673 of file astNodes.h.
Referenced by h::AstBoolExpr::get().