Horizon: Unhosted (baremetal) compilation
Unhosted (baremetal) compilation
Classes
class DebugStream
struct InterruptState
class InterruptManager
struct kernel_args_arch
struct kernel_args_cpu_arch
struct kernel_args_memory
struct kernel_args_cpu
struct kernel_args_module
struct kernel_args
class PhysicalMemoryManager
class SpecialFile
class SpecialTty
class SpecialRnd
class SpecialModule
class VirtualMemoryManager
Namespaces
namespace horizon
Defines
#define EarlyAssert(x) if(!(x)) {_EarlyAssert(#x, __LINE__, __FILE__);}
#define CR0_NE (1<<5)
#define CR0_TS (1<<3)
#define CR0_EM (1<<2)
#define CR0_MP (1<<1)
#define CR4_OSFXSR (1 << 9)
#define CR4_OSXMMEXCPT (1 << 10)
#define MSR_FS_BASE 0xC0000100
#define MSR_GS_BASE 0xC0000101
#define KERNEL_ARGS_RANGES_MAX 64
#define KERNEL_ARGS_UUID_LEN 64
#define phys_ptr_t uint64_t
#define LINUX_SYSCALLS_DEFINED
#define LOAD_P1(var, ty) ty var = (ty) s.rdi
#define LOAD_P2(var, ty) ty var = (ty) s.rsi
#define LOAD_P3(var, ty) ty var = (ty) s.rdx
#define LOAD_P4(var, ty) ty var = (ty) s.r10
#define LOAD_P5(var, ty) ty var = (ty) s.r8
#define LOAD_P6(var, ty) ty var = (ty) s.r9
#define SAVE_P1(var) s.rdi = (uint64_t) var
#define SAVE_P2(var) s.rsi = (uint64_t) var
#define SAVE_P3(var) s.rdx = (uint64_t) var
#define SAVE_P4(var) s.r10 = (uint64_t) var
#define SAVE_P5(var) s.r8 = (uint64_t) var
#define SAVE_P6(var) s.r9 = (uint64_t) var
#define SAVE_R(var) s.rax = (uint64_t) var
Typedefs
typedef struct kernel_args_arch kernel_args_arch_t
typedef struct kernel_args_cpu_arch kernel_args_cpu_arch_t
typedef struct kernel_args_memory kernel_args_memory_t
typedef struct kernel_args_cpu kernel_args_cpu_t
typedef struct kernel_args_module kernel_args_module_t
typedef struct kernel_args kernel_args_t
typedef void(* SyscallHandler)(InterruptState &)
Functions
void _EarlyAssert (const char *cond, int line, const char *file) __attribute__((noreturn))
void Panic (const char *msg) __attribute__((noreturn))
void Out8 (uint16_t port, uint8_t value)
uint8_t In8 (uint16_t port)
uint16_t In16 (uint16_t port)
uint64_t ReadCR0 ()
void WriteCR0 (uint64_t x)
uint64_t ReadCR3 ()
uint64_t ReadCR4 ()
void WriteCR4 (uint64_t x)
void ReadIDTR (void *p)
void WriteIDTR (void *p)
void WriteFPUCW (uint16_t cw)
void InitialiseFPU ()
void WriteMSR (uint32_t msr, uint64_t val)
uint64_t ReadMSR (uint32_t msr)
void Reboot ()
struct InterruptState __attribute__ ((packed))
void InitialiseSpecialFiles (kernel_args_t *args)
void InitialiseSyscallHandlers ()
Variables
class InterruptManager __attribute__
SyscallHandler g_syscall_handlers [NumLinuxSyscalls]
Detailed Description
This module contains all the classes and algorithms needed to boot Horizon without a host OS.
It emulates a Linux operating system - enough of Linux to boot LLVM and glibc, anyway. This code can bootstrap straight from a bootloader into a "hosted" environment for glibc, libstdc++, libboost, LLVM and of course Horizon to run.
Define Documentation
#define CR0_EM (1<<2)
Definition at line 31 of file cpu.h.
Referenced by InitialiseFPU().
#define CR0_MP (1<<1)
Definition at line 32 of file cpu.h.
Referenced by InitialiseFPU().
#define CR0_NE (1<<5)
Definition at line 29 of file cpu.h.
Referenced by InitialiseFPU().
#define CR0_TS (1<<3)
Definition at line 30 of file cpu.h.
Referenced by InitialiseFPU().
#define CR4_OSFXSR (1 << 9)
Definition at line 33 of file cpu.h.
#define CR4_OSXMMEXCPT (1 << 10)
Definition at line 34 of file cpu.h.
#define EarlyAssert (x) if(!(x)) {_EarlyAssert(#x, __LINE__, __FILE__);}
Definition at line 27 of file assert.h.
Referenced by PhysicalMemoryManager::Allocate(), dladdr(), dlopen(), dlsym(), PhysicalMemoryManager::Initialise(), InitialiseSpecialFiles(), VirtualMemoryManager::Map(), pthread_getspecific(), pthread_key_create(), pthread_key_delete(), pthread_setspecific(), and InterruptManager::RegisterHandler().
#define KERNEL_ARGS_RANGES_MAX 64
Size of arrays in the arguments structure.
Definition at line 33 of file kiwi.h.
#define KERNEL_ARGS_UUID_LEN 64
Definition at line 34 of file kiwi.h.
#define LINUX_SYSCALLS_DEFINED
Definition at line 24 of file syscallHandlers.h.
#define LOAD_P1 (var, ty) ty var = (ty) s.rdi
Definition at line 39 of file syscallHandlers.h.
#define LOAD_P2 (var, ty) ty var = (ty) s.rsi
Definition at line 40 of file syscallHandlers.h.
#define LOAD_P3 (var, ty) ty var = (ty) s.rdx
Definition at line 41 of file syscallHandlers.h.
#define LOAD_P4 (var, ty) ty var = (ty) s.r10
Definition at line 42 of file syscallHandlers.h.
#define LOAD_P5 (var, ty) ty var = (ty) s.r8
Definition at line 43 of file syscallHandlers.h.
#define LOAD_P6 (var, ty) ty var = (ty) s.r9
Definition at line 44 of file syscallHandlers.h.
#define MSR_FS_BASE 0xC0000100
Definition at line 36 of file cpu.h.
#define MSR_GS_BASE 0xC0000101
Definition at line 37 of file cpu.h.
#define phys_ptr_t uint64_t
Definition at line 36 of file kiwi.h.
#define SAVE_P1 (var) s.rdi = (uint64_t) var
Definition at line 47 of file syscallHandlers.h.
#define SAVE_P2 (var) s.rsi = (uint64_t) var
Definition at line 48 of file syscallHandlers.h.
#define SAVE_P3 (var) s.rdx = (uint64_t) var
Definition at line 49 of file syscallHandlers.h.
#define SAVE_P4 (var) s.r10 = (uint64_t) var
Definition at line 50 of file syscallHandlers.h.
#define SAVE_P5 (var) s.r8 = (uint64_t) var
Definition at line 51 of file syscallHandlers.h.
#define SAVE_P6 (var) s.r9 = (uint64_t) var
Definition at line 52 of file syscallHandlers.h.
#define SAVE_R (var) s.rax = (uint64_t) var
Definition at line 54 of file syscallHandlers.h.
Typedef Documentation
typedef struct kernel_args_arch kernel_args_arch_t
x86-specific kernel arguments.
typedef struct kernel_args_cpu_arch kernel_args_cpu_arch_t
x86-specific CPU information structure.
typedef struct kernel_args_cpu kernel_args_cpu_t
Structure containing details of a CPU passed to the kernel.
typedef struct kernel_args_memory kernel_args_memory_t
Structure describing a physical memory range.
typedef struct kernel_args_module kernel_args_module_t
Structure describing a boot module.
typedef struct kernel_args kernel_args_t
Structure containing arguments passed to the kernel.
typedef void(* SyscallHandler)(InterruptState &)
Syscall handler function type.
Definition at line 28 of file syscallHandlers.h.
Function Documentation
struct InterruptState __attribute__ ((packed))
The state when the global interrupt handler is called.
Note:
Written by Joerg Pfahler for Pedigree.
void _EarlyAssert (const char * cond, int line, const char * file)
Definition at line 26 of file assert.cc.
References dout, and memset.
uint16_t In16 (uint16_t port)
Retrieves and returns a 16-bit integer from the given port.
Definition at line 34 of file cpu.cc.
uint8_t In8 (uint16_t port)
Retrieves and returns an 8-bit integer from the given port.
Definition at line 28 of file cpu.cc.
Referenced by DebugStream::operator<<(), and Reboot().
void InitialiseFPU ()
Initialises the FPU/SSE extensions.
Definition at line 70 of file cpu.cc.
References CR0_EM, CR0_MP, CR0_NE, CR0_TS, ReadCR0(), ReadCR4(), WriteCR0(), WriteCR4(), and WriteFPUCW().
Referenced by kmain().
void InitialiseSpecialFiles (kernel_args_t * args)
Definition at line 179 of file SpecialFile.cc.
References kernel_args_module::base, EarlyAssert, kernel_args::module_count, kernel_args::modules, kernel_args_module::next, and kernel_args_module::size.
Referenced by kmain().
void InitialiseSyscallHandlers ()
Initialisation function, to set up handler addresses.
Definition at line 385 of file syscallHandlers.cc.
References g_syscall_handlers, and SpecialFile::get().
Referenced by kmain().
void Out8 (uint16_t port, uint8_t value)
Outputs an 8-bit integer to the given port.
Definition at line 24 of file cpu.cc.
Referenced by DebugStream::Initialise(), DebugStream::operator<<(), and Reboot().
void Panic (const char * msg)
Definition at line 49 of file assert.cc.
References dout.
uint64_t ReadCR0 ()
Reads the value in the CR0 register.
Definition at line 40 of file cpu.cc.
Referenced by InitialiseFPU(), and reg_dump().
uint64_t ReadCR3 ()
Reads the value in the CR3 register.
Definition at line 50 of file cpu.cc.
Referenced by VirtualMemoryManager::Initialise(), and reg_dump().
uint64_t ReadCR4 ()
Reads the value in the CR4 register.
Definition at line 56 of file cpu.cc.
Referenced by InitialiseFPU(), and reg_dump().
void ReadIDTR (void * p)
Reads the value in the IDTR register.
Parameters:
p An array of at least 8 bytes.
uint64_t ReadMSR (uint32_t msr)
Reads from the given MSR.
Definition at line 90 of file cpu.cc.
void Reboot ()
Resets the machine.
Definition at line 96 of file cpu.cc.
References In8(), and Out8().
Referenced by exit_handler().
void WriteCR0 (uint64_t x)
Write to the CR0 register.
Definition at line 46 of file cpu.cc.
Referenced by InitialiseFPU().
void WriteCR4 (uint64_t x)
Writes to the CR4 register.
Definition at line 62 of file cpu.cc.
Referenced by InitialiseFPU().
void WriteFPUCW (uint16_t cw)
Writes the FPU control word.
Definition at line 66 of file cpu.cc.
Referenced by InitialiseFPU().
void WriteIDTR (void * p)
Writes to the IDTR register
Parameters:
p An array of 8 bytes.
void WriteMSR (uint32_t msr, uint64_t val)
Writes to the given Model-specific register.
Definition at line 84 of file cpu.cc.
Variable Documentation
class InterruptManager __attribute__
Manages the assignment and dispatch of interrupts.
Note:
Written by Joerg Pfahler for Pedigree.
SyscallHandler g_syscall_handlers[NumLinuxSyscalls]
Array of size NumLinuxSyscalls containing syscall handler functions.
Definition at line 37 of file syscallHandlers.cc.
Referenced by InitialiseSyscallHandlers(), and syscall_handler().